export const reportColumnKeys = [
  "area",
  "work-name",
  "unit",
  "day-plan",
  "day-fact",
  "day-delta",
  "day-productivity",
  "day-reason",
  "month-total-plan",
  "month-plan",
  "month-fact",
  "month-delta",
  "month-productivity",
  "year-plan",
  "year-fact",
  "year-delta",
  "year-reason",
  "annual-plan",
  "annual-fact",
  "annual-remaining",
] as const;

export type ReportColumnKey = typeof reportColumnKeys[number];

export const reportColumnHeaderFallbacks: Record<ReportColumnKey, string> = {
  area: "Участок",
  "work-name": "Вид работ",
  unit: "Ед.",
  "day-plan": "План суточный",
  "day-fact": "Оперучет",
  "day-delta": "Откл.",
  "day-productivity": "Произв. техники",
  "day-reason": "Причина за сутки",
  "month-total-plan": "План на месяц",
  "month-plan": "План с начала месяца",
  "month-fact": "Маркзамер + оперучет",
  "month-delta": "Откл.",
  "month-productivity": "Произв. накоп.",
  "year-plan": "План с начала года",
  "year-fact": "Маркзамер + недостающий оперучет",
  "year-delta": "Откл.",
  "year-reason": "Причины с накоплением",
  "annual-plan": "Годовой план",
  "annual-fact": "Факт годового плана",
  "annual-remaining": "Остаток",
};

export const reportReasonColumnKeys = new Set<ReportColumnKey>(["day-reason", "year-reason"]);

export const reportCompactColumnKeys = new Set<ReportColumnKey>([
  "area",
  "unit",
  "day-plan",
  "day-fact",
  "day-delta",
  "day-productivity",
  "month-total-plan",
  "month-plan",
  "month-fact",
  "month-delta",
  "month-productivity",
  "year-plan",
  "year-fact",
  "year-delta",
  "annual-plan",
  "annual-fact",
  "annual-remaining",
]);

export const reportColumnTextCaps: Record<ReportColumnKey, number> = {
  area: 12,
  "work-name": 28,
  unit: 4,
  "day-plan": 12,
  "day-fact": 12,
  "day-delta": 12,
  "day-productivity": 12,
  "day-reason": 70,
  "month-total-plan": 12,
  "month-plan": 12,
  "month-fact": 18,
  "month-delta": 12,
  "month-productivity": 12,
  "year-plan": 12,
  "year-fact": 18,
  "year-delta": 12,
  "year-reason": 70,
  "annual-plan": 12,
  "annual-fact": 12,
  "annual-remaining": 12,
};

export const reportColumnAutoMaxWidths: Record<ReportColumnKey, number> = {
  area: 92,
  "work-name": 240,
  unit: 34,
  "day-plan": 56,
  "day-fact": 56,
  "day-delta": 52,
  "day-productivity": 60,
  "day-reason": 260,
  "month-total-plan": 62,
  "month-plan": 62,
  "month-fact": 68,
  "month-delta": 52,
  "month-productivity": 60,
  "year-plan": 62,
  "year-fact": 68,
  "year-delta": 52,
  "year-reason": 300,
  "annual-plan": 62,
  "annual-fact": 62,
  "annual-remaining": 60,
};

export const reportColumnAutoMinWidths: Record<ReportColumnKey, number> = {
  area: 76,
  "work-name": 180,
  unit: 30,
  "day-plan": 44,
  "day-fact": 44,
  "day-delta": 42,
  "day-productivity": 50,
  "day-reason": 120,
  "month-total-plan": 48,
  "month-plan": 48,
  "month-fact": 54,
  "month-delta": 42,
  "month-productivity": 50,
  "year-plan": 48,
  "year-fact": 54,
  "year-delta": 42,
  "year-reason": 140,
  "annual-plan": 48,
  "annual-fact": 48,
  "annual-remaining": 48,
};

export const defaultReportColumnWidths = [
  82,
  220,
  32,
  50,
  50,
  46,
  56,
  150,
  58,
  58,
  64,
  46,
  56,
  58,
  64,
  46,
  150,
  58,
  58,
  56,
];
