export const reportColumnKeys = [
  "area",
  "work-name",
  "unit",
  "day-plan",
  "day-fact",
  "day-delta",
  "day-productivity",
  "day-reason",
  "month-total-plan",
  "month-plan",
  "month-fact",
  "month-delta",
  "month-productivity",
  "year-plan",
  "year-fact",
  "year-delta",
  "year-reason",
  "annual-plan",
  "annual-fact",
  "annual-remaining",
] as const;

export type ReportColumnKey = typeof reportColumnKeys[number];

export const reportColumnHeaderFallbacks: Record<ReportColumnKey, string> = {
  area: "Участок",
  "work-name": "Вид работ",
  unit: "Ед.",
  "day-plan": "План суточный",
  "day-fact": "Оперучет",
  "day-delta": "Откл.",
  "day-productivity": "Произв. техники",
  "day-reason": "Причина за сутки",
  "month-total-plan": "План на месяц",
  "month-plan": "План с начала месяца",
  "month-fact": "Маркзамер + оперучет",
  "month-delta": "Откл.",
  "month-productivity": "Произв. накоп.",
  "year-plan": "План с начала года",
  "year-fact": "Маркзамер + недостающий оперучет",
  "year-delta": "Откл.",
  "year-reason": "Причины с накоплением",
  "annual-plan": "Годовой план",
  "annual-fact": "Факт годового плана",
  "annual-remaining": "Остаток",
};

export const reportReasonColumnKeys = new Set<ReportColumnKey>(["day-reason", "year-reason"]);

export const reportColumnTextCaps: Record<ReportColumnKey, number> = {
  area: 12,
  "work-name": 28,
  unit: 4,
  "day-plan": 12,
  "day-fact": 12,
  "day-delta": 12,
  "day-productivity": 12,
  "day-reason": 70,
  "month-total-plan": 12,
  "month-plan": 12,
  "month-fact": 18,
  "month-delta": 12,
  "month-productivity": 12,
  "year-plan": 12,
  "year-fact": 18,
  "year-delta": 12,
  "year-reason": 70,
  "annual-plan": 12,
  "annual-fact": 12,
  "annual-remaining": 12,
};

export const reportColumnAutoMaxWidths: Record<ReportColumnKey, number> = {
  area: 95,
  "work-name": 260,
  unit: 48,
  "day-plan": 82,
  "day-fact": 82,
  "day-delta": 70,
  "day-productivity": 88,
  "day-reason": 260,
  "month-total-plan": 92,
  "month-plan": 104,
  "month-fact": 122,
  "month-delta": 70,
  "month-productivity": 92,
  "year-plan": 104,
  "year-fact": 128,
  "year-delta": 70,
  "year-reason": 300,
  "annual-plan": 92,
  "annual-fact": 100,
  "annual-remaining": 82,
};

export const defaultReportColumnWidths = [
  80,
  240,
  42,
  72,
  72,
  60,
  82,
  150,
  84,
  96,
  110,
  60,
  82,
  102,
  120,
  60,
  150,
  88,
  96,
  78,
];
