import { reportRowKey } from "./display";
import type { ReportCustomerConfig, ReportRow } from "./types";

export const defaultReportRows: ReportRow[] = [
  {
    area: "Аксу",
    name: "Подача руды в бункер ЗИФ КАТех",
    unit: "тн",
    dayPlan: 2064,
    dayFact: 2102,
    dayProductivity: 2102,
    dayReason: "",
    monthTotalPlan: 62892,
    monthPlan: 23988,
    monthFact: 25100,
    monthSurveyFact: 22998,
    monthOperFact: 2102,
    monthProductivity: 25100,
    yearPlan: 208500,
    yearFact: 216698,
    yearSurveyFact: 214596,
    yearOperFact: 2102,
    yearReason: "",
    annualPlan: 734781,
    annualFact: 216698,
  },
  {
    area: "Аксу",
    name: "Перевозка руды с карьера Котенко на ЗИФ КАТех",
    unit: "тн",
    dayPlan: 500,
    dayFact: 665,
    dayProductivity: 665,
    dayReason: "",
    monthTotalPlan: 53200,
    monthPlan: 10600,
    monthFact: 6721,
    monthSurveyFact: 6056,
    monthOperFact: 665,
    monthProductivity: 6721,
    yearPlan: 194793,
    yearFact: 109050,
    yearSurveyFact: 108385,
    yearOperFact: 665,
    yearReason: "Ремонт транспортировочной техники; перевозка приостановлена по инициативе ТОО \"Казахалтын Technology\"; погодные условия; перенаправление на перевозку дробленной руды.",
    annualPlan: 629956,
    annualFact: 109050,
  },
  {
    area: "Аксу",
    name: "Отсыпка тела дамбы 2 секция ААМ",
    unit: "м3",
    dayPlan: 4624,
    dayFact: 7780,
    dayProductivity: 7780,
    dayReason: "",
    monthTotalPlan: 134720,
    monthPlan: 51488,
    monthFact: 63727,
    monthSurveyFact: 55947,
    monthOperFact: 7780,
    monthProductivity: 63727,
    yearPlan: 51488,
    yearFact: 76138,
    yearSurveyFact: 68358,
    yearOperFact: 7780,
    yearReason: "",
    annualPlan: 240107,
    annualFact: 76138,
  },
  {
    area: "Акбакай",
    name: "Перевозка горной массы с карьера",
    unit: "м3",
    dayPlan: 10352,
    dayFact: 11171,
    dayProductivity: 11171,
    dayReason: "",
    monthTotalPlan: 314239,
    monthPlan: 123630,
    monthFact: 125674,
    monthSurveyFact: 114503,
    monthOperFact: 11171,
    monthProductivity: 125674,
    yearPlan: 980026,
    yearFact: 965596,
    yearSurveyFact: 954425,
    yearOperFact: 11171,
    yearReason: "Ожидание сортового плана; ожидание ВР; ремонт погрузочной техники; ремонт транспортировочной техники; погодные условия.",
    annualPlan: 3827026,
    annualFact: 965596,
  },
  {
    area: "Акбакай",
    name: "Подача руды на ЗИФ",
    unit: "тн",
    dayPlan: 3331,
    dayFact: 1227,
    dayProductivity: 1227,
    dayReason: "Простой ДСК.",
    monthTotalPlan: 91102,
    monthPlan: 31145,
    monthFact: 38224,
    monthSurveyFact: 36997,
    monthOperFact: 1227,
    monthProductivity: 38224,
    yearPlan: 338528,
    yearFact: 350767,
    yearSurveyFact: 349540,
    yearOperFact: 1227,
    yearReason: "",
    annualPlan: 1200000,
    annualFact: 350767,
  },
];

export const defaultReportCustomers: ReportCustomerConfig[] = [
  {
    id: "aa-mining",
    label: "ТОО AA Mining",
    ptoCode: "AAM",
    visible: true,
    autoShowRows: true,
    rowKeys: defaultReportRows.map(reportRowKey),
    hiddenRowKeys: [],
    rowLabels: {},
    summaryRows: [],
    areaOrder: [],
    workOrder: {},
  },
  {
    id: "ak-altynalmas",
    label: "АО АК Алтыналмас",
    ptoCode: "AA",
    visible: true,
    autoShowRows: false,
    rowKeys: [],
    hiddenRowKeys: [],
    rowLabels: {},
    summaryRows: [],
    areaOrder: [],
    workOrder: {},
  },
  {
    id: "aa-engineering",
    label: "ТОО AA Engineering",
    ptoCode: "AAE",
    visible: true,
    autoShowRows: false,
    rowKeys: [],
    hiddenRowKeys: [],
    rowLabels: {},
    summaryRows: [],
    areaOrder: [],
    workOrder: {},
  },
];

export const defaultReportCustomerId = defaultReportCustomers[0].id;
