import type {
  CreatePtoDateEditablePropsModelOptions,
  PtoDateEditableProps,
} from "@/features/pto/ptoDateContainerPropsTypes";

export function createPtoDateEditableProps({
  props,
  toolbar,
  rowsColumnsModel,
  draftRowController,
  formulaController,
  headerRenderers,
}: CreatePtoDateEditablePropsModelOptions): PtoDateEditableProps {
  const {
    setRows,
    ptoAreaTabs,
    ptoPlanYear,
    reportDate,
    ptoDateEditing,
    ptoRowHeights,
    ptoDateOptionMaps,
    ptoDateTableScrollRef,
    draggedPtoRowId,
    ptoDropTarget,
    hoveredPtoAddRowId,
    ptoFormulaDraft,
    ptoSelectionDraggingRef,
    ptoDraftRowFields,
    setDraggedPtoRowId,
    setPtoDropTarget,
    setHoveredPtoAddRowId,
    requestPtoDatabaseSave,
    handlePtoDateTableScroll,
    startPtoRowResize,
    removeLinkedPtoDateRow,
    getPtoDropPosition,
    moveLinkedPtoDateRow,
    updatePtoDateRow,
    beginPtoRowTextDraft,
    getPtoRowTextDraft,
    updatePtoRowTextDraft,
    commitPtoRowTextDraft,
    cancelPtoRowTextDraft,
    ptoTab,
  } = props;
  const {
    carryoverHeader,
    columnWidthByKey,
    displayPtoMonthGroups,
    editableMonthTotal,
    filteredRows,
    getEffectiveCarryover,
    getRowDateTotals,
    renderedRows,
    showCustomerCode,
    showLocation,
    tableColumns,
    tableMinWidth,
    bottomSpacerHeight,
    ptoColumnResizeHandler,
    tableSpacerColSpan,
    topSpacerHeight,
    virtualStartIndex,
  } = rowsColumnsModel;
  const {
    updateDraftField: updatePtoDraftField,
    handleDraftKeyDown: handlePtoDraftKeyDown,
    addRowAfter: addPtoRowAfter,
    addRowFromDraft: addPtoRowFromDraft,
  } = draftRowController;
  const {
    formulaCellActive,
    formulaCellDomKey,
    formulaCellEditing,
    formulaRowEditing,
    formulaCellSelected,
    formulaCellsByRowId,
    handleFormulaCellKeyDown,
    handleFormulaCellMouseDown,
    handleFormulaCellMouseEnter,
    selectFormulaCell,
    selectFormulaRange,
    startInlineFormulaEdit,
    commitInlineFormulaEdit,
    updateFormulaValue,
  } = formulaController;
  const {
    renderPtoHeaderText,
    renderPtoMonthHeader,
  } = headerRenderers;

  return {
    allAreasKey: ptoDateOptionMaps.allAreasKey,
    areaTabs: ptoAreaTabs,
    toolbar,
    scrollRef: ptoDateTableScrollRef,
    onScroll: handlePtoDateTableScroll,
    tableColumns,
    tableMinWidth,
    headerProps: {
      showCustomerCode,
      showLocation,
      ptoPlanYear,
      carryoverHeader,
      monthGroups: displayPtoMonthGroups,
      columnWidthByKey,
      onResizeStart: ptoColumnResizeHandler,
      renderHeaderText: renderPtoHeaderText,
      renderMonthHeader: renderPtoMonthHeader,
    },
    bodyProps: {
      addRowAfter: addPtoRowAfter,
      addRowFromDraft: addPtoRowFromDraft,
      beginPtoRowTextDraft,
      bottomSpacerHeight,
      cancelPtoRowTextDraft,
      carryoverHeader,
      commitInlineFormulaEdit,
      commitPtoRowTextDraft,
      displayPtoMonthGroups,
      draggedPtoRowId,
      editableMonthTotal,
      filteredRows,
      formulaCellActive,
      formulaCellDomKey,
      formulaCellEditing,
      formulaRowEditing,
      formulaCellSelected,
      formulaCellsByRowId,
      getEffectiveCarryover,
      getPtoDropPosition,
      getPtoRowTextDraft,
      getRowDateTotals,
      handleDraftKeyDown: handlePtoDraftKeyDown,
      handleFormulaCellKeyDown,
      handleFormulaCellMouseDown,
      handleFormulaCellMouseEnter,
      hoveredPtoAddRowId,
      moveLinkedPtoDateRow,
      ptoDateEditing,
      ptoDateOptionMaps,
      ptoDraftRowFields,
      ptoDropTarget,
      ptoFormulaDraft,
      ptoRowHeights,
      ptoSelectionDraggingRef,
      ptoTab,
      removeLinkedPtoDateRow,
      renderedRows,
      reportDate,
      requestPtoDatabaseSave,
      selectFormulaCell,
      selectFormulaRange,
      setDraggedPtoRowId,
      setHoveredPtoAddRowId,
      setPtoDropTarget,
      setRows,
      showCustomerCode,
      showLocation,
      startInlineFormulaEdit,
      startPtoRowResize,
      tableMinWidth,
      tableSpacerColSpan,
      topSpacerHeight,
      updateDraftField: updatePtoDraftField,
      updateFormulaValue,
      updatePtoDateRow,
      updatePtoRowTextDraft,
      virtualStartIndex,
    },
  };
}
