import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createEmptyPtoDateModel } from "../features/app/emptyPtoDateModel";
import { repairAdminReportText } from "../features/reports/admin/adminReportText";

const testDir = dirname(fileURLToPath(import.meta.url));
const appPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/AppPrimaryContent.tsx"), "utf8");
const initialAppDataLoadStepsSource = readFileSync(resolve(testDir, "../features/app/initialAppDataLoadSteps.ts"), "utf8");
const initialAppDatabaseBootstrapSource = readFileSync(resolve(testDir, "../features/app/initialAppDatabaseBootstrap.ts"), "utf8");
const navigationSelectionHandlersSource = readFileSync(resolve(testDir, "../features/navigation/useNavigationSelectionHandlers.ts"), "utf8");
const appUndoSchedulerSource = readFileSync(resolve(testDir, "../features/app/useAppUndoScheduler.ts"), "utf8");
const ptoBucketsGridModelSource = readFileSync(resolve(testDir, "../features/pto/ptoBucketsGridModel.ts"), "utf8");
const ptoDateFormulaControllerSource = readFileSync(resolve(testDir, "../features/pto/ptoDateFormulaController.ts"), "utf8");
const ptoDateFormulaModelSource = readFileSync(resolve(testDir, "../features/pto/ptoDateFormulaModel.ts"), "utf8");
const ptoDateFormulaSelectionModelSource = readFileSync(resolve(testDir, "../features/pto/ptoDateFormulaSelectionModel.ts"), "utf8");
const ptoDateTableViewModelSource = readFileSync(resolve(testDir, "../features/pto/ptoDateTableViewModel.ts"), "utf8");
const ptoDateRowsColumnsModelSource = readFileSync(resolve(testDir, "../features/pto/ptoDateRowsColumnsModel.ts"), "utf8");
const ptoSectionSource = readFileSync(resolve(testDir, "../features/pto/PtoSection.tsx"), "utf8");
const ptoStaticTabContentSource = readFileSync(resolve(testDir, "../features/pto/PtoStaticTabContent.tsx"), "utf8");
const usePtoBucketsGridEditingSource = readFileSync(resolve(testDir, "../features/pto/usePtoBucketsGridEditing.ts"), "utf8");
const ptoDateEditableTableBodySource = readFileSync(resolve(testDir, "../features/pto/PtoDateEditableTableBody.tsx"), "utf8");
const ptoDateEditableTableRowSource = readFileSync(resolve(testDir, "../features/pto/PtoDateEditableTableRow.tsx"), "utf8");
const ptoDateEditingResetSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateEditingReset.ts"), "utf8");
const ptoBucketsTableSource = readFileSync(resolve(testDir, "../features/pto/PtoBucketsTable.tsx"), "utf8");
const ptoBucketsTableRowSource = readFileSync(resolve(testDir, "../features/pto/PtoBucketsTableRow.tsx"), "utf8");
const ptoBucketValueCellSource = readFileSync(resolve(testDir, "../features/pto/PtoBucketValueCell.tsx"), "utf8");
const ptoBucketsPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoBucketsPrimaryContent.tsx"), "utf8");
const useAppPtoSupplementalTablesSource = readFileSync(resolve(testDir, "../features/app/useAppPtoSupplementalTables.ts"), "utf8");
const useAppPtoBucketSupplementalTablesSource = readFileSync(resolve(testDir, "../features/app/useAppPtoBucketSupplementalTables.ts"), "utf8");
const useAppPtoDateModelSource = readFileSync(resolve(testDir, "../features/app/useAppPtoDateModel.ts"), "utf8");
const useAppPtoBucketsModelSource = readFileSync(resolve(testDir, "../features/app/useAppPtoBucketsModel.ts"), "utf8");
const usePtoBucketsNavigationModelSource = readFileSync(resolve(testDir, "../features/pto/usePtoBucketsNavigationModel.ts"), "utf8");
const usePtoBucketsViewModelSource = readFileSync(resolve(testDir, "../features/pto/usePtoBucketsViewModel.ts"), "utf8");
const usePtoDateViewModelSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateViewModel.ts"), "utf8");
const ptoPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoPrimaryContent.tsx"), "utf8");
const ptoDataPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoDataPrimaryContent.tsx"), "utf8");
const ptoDateDataPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoDateDataPrimaryContent.tsx"), "utf8");
const ptoBucketsDataPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoBucketsDataPrimaryContent.tsx"), "utf8");
const ptoDatePrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoDatePrimaryContent.tsx"), "utf8");
const ptoDateReadonlyTableSource = readFileSync(resolve(testDir, "../features/pto/PtoDateReadonlyTable.tsx"), "utf8");
const useAppPtoControllersSource = readFileSync(resolve(testDir, "../features/app/useAppPtoControllers.ts"), "utf8");
const useAppPtoDateEditingControllerSource = readFileSync(resolve(testDir, "../features/app/useAppPtoDateEditingController.ts"), "utf8");
const noopPtoDateEditingSource = readFileSync(resolve(testDir, "../features/app/noopPtoDateEditing.ts"), "utf8");
const reportsPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/ReportsPrimaryContent.tsx"), "utf8");
const useAppScreenPropsSource = readFileSync(resolve(testDir, "../features/app/useAppScreenProps.tsx"), "utf8");
const useAppSectionPreloaderSource = readFileSync(resolve(testDir, "../features/app/useAppSectionPreloader.ts"), "utf8");
const useAppRuntimeControllersSource = readFileSync(resolve(testDir, "../features/app/useAppRuntimeControllers.ts"), "utf8");
const useAppAdminDatabasePropsSource = readFileSync(resolve(testDir, "../features/app/useAppAdminDatabaseProps.ts"), "utf8");
const sharedButtonsSource = readFileSync(resolve(testDir, "../shared/ui/buttons.tsx"), "utf8");
const sharedNavigationSource = readFileSync(resolve(testDir, "../shared/ui/navigation.tsx"), "utf8");
const useTableResizeHandlersSource = readFileSync(resolve(testDir, "../components/shared/useTableResizeHandlers.ts"), "utf8");
const useReportColumnLayoutSource = readFileSync(resolve(testDir, "../features/reports/useReportColumnLayout.ts"), "utf8");
const reportColumnTextModelSource = readFileSync(resolve(testDir, "../features/reports/reportColumnTextModel.ts"), "utf8");
const reportRowDisplayViewModelSource = readFileSync(resolve(testDir, "../features/reports/reportRowDisplayViewModel.ts"), "utf8");
const reportRowFactsModelSource = readFileSync(resolve(testDir, "../features/reports/reportRowFactsModel.ts"), "utf8");
const reportTableBodySource = readFileSync(resolve(testDir, "../features/reports/ReportTableBody.tsx"), "utf8");
const reportTableBodyModelSource = readFileSync(resolve(testDir, "../features/reports/reportTableBodyModel.ts"), "utf8");
const reportsSectionSource = readFileSync(resolve(testDir, "../features/reports/ReportsSection.tsx"), "utf8");
const useReportPrintLayoutControllerSource = readFileSync(resolve(testDir, "../features/reports/useReportPrintLayoutController.ts"), "utf8");
const reportPrintLayoutSource = readFileSync(resolve(testDir, "../features/reports/reportPrintLayout.ts"), "utf8");
const reportPrintPageCssSource = readFileSync(resolve(testDir, "../features/reports/reportPrintPageCss.ts"), "utf8");
const reportPrintMediaTableSectionsSource = readFileSync(resolve(testDir, "../features/reports/reportPrintMediaTableSections.ts"), "utf8");
const reportPrintProfileSource = readFileSync(resolve(testDir, "../features/reports/reportPrintProfile.ts"), "utf8");
const useReportRowsModelSource = readFileSync(resolve(testDir, "../features/reports/useReportRowsModel.ts"), "utf8");
const useCustomerReportViewModelSource = readFileSync(resolve(testDir, "../features/reports/useCustomerReportViewModel.ts"), "utf8");
const customerReportRowsModelSource = readFileSync(resolve(testDir, "../features/reports/customerReportRowsModel.ts"), "utf8");
const useAppReportsModelSource = readFileSync(resolve(testDir, "../features/app/useAppReportsModel.ts"), "utf8");
const useAppAdminReportsPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/useAppAdminReportsPrimaryContent.tsx"), "utf8");
const useAdminReportSettingsViewModelSource = readFileSync(resolve(testDir, "../features/reports/useAdminReportSettingsViewModel.ts"), "utf8");
const reportFactSourcePickerStylesSource = readFileSync(resolve(testDir, "../features/reports/admin/ReportFactSourcePickerStyles.ts"), "utf8");
const reportFactSourcePickerCellSource = readFileSync(resolve(testDir, "../features/reports/admin/ReportFactSourcePickerCell.tsx"), "utf8");
const summarySettingsViewModelSource = readFileSync(resolve(testDir, "../features/reports/admin/summarySettingsViewModel.ts"), "utf8");
const adminReportTextSource = readFileSync(resolve(testDir, "../features/reports/admin/adminReportText.ts"), "utf8");
const useDispatchSummaryViewModelSource = readFileSync(resolve(testDir, "../features/dispatch/useDispatchSummaryViewModel.ts"), "utf8");
const dispatchSectionSource = readFileSync(resolve(testDir, "../features/dispatch/DispatchSection.tsx"), "utf8");

const guardedSelectTopTabSource = useAppScreenPropsSource.match(/const guardedSelectTopTab = useCallback\([\s\S]*?\n  \}, \[[\s\S]*?\]\);/)?.[0] ?? "";
const guardedSelectPtoTabSource = useAppScreenPropsSource.match(/const guardedSelectPtoTab = useCallback\([\s\S]*?\n  \}, \[[\s\S]*?\]\);/)?.[0] ?? "";
const emptyPtoDateModel = createEmptyPtoDateModel("2026");
const textFromCodePoints = (...codePoints: number[]) => String.fromCodePoint(...codePoints);
const planText = textFromCodePoints(0x041f, 0x043b, 0x0430, 0x043d);
const win1251PlanMojibake = textFromCodePoints(0x0420, 0x045f, 0x0420, 0x00bb, 0x0420, 0x00b0, 0x0420, 0x0405);
const win1252PlanMojibake = textFromCodePoints(0x00d0, 0x0178, 0x00d0, 0x00bb, 0x00d0, 0x00b0, 0x00d0, 0x00bd);
const sumRowsText = textFromCodePoints(0x0421, 0x0443, 0x043c, 0x043c, 0x0430, 0x20, 0x0441, 0x0442, 0x0440, 0x043e, 0x043a);
const win1251SumRowsMojibake = textFromCodePoints(
  0x0420, 0x040e, 0x0421, 0x0453, 0x0420, 0x0458, 0x0420, 0x0458, 0x0420, 0x00b0,
  0x20,
  0x0421, 0x0403, 0x0421, 0x201a, 0x0421, 0x0402, 0x0420, 0x0455, 0x0420, 0x0454,
);

assert.equal(emptyPtoDateModel.isPtoSection, true);
assert.equal(emptyPtoDateModel.isPtoDateTab, false);
assert.equal(emptyPtoDateModel.isPtoBucketsSection, false);
assert.deepEqual(emptyPtoDateModel.ptoYearTabs, ["2026"]);
assert.deepEqual(emptyPtoDateModel.activePtoDateRows, []);
assert.deepEqual(emptyPtoDateModel.ptoBucketRowLookupSources, []);
assert.equal(repairAdminReportText(win1251PlanMojibake), planText);
assert.equal(repairAdminReportText(win1252PlanMojibake), planText);
assert.equal(repairAdminReportText(win1251SumRowsMojibake), sumRowsText);
assert.equal(repairAdminReportText("Plan 2026"), "Plan 2026");

assert.match(guardedSelectTopTabSource, /selectTopTab\(tab\)/);
assert.doesNotMatch(guardedSelectTopTabSource, /flushPtoDatabasePendingSave\(\)/);
assert.match(useAppScreenPropsSource, /const schedulePtoDatabaseFlush = useCallback\(\(\) => \{[\s\S]*window\.setTimeout\(\(\) => \{[\s\S]*void runtime\.flushPtoDatabasePendingSave\(\);[\s\S]*\}, 0\);[\s\S]*\}, \[runtime\]\);/);
assert.match(guardedSelectTopTabSource, /selectTopTab\(tab\);\s*schedulePtoDatabaseFlush\(\);/);
assert.doesNotMatch(guardedSelectTopTabSource, /if \(canNavigate\) selectTopTab\(tab\)/);
assert.match(guardedSelectPtoTabSource, /selectPtoTab\(tab\)/);
assert.doesNotMatch(guardedSelectPtoTabSource, /flushPtoDatabasePendingSave/);
assert.doesNotMatch(useAppSectionPreloaderSource, /PtoDateEditableTableContainer/);
assert.doesNotMatch(useAppSectionPreloaderSource, /PtoBucketsSection/);
assert.match(useTableResizeHandlersSource, /requestAnimationFrame\(flushResizeMove\)/);
assert.match(useTableResizeHandlersSource, /cancelAnimationFrame\(resizeFrameRef\.current\)/);
assert.match(useTableResizeHandlersSource, /resizeActive: boolean;/);
assert.match(useTableResizeHandlersSource, /const \[resizeDragActive, setResizeDragActive\] = useState\(false\);/);
assert.match(useTableResizeHandlersSource, /if \(!resizeActive \|\| !resizeDragActive\) return undefined;[\s\S]*window\.addEventListener\("mousemove", handleResizeMove\);[\s\S]*window\.addEventListener\("mouseup", handleResizeEnd\);/);
assert.match(useTableResizeHandlersSource, /return \(\) => \{[\s\S]*window\.removeEventListener\("mousemove", handleResizeMove\);[\s\S]*window\.removeEventListener\("mouseup", handleResizeEnd\);[\s\S]*resizePointerRef\.current = null;[\s\S]*ptoResizeStateRef\.current = null;[\s\S]*reportResizeStateRef\.current = null;[\s\S]*clearResizeCursor\(\);[\s\S]*setResizeDragActive\(false\);[\s\S]*\};/);
assert.match(useTableResizeHandlersSource, /\[addAdminLog, requestSave, resizeActive, resizeDragActive, setPtoColumnWidths, setPtoRowHeights, setReportColumnWidths\]/);
assert.match(useTableResizeHandlersSource, /if \(!resizeActive\) return;\s*ptoResizeStateRef\.current/);
assert.match(useTableResizeHandlersSource, /if \(!resizeActive\) return;\s*reportResizeStateRef\.current/);
assert.equal((useTableResizeHandlersSource.match(/setResizeDragActive\(true\)/g) ?? []).length, 3);
assert.match(useReportRowsModelSource, /if \(!needsAutoReportRows \|\| calculatedReportRows\.length === 0\) \{\s*derivedReportRowsCacheRef\.current = new Map\(\);\s*return \[\];\s*\}/);
assert.match(useReportRowsModelSource, /if \(!needsAutoReportRows \|\| !needsReportReasons \|\| !reportPtoIndexes\) return new Map<string, string>\(\);/);
assert.match(useReportRowsModelSource, /if \(!needsReportReasons\) return calculatedReportRows;/);
assert.match(useReportRowsModelSource, /let reasonIndex: ReturnType<typeof createReportReasonIndex> \| null = null;/);
assert.match(useReportRowsModelSource, /reasonIndex \?\?= createReportReasonIndex\(reportReasons\)/);
assert.match(useReportRowsModelSource, /const derivedReportRowsCacheRef = useRef\(new Map<string, CachedDerivedReportRow>\(\)\);/);
assert.match(useReportRowsModelSource, /previous\?\.base === derivedRow/);
assert.match(useReportRowsModelSource, /return previous\.output;/);
assert.match(useAppReportsModelSource, /needsAdminReportAutoRows: boolean;/);
assert.match(useAppReportsModelSource, /const needsCalculatedReportRows = needsAutoReportRows \|\| needsAdminReportAutoRows;/);
assert.match(useAppReportsModelSource, /needsReportIndexes: \(needsReportIndexes \|\| needsAdminReportAutoRows\) && needsReportData/);
assert.match(useAppReportsModelSource, /needsReportReasons: needsVisibleReportRows/);
assert.match(useAppAdminReportsPrimaryContentSource, /const adminReportTabNeedsAutoRows = activeAdminReportSettingsTab === "display" \|\| activeAdminReportCustomer\.autoShowRows;/);
assert.match(useAppAdminReportsPrimaryContentSource, /needsAutoReportRows: false,/);
assert.match(useAdminReportSettingsViewModelSource, /needsAdminReportAutoRows: boolean;/);
assert.match(useAdminReportSettingsViewModelSource, /needsAdminReportAutoRows\s*\?\s*new Map\(derivedReportRows\.map/);
assert.match(useDispatchSummaryViewModelSource, /const normalizedDispatchSearch = useMemo\(\(\) => search\.trim\(\)\.toLowerCase\(\), \[search\]\);/);
assert.match(useDispatchSummaryViewModelSource, /const vehicleSearchRecords = useMemo/);
assert.match(useDispatchSummaryViewModelSource, /const dispatchVehicleSelectOptions = useMemo/);
assert.equal((useDispatchSummaryViewModelSource.match(/buildVehicleDisplayName\(vehicle\)/g) ?? []).length, 1);
assert.doesNotMatch(dispatchSectionSource, /buildVehicleDisplayName/);
assert.doesNotMatch(dispatchSectionSource, /useMemo/);
assert.match(reportRowFactsModelSource, /export function createReportRowFacts\(row: ReportRow\): ReportRowFacts/);
assert.match(reportColumnTextModelSource, /createReportRowFacts\(row\)/);
assert.match(reportPrintLayoutSource, /const facts = createReportRowFacts\(row\)/);
assert.match(reportRowDisplayViewModelSource, /const facts = createReportRowFacts\(row\)/);
assert.doesNotMatch(reportColumnTextModelSource, /reportMonthFact/);
assert.doesNotMatch(reportPrintLayoutSource, /reportYearFact/);
assert.match(useReportColumnLayoutSource, /createReportColumnTextModel\(filteredReports, visibleReportColumnKeys, needsDerivedReportRows\)/);
assert.doesNotMatch(useReportColumnLayoutSource, /reportColumnKeys\.forEach\(\(key\) => \{/);
assert.match(reportColumnTextModelSource, /createEmptyReportColumnValueLists\(columnKeys/);
assert.match(reportColumnTextModelSource, /valuesByKey\[key\]\?\.push\(reportColumnTextValue\(row, key, facts\)\)/);
assert.doesNotMatch(useReportColumnLayoutSource, /reportColumnTextRows/);
assert.doesNotMatch(useReportColumnLayoutSource, /reportColumnTextRows\.map\(\(row\) => row\[key\]\)/);
assert.match(useCustomerReportViewModelSource, /createCustomerReportRows\(derivedReportRows, activeReportCustomer, needsDerivedReportRows\)/);
assert.match(useCustomerReportViewModelSource, /flattenReportAreaGroups\(filteredReportAreaGroups\)/);
assert.doesNotMatch(useCustomerReportViewModelSource, /flatMap/);
assert.match(customerReportRowsModelSource, /function addSummarySourceRowKeys/);
assert.match(customerReportRowsModelSource, /summaryRows\.forEach\(\(summary\) => addSummarySourceRowKeys/);
assert.match(reportTableBodySource, /createReportTableBodyGroups\(\{/);
assert.match(reportTableBodySource, /rowKey=\{rowDescriptor\.rowKey\}/);
assert.match(reportTableBodyModelSource, /function reportTableYearReasonText/);
assert.match(reportTableBodyModelSource, /reportReasons\[reportReasonEntryKey\(reportDate, rowKey\)\]/);
assert.match(reportTableBodyModelSource, /reportYearReasonTextWithManualOverride\(reportReasons, rowKey, reportDate, row\.yearReason\)/);
assert.doesNotMatch(reportTableBodySource, /const rowKey = reportRowDisplayKey\(row\);\s*const dayReasonText/);
assert.doesNotMatch(reportTableBodySource, /reportReasonEntryKey/);
assert.doesNotMatch(reportTableBodySource, /reportYearReasonTextWithManualOverride/);
assert.match(reportsSectionSource, /useReportPrintLayoutController\(\{/);
assert.doesNotMatch(reportsSectionSource, /createReportBodyLayout/);
assert.doesNotMatch(reportsSectionSource, /createReportPrintLayout/);
assert.doesNotMatch(reportsSectionSource, /flushSync/);
assert.match(useReportPrintLayoutControllerSource, /createReportBodyLayout\(filteredReportAreaGroups\)/);
assert.match(useReportPrintLayoutControllerSource, /const reportPrintLayoutToken = useMemo\(\(\) => \(\{[\s\S]*filteredReportAreaGroups,[\s\S]*reportColumnKeys,[\s\S]*reportDate,[\s\S]*reportHeaderLabel,[\s\S]*reportReasons,[\s\S]*\}\)/);
assert.match(useReportPrintLayoutControllerSource, /const \[preparedReportPrintState, setPreparedReportPrintState\] = useState/);
assert.match(useReportPrintLayoutControllerSource, /flushSync\(\(\) => setPreparedReportPrintState\(\{/);
assert.doesNotMatch(useReportPrintLayoutControllerSource, /setPreparedReportPrintState\(null\)/);
assert.doesNotMatch(reportsSectionSource, /const reportPrintLayout = useMemo\(\(\) => createReportPrintLayout/);
assert.match(reportPrintLayoutSource, /import \{ reportPrintProfile, type ReportPrintTextColumnKey \} from "\.\/reportPrintProfile";/);
assert.match(reportPrintProfileSource, /size: "A3 landscape"/);
assert.match(reportPrintProfileSource, /widthBudgetPx: 1400/);
assert.match(reportPrintProfileSource, /perPage: 42/);
assert.match(reportPrintProfileSource, /fontSizePx: 7\.6/);
assert.match(reportPrintProfileSource, /borderColor: "#64748b"/);
assert.match(reportPrintProfileSource, /paddingMmPerMissingRow: 2\.2/);
assert.match(reportPrintPageCssSource, /reportPrintProfile\.page\.size/);
assert.match(reportPrintMediaTableSectionsSource, /reportPrintProfile\.table\.fontSizePx/);
assert.match(reportPrintMediaTableSectionsSource, /reportPrintProfile\.fillRows\.fallbackPaddingPx/);
assert.match(reportPrintMediaTableSectionsSource, /const reportPrintTextColumnFallbackCss = \(Object\.keys\(reportPrintProfile\.columns\.cssFallbackWidths\) as ReportPrintTextColumnKey\[\]\)/);
assert.match(reportPrintMediaTableSectionsSource, /reportPrintTextColumnCssVariable\(key\)/);
assert.doesNotMatch(reportPrintMediaTableSectionsSource, /cssFallbackWidths\["work-name"\]/);
assert.match(reportPrintLayoutSource, /const reportPrintTextScores: Record<ReportPrintTextColumnKey, number>/);
assert.match(reportPrintLayoutSource, /const addReportPrintTextScore = \(key: ReportPrintTextColumnKey, value: string\)/);
assert.doesNotMatch(reportPrintLayoutSource, /const reportPrintRowsPerPage = 42/);
assert.doesNotMatch(reportPrintLayoutSource, /const reportPrintPageWidthBudget = 1400/);
assert.doesNotMatch(reportPrintPageCssSource, /size: A3 landscape/);
assert.doesNotMatch(reportPrintMediaTableSectionsSource, /font-size: 7\.6px/);
assert.doesNotMatch(reportPrintMediaTableSectionsSource, /border: 2px solid #64748b/);
assert.doesNotMatch(reportPrintLayoutSource, /Record<ReportPrintTextColumnKey, string\[\]>/);
assert.match(appPrimaryContentSource, /const shouldShowPtoDatabaseGateOnly = shouldGatePtoDatabase\s*&& renderedTopTab === "pto"\s*&& ptoTabNeedsDatabase;/);
assert.match(appPrimaryContentSource, /if \(shouldShowPtoDatabaseGateOnly\) \{\s*return <PtoDatabaseGate message=\{ptoDatabaseMessage\} \/>;\s*\}/);
assert.match(appPrimaryContentSource, /const ptoTabNeedsDatabase = isPtoDateTableKey\(appState\.ptoTab\) \|\| appState\.ptoTab === "buckets";/);
assert.match(appPrimaryContentSource, /const shouldPreloadSections = appState\.adminDataLoaded && \(!databaseConfigured \|\| ptoDatabaseReady\);/);
assert.match(appPrimaryContentSource, /useAppSectionPreloader\(shouldPreloadSections, \{ includePto: !databaseConfigured \|\| ptoDatabaseReady \}\);/);
assert.match(reportsPrimaryContentSource, /databaseSyncMessage=\{databaseConfigured && !appState\.ptoDatabaseReady \? appState\.ptoDatabaseMessage : ""\}/);
assert.match(reportsSectionSource, /databaseSyncMessage\?: string;/);
assert.match(initialAppDatabaseBootstrapSource, /storageChanged: boolean/);
assert.match(initialAppDatabaseBootstrapSource, /storedState: InitialStoredAppState \| null/);
assert.match(initialAppDatabaseBootstrapSource, /const resolvedStorage = collectInitialStoredAppStorage\(\{ includePto: false \}\);/);
assert.match(initialAppDatabaseBootstrapSource, /resolvedStorage\[key\] = value;/);
assert.match(initialAppDatabaseBootstrapSource, /resolvedStorage\[setting\.key\] = serialized;/);
assert.match(initialAppDatabaseBootstrapSource, /parseInitialStoredAppStateFromStorage\(resolvedStorage, \{ includePto: false \}\)/);
assert.match(initialAppDatabaseBootstrapSource, /adminStorageKeys\.appStateLocalUpdatedAt/);
assert.match(initialAppDatabaseBootstrapSource, /adminStorageKeys\.appSettingsLocalUpdatedAt/);
assert.match(initialAppDatabaseBootstrapSource, /const databaseStorageIncludesSharedSettings = sharedAppSettingKeys\.some/);
assert.match(initialAppDatabaseBootstrapSource, /if \(databaseStorageIncludesSharedSettings\) \{[\s\S]*window\.localStorage\.setItem\(adminStorageKeys\.appSettingsLocalUpdatedAt, databaseAppState\.updatedAt\);/);
assert.match(initialAppDatabaseBootstrapSource, /const currentAppSettingsLocalUpdatedAt = window\.localStorage\.getItem\(adminStorageKeys\.appSettingsLocalUpdatedAt\);/);
assert.match(initialAppDatabaseBootstrapSource, /const currentAppLocalUpdatedAt = window\.localStorage\.getItem\(adminStorageKeys\.appLocalUpdatedAt\);/);
assert.match(initialAppDatabaseBootstrapSource, /const currentLocalUpdatedTime = Math\.max\([\s\S]*timestampToMs\(currentAppSettingsLocalUpdatedAt\),[\s\S]*timestampToMs\(currentAppLocalUpdatedAt\),[\s\S]*\);/);
assert.doesNotMatch(initialAppDatabaseBootstrapSource, /const currentLocalUpdatedAt = window\.localStorage\.getItem\(adminStorageKeys\.appLocalUpdatedAt\);/);
assert.match(initialAppDataLoadStepsSource, /if \(databaseBootstrap\.storageChanged && databaseBootstrap\.storedState\) \{\s*storedState = databaseBootstrap\.storedState;\s*initialReportState = applySharedState\(storedState\);\s*\}/);
assert.doesNotMatch(initialAppDataLoadStepsSource, /if \(databaseBootstrap\.storageChanged\) \{\s*storedState = readInitialStoredAppState\(\{ includePto: false \}\)/);
assert.match(useAppSectionPreloaderSource, /export function useAppSectionPreloader\(\s*enabled: boolean,[\s\S]*includePto/);
assert.match(useAppSectionPreloaderSource, /if \(!enabled\) return undefined;/);
assert.match(useAppSectionPreloaderSource, /const primarySectionPreloaders: SectionPreloader\[\] = \[/);
assert.match(useAppSectionPreloaderSource, /const ptoSectionPreloaders: SectionPreloader\[\] = \[/);
assert.match(useAppSectionPreloaderSource, /includePto[\s\S]*\? \[\.\.\.primarySectionPreloaders, \.\.\.ptoSectionPreloaders\][\s\S]*: primarySectionPreloaders/);
assert.match(useAppSectionPreloaderSource, /const completedPreloaders = new Set<string>\(\);/);
assert.match(useAppSectionPreloaderSource, /completedPreloaders\.has\(sectionPreloaders\[preloadIndex\]\?\.key \?\? ""\)/);
assert.match(useAppSectionPreloaderSource, /completedPreloaders\.add\(preloadSection\.key\)/);
assert.match(useAppSectionPreloaderSource, /runNextPreload\(\);/);
assert.doesNotMatch(useAppSectionPreloaderSource, /function preloadCoreSections/);
assert.match(useAppRuntimeControllersSource, /ptoSelectionActive: topTab === "pto" && ptoDateEditing/);
assert.match(useAppRuntimeControllersSource, /const tableResizeActive = \(topTab === "pto" && ptoDateEditing\) \|\| topTab === "reports";/);
assert.match(useAppRuntimeControllersSource, /resizeActive: tableResizeActive/);
assert.doesNotMatch(useAppRuntimeControllersSource, /ptoSelectionActive: topTab === "pto",/);
assert.match(useAppAdminDatabasePropsSource, /const ptoMemoryTotal = useMemo\(\(\) => \(/);
assert.match(useAppAdminDatabasePropsSource, /const clientSnapshotStatsByKey = useMemo\(\(\) => new Map\(/);
assert.match(useAppAdminDatabasePropsSource, /clientSnapshotStatsByKey\.get\(snapshot\.key\) \?\? clientSnapshotStats\(snapshot\)/);
assert.match(sharedButtonsSource, /const topButtonActiveStyle: CSSProperties = \{/);
assert.match(sharedButtonsSource, /const topButtonGroupInactiveStyle: CSSProperties = \{/);
assert.doesNotMatch(sharedButtonsSource, /const buttonStyle: CSSProperties = \{/);
assert.match(sharedNavigationSource, /style=\{active \? headerSubtabButtonActiveStyle : headerSubtabButtonStyle\}/);
assert.doesNotMatch(sharedNavigationSource, /style=\{\{[\s\S]*headerSubtabButtonStyle/);
assert.match(reportFactSourcePickerStylesSource, /export const modeButtonStyle: CSSProperties = \{[\s\S]*borderWidth: 1,[\s\S]*borderStyle: "solid",[\s\S]*borderColor: "#cbd5e1",/);
assert.match(reportFactSourcePickerStylesSource, /export const modeActiveStyle: CSSProperties = \{[\s\S]*\.\.\.modeButtonStyle,[\s\S]*borderColor: "#0f172a",/);
assert.doesNotMatch(reportFactSourcePickerStylesSource, /export const modeActiveStyle: CSSProperties = \{[\s\S]*border: "1px solid #0f172a"/);
assert.match(adminReportTextSource, /export function repairAdminReportText/);
assert.match(adminReportTextSource, /windows1251TrailBytes/);
assert.match(adminReportTextSource, /windows1252TrailBytes/);
assert.match(reportFactSourcePickerCellSource, /const FACT_SOURCE_VISIBLE_LABEL_LIMIT = 2;/);
assert.match(reportFactSourcePickerCellSource, /repairAdminReportText\(rowLabels\[reportRowKey\(row\)\]\?\.trim\(\) \|\| row\.name\)/);
assert.match(reportFactSourcePickerCellSource, /compactLabels\.join\(" \+ "\)/);
assert.match(reportFactSourcePickerCellSource, /title=\{selectedTitle\}/);
assert.doesNotMatch(reportFactSourcePickerCellSource, /\{isSumMode \? `Сумма: \$\{sourceRowKeys\.length\}` : "Свой"\}/);
assert.match(summarySettingsViewModelSource, /const visibleSummaryArea = summary\.area \|\| areaOptions\[0\] \|\| "";/);
assert.match(summarySettingsViewModelSource, /repairAdminReportText\(customer\.rowLabels\[rowKey\]\?\.trim\(\) \|\| row\.name\)/);
assert.doesNotMatch(summarySettingsViewModelSource, /const visibleSummaryArea = hasStoredArea \? summary\.area : areaOptions\[0\]/);
assert.match(ptoPrimaryContentSource, /createEmptyPtoDateModel\(appState\.ptoPlanYear\)/);
assert.match(ptoPrimaryContentSource, /import\("@\/features\/app\/PtoDataPrimaryContent"\)/);
assert.doesNotMatch(ptoPrimaryContentSource, /useAppPtoDateModel/);
assert.doesNotMatch(ptoPrimaryContentSource, /usePtoDateEditingGlobalReset/);
assert.match(ptoDataPrimaryContentSource, /export function PtoDataPrimaryContent/);
assert.doesNotMatch(ptoDataPrimaryContentSource, /useAppPtoDateModel/);
assert.doesNotMatch(ptoDataPrimaryContentSource, /useAppPtoBucketsModel/);
assert.match(ptoDataPrimaryContentSource, /import\("@\/features\/app\/PtoDateDataPrimaryContent"\)/);
assert.match(ptoDataPrimaryContentSource, /import\("@\/features\/app\/PtoBucketsDataPrimaryContent"\)/);
assert.match(ptoDataPrimaryContentSource, /usePtoDateEditingReset/);
assert.match(useAppPtoDateModelSource, /deferredPtoPlanRows: PtoPlanRow\[\];/);
assert.match(useAppPtoDateModelSource, /deferredPtoOperRows: PtoPlanRow\[\];/);
assert.match(useAppPtoDateModelSource, /deferredPtoSurveyRows: PtoPlanRow\[\];/);
assert.match(ptoDateDataPrimaryContentSource, /useAppPtoDateModel/);
assert.doesNotMatch(ptoDateDataPrimaryContentSource, /useAppPtoBucketsModel/);
assert.match(ptoBucketsDataPrimaryContentSource, /useAppPtoBucketsModel/);
assert.doesNotMatch(ptoBucketsDataPrimaryContentSource, /useAppPtoDateModel/);
assert.doesNotMatch(ptoDataPrimaryContentSource, /usePtoDateEditingGlobalReset/);
assert.doesNotMatch(useAppPtoControllersSource, /useAppPtoDateEditing/);
assert.match(ptoDatePrimaryContentSource, /if \(appState\.ptoDateEditing\) \{/);
assert.match(ptoDatePrimaryContentSource, /function PtoDateReadonlyPrimaryContent/);
assert.match(ptoDatePrimaryContentSource, /ptoDateEditing: noopPtoDateEditing/);
assert.match(ptoDateReadonlyTableSource, /rowHeight=\{rowHeights\[`[$]\{ptoTab\}:[$]\{row\.id\}`\]\}/);
assert.match(ptoDateReadonlyTableSource, /rowHeight\?: number;/);
assert.doesNotMatch(ptoDateReadonlyTableSource, /rowHeights,\s*showCustomerCode/);
assert.doesNotMatch(ptoDateReadonlyTableSource, /const rowHeightKey = `[$]\{ptoTab\}:[$]\{row\.id\}`;/);
assert.match(ptoDatePrimaryContentSource, /function PtoDateEditingPrimaryContent/);
assert.match(ptoDatePrimaryContentSource, /useAppPtoDateEditingController\(\{ appState, models, runtime \}\)/);
assert.match(useAppPtoDateEditingControllerSource, /useAppPtoDateEditing\(\{/);
assert.match(noopPtoDateEditingSource, /export const noopPtoDateEditing/);
assert.match(ptoPrimaryContentSource, /if \(!isPtoDateTab && !isPtoBucketsSection\)/);
assert.doesNotMatch(ptoPrimaryContentSource, /allPtoDateRows/);
assert.match(ptoSectionSource, /PtoStaticTabContent content=\{content\} ptoTab=\{ptoTab\}/);
assert.doesNotMatch(ptoSectionSource, /ptoTab === "bodies"/);
assert.doesNotMatch(ptoSectionSource, /ptoTab === "performance"/);
assert.doesNotMatch(ptoSectionSource, /ptoTab === "cycle"/);
assert.match(ptoStaticTabContentSource, /bodies:/);
assert.match(ptoStaticTabContentSource, /performance:/);
assert.match(ptoStaticTabContentSource, /cycle:/);
assert.match(navigationSelectionHandlersSource, /const selectTopTab = useCallback\(\(tab: TopTab\) => \{\s*startTransition\(\(\) => \{\s*setTopTab\(tab\);\s*\}\);/);
assert.doesNotMatch(appUndoSchedulerSource, /undoCurrentSnapshotRef\.current = cloneAppUndoSnapshot\(nextSnapshot\)/);
assert.match(appUndoSchedulerSource, /undoCurrentSnapshotRef\.current = nextSnapshot;/);
assert.match(appUndoSchedulerSource, /cloneAppUndoSnapshot\(undoCurrentSnapshotRef\.current\)/);
assert.doesNotMatch(ptoBucketsGridModelSource, /editableGridRangeKeys/);
assert.doesNotMatch(ptoBucketsGridModelSource, /editableGridKeyAtOffset/);
assert.match(ptoBucketsGridModelSource, /editableGridAxisRangeKeys/);
assert.match(ptoBucketsGridModelSource, /editableGridAxisCellByOffset/);
assert.match(ptoDateFormulaControllerSource, /const formulaModel = useMemo\(\(\) => \{/);
assert.match(ptoDateFormulaControllerSource, /if \(!ptoDateEditing\) return null;/);
assert.match(ptoDateFormulaControllerSource, /createPtoDateFormulaModel\(\{/);
assert.match(ptoDateFormulaControllerSource, /if \(!ptoDateEditing \|\| !formulaModel\) \{/);
assert.match(ptoDateFormulaControllerSource, /\} = formulaModel;/);
assert.match(ptoDateFormulaControllerSource, /createPtoDateFormulaSelectionModel\(\{/);
assert.match(ptoDateFormulaControllerSource, /\[formulaModel, ptoSelectedCellKeys\]/);
assert.match(ptoDateFormulaModelSource, /editableGridAxisRangeKeys/);
assert.doesNotMatch(ptoDateFormulaModelSource, /const rowStart = Math\.min/);
assert.match(ptoDateFormulaSelectionModelSource, /editableGridAxisCellByOffset/);
assert.doesNotMatch(ptoDateFormulaSelectionModelSource, /const nextRowIndex = Math\.min/);
assert.match(usePtoBucketsGridEditingSource, /editingMode \? rows\.map\(\(row\) => row\.key\) : \[\]/);
assert.match(usePtoBucketsGridEditingSource, /editingMode \? columns\.map\(\(column\) => column\.key\) : \[\]/);
assert.doesNotMatch(ptoDateEditableTableBodySource, /formulaCellsByRowId\.get\(row\.id\)/);
assert.match(ptoDateEditableTableBodySource, /rowProps\.formulaRowEditing\(row\.id\)/);
assert.doesNotMatch(ptoDateEditableTableBodySource, /some\(\(cell\) =>/);
assert.match(ptoDateEditableTableRowSource, /formulaCellEditing=\{formulaCellEditing\}/);
assert.match(ptoDateEditableTableRowSource, /export const PtoDateEditableTableRow = memo\(function PtoDateEditableTableRow/);
assert.match(ptoBucketsTableRowSource, /export const PtoBucketsTableRow = memo\(function PtoBucketsTableRow/);
assert.match(ptoBucketsTableSource, /const rowActiveCell = activeCell\?\.rowKey === row\.key \? activeCell : null;/);
assert.match(ptoBucketsTableSource, /draft=\{rowActiveCell \? draft : ""\}/);
assert.match(ptoBucketsTableSource, /createPtoBucketSelectedKeysByRow\(selectedBucketKeys\)/);
assert.match(ptoBucketsTableSource, /emptyPtoBucketSelectedKeys/);
assert.match(ptoBucketsTableSource, /selectedBucketKeys=\{selectedBucketKeysByRow\.get\(row\.key\) \?\? emptyPtoBucketSelectedKeys\}/);
assert.match(usePtoBucketsGridEditingSource, /usePtoBucketsCellSelection/);
assert.match(usePtoBucketsGridEditingSource, /selectedBucketKeys/);
assert.doesNotMatch(ptoBucketsTableRowSource, /selectedBucketKeys: Set<string>/);
assert.match(ptoBucketsTableRowSource, /selectedBucketKeys: ReadonlySet<string>/);
assert.match(ptoBucketsTableRowSource, /function ptoBucketsTableRowPropsEqual/);
assert.match(ptoBucketsTableRowSource, /bucketRowVisibleValuesEqual\(previous, next\)/);
assert.match(ptoBucketsTableRowSource, /bucketCellSelectionSetsEqual\(previous\.selectedBucketKeys, next\.selectedBucketKeys\)/);
assert.match(ptoBucketsTableRowSource, /\}, ptoBucketsTableRowPropsEqual\);/);
assert.match(ptoBucketsTableRowSource, /cellKey=\{cellKey\}/);
assert.doesNotMatch(ptoBucketValueCellSource, /ptoBucketCellKey/);
assert.match(ptoBucketValueCellSource, /if \(!editingMode\) \{/);
assert.match(ptoBucketValueCellSource, /const cell = \{ rowKey: row\.key, equipmentKey: column\.key \};/);
assert.match(ptoDateEditingResetSource, /setPtoSelectedCellKeys\(\(current\) => \(current\.length === 0 \? current : \[\]\)\)/);
assert.doesNotMatch(ptoDateEditingResetSource, /setPtoSelectedCellKeys\(\[\]\)/);
assert.match(ptoBucketsPrimaryContentSource, /useAppPtoBucketSupplementalTables/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoPlanRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoOperRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoSurveyRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoPlanImportInputRef:/);
assert.doesNotMatch(useAppPtoSupplementalTablesSource, /usePtoBucketsViewModel/);
assert.doesNotMatch(useAppPtoSupplementalTablesSource, /usePtoBucketsEditor/);
assert.match(useAppPtoBucketSupplementalTablesSource, /usePtoBucketsViewModel/);
assert.match(useAppPtoBucketSupplementalTablesSource, /usePtoBucketsEditor/);
assert.doesNotMatch(usePtoBucketsViewModelSource, /ptoBucketRowLookupSourcesSignature\(bucketRowSources\)/);
assert.match(usePtoBucketsViewModelSource, /ptoBucketRowsSignature\(manualRows\)/);
assert.match(usePtoBucketsViewModelSource, /active \? ptoBucketRowsSignature\(manualRows\) : ""/);
assert.match(usePtoBucketsViewModelSource, /createPtoBucketRowsModel\(bucketRowSources, stableManualRows, areaFilter\)/);
assert.match(usePtoBucketsViewModelSource, /useStableBucketRows\(ptoBucketRowsModel\.rows, ptoBucketRowsModel\.signature\)/);
assert.match(usePtoBucketsViewModelSource, /active \? ptoBucketColumnsSourceSignature\(vehicleRows\) : ""/);
assert.match(usePtoBucketsViewModelSource, /useStableBucketColumnVehicleRows/);
assert.match(usePtoBucketsViewModelSource, /createPtoBucketColumnsModel\(stableVehicleRowsForBucketColumns\)/);
assert.doesNotMatch(usePtoBucketsViewModelSource, /createPtoBucketColumnsModel\(vehicleRows\)/);
assert.match(usePtoBucketsViewModelSource, /useStableBucketColumns/);
assert.doesNotMatch(usePtoBucketsNavigationModelSource, /ptoAreaAndBucketRowGroupsSignature/);
assert.match(ptoDateTableViewModelSource, /const emptyPtoRowById = new Map<string, PtoPlanRow>\(\);/);
assert.match(ptoDateTableViewModelSource, /export function createPtoDateFilteredRows/);
assert.match(ptoDateTableViewModelSource, /export function createPtoDateRowById/);
assert.match(ptoDateTableViewModelSource, /return ptoDateEditing \? new Map\(rows\.map\(\(row\) => \[row\.id, row\] as const\)\) : emptyPtoRowById;/);
assert.match(ptoDateRowsColumnsModelSource, /const filteredRows = useMemo\(\(\) => \(\s*createPtoDateFilteredRows/);
assert.match(ptoDateRowsColumnsModelSource, /const rowById = useMemo\(\(\) => \(\s*createPtoDateRowById/);
assert.match(ptoDateRowsColumnsModelSource, /const tableLayoutModel = useMemo\(\(\) => createPtoDateTableModel/);
assert.doesNotMatch(ptoDateRowsColumnsModelSource, /useMemo\(\(\) => createPtoDateTableViewModel/);
assert.match(usePtoDateViewModelSource, /ptoDateEditing: boolean;/);
assert.match(usePtoDateViewModelSource, /const activePtoDateLookupRows = useMemo/);
assert.match(usePtoDateViewModelSource, /if \(ptoTab === "plan"\) return deferredPtoPlanRows;/);
assert.match(usePtoDateViewModelSource, /const activePtoDateLookupBundle = useMemo/);
assert.match(usePtoDateViewModelSource, /createPtoDateLookupSourceBundle\(activePtoDateLookupRows\)/);
assert.match(usePtoDateViewModelSource, /useStablePtoDateLookupSources\(activePtoDateLookupBundle\)/);
assert.match(usePtoDateViewModelSource, /createPtoAreaLookupSourceBundle\(activePtoDateLookupRows\)/);
assert.match(usePtoDateViewModelSource, /\[activePtoDateLookupRows, isPtoDateTab\]/);
assert.match(usePtoDateViewModelSource, /\[activePtoDateLookupBundle\.signature, isPtoDateTab\]/);
assert.doesNotMatch(usePtoDateViewModelSource, /ptoDateRowsLookupSignature/);
assert.doesNotMatch(usePtoDateViewModelSource, /createPtoDateLookupSourceBundle\(activePtoDateRows\)/);
assert.match(usePtoDateViewModelSource, /isPtoDateTab \? yearMonths\(ptoPlanYear\) : \[\]/);
assert.match(usePtoDateViewModelSource, /if \(!isPtoDateTab \|\| !ptoDateEditing\) \{/);
assert.match(usePtoDateViewModelSource, /createPtoAreaLookupSourceBundle/);
assert.match(usePtoDateViewModelSource, /const activePtoAreaLookupBundle = useMemo/);
assert.doesNotMatch(usePtoDateViewModelSource, /createPtoAreaAndBucketRowLookupSourceBundle/);
assert.doesNotMatch(usePtoDateViewModelSource, /ptoBucketManualRows/);
assert.doesNotMatch(useAppPtoDateModelSource, /usePtoBucketsNavigationModel/);
assert.match(useAppPtoDateModelSource, /isPtoBucketsSection: false/);
assert.match(useAppPtoDateModelSource, /ptoAreaTabs: dateModel\.ptoAreaTabs/);
assert.match(useAppPtoBucketsModelSource, /usePtoBucketsNavigationModel/);
assert.match(useAppPtoBucketsModelSource, /createEmptyPtoDateModel\(options\.ptoPlanYear\)/);
assert.match(useAppPtoBucketsModelSource, /isPtoBucketsSection: bucketModel\.isPtoBucketsSection/);
assert.match(useAppPtoBucketsModelSource, /ptoAreaTabs: bucketModel\.ptoBucketAreaTabs/);
assert.match(usePtoBucketsNavigationModelSource, /function useStablePtoAreaAndBucketRowLookupBundle/);
assert.match(usePtoBucketsNavigationModelSource, /bundle\.rowGroupsSignature/);
assert.match(usePtoBucketsNavigationModelSource, /const referenceLookupBundleSnapshot = useMemo/);
assert.match(usePtoBucketsNavigationModelSource, /const referenceLookupBundle = useStablePtoAreaAndBucketRowLookupBundle\(referenceLookupBundleSnapshot\)/);
assert.doesNotMatch(usePtoBucketsNavigationModelSource, /const referenceRowGroupsSignature = useMemo/);
assert.match(usePtoBucketsNavigationModelSource, /createPtoAreaAndBucketRowLookupSourceBundle\(\[deferredPtoPlanRows, deferredPtoSurveyRows, deferredPtoOperRows\]\)/);
assert.match(usePtoBucketsNavigationModelSource, /\[deferredPtoOperRows, deferredPtoPlanRows, deferredPtoSurveyRows, isPtoBucketsSection\]/);
assert.doesNotMatch(usePtoBucketsNavigationModelSource, /\[isPtoBucketsSection, referenceRowGroupsSignature\]/);
assert.match(usePtoBucketsNavigationModelSource, /createPtoBucketAreaLookupSourceBundle\(ptoBucketManualRows\)/);
assert.match(usePtoBucketsNavigationModelSource, /ptoBucketAreaTabs: ptoAreaTabs/);
