import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createEmptyPtoDateModel } from "../features/app/emptyPtoDateModel";

const testDir = dirname(fileURLToPath(import.meta.url));
const appPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/AppPrimaryContent.tsx"), "utf8");
const initialAppDataLoadStepsSource = readFileSync(resolve(testDir, "../features/app/initialAppDataLoadSteps.ts"), "utf8");
const initialAppDatabaseBootstrapSource = readFileSync(resolve(testDir, "../features/app/initialAppDatabaseBootstrap.ts"), "utf8");
const navigationSelectionHandlersSource = readFileSync(resolve(testDir, "../features/navigation/useNavigationSelectionHandlers.ts"), "utf8");
const ptoBucketsGridModelSource = readFileSync(resolve(testDir, "../features/pto/ptoBucketsGridModel.ts"), "utf8");
const ptoDateTableViewModelSource = readFileSync(resolve(testDir, "../features/pto/ptoDateTableViewModel.ts"), "utf8");
const usePtoBucketsGridEditingSource = readFileSync(resolve(testDir, "../features/pto/usePtoBucketsGridEditing.ts"), "utf8");
const ptoDateEditableTableBodySource = readFileSync(resolve(testDir, "../features/pto/PtoDateEditableTableBody.tsx"), "utf8");
const ptoDateEditableTableRowSource = readFileSync(resolve(testDir, "../features/pto/PtoDateEditableTableRow.tsx"), "utf8");
const ptoBucketsTableSource = readFileSync(resolve(testDir, "../features/pto/PtoBucketsTable.tsx"), "utf8");
const ptoBucketsTableRowSource = readFileSync(resolve(testDir, "../features/pto/PtoBucketsTableRow.tsx"), "utf8");
const ptoBucketsPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoBucketsPrimaryContent.tsx"), "utf8");
const useAppPtoSupplementalTablesSource = readFileSync(resolve(testDir, "../features/app/useAppPtoSupplementalTables.ts"), "utf8");
const useAppPtoBucketSupplementalTablesSource = readFileSync(resolve(testDir, "../features/app/useAppPtoBucketSupplementalTables.ts"), "utf8");
const usePtoDateViewModelSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateViewModel.ts"), "utf8");
const ptoPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoPrimaryContent.tsx"), "utf8");
const ptoDataPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/PtoDataPrimaryContent.tsx"), "utf8");
const useAppScreenPropsSource = readFileSync(resolve(testDir, "../features/app/useAppScreenProps.tsx"), "utf8");
const useAppSectionPreloaderSource = readFileSync(resolve(testDir, "../features/app/useAppSectionPreloader.ts"), "utf8");
const useAppAdminDatabasePropsSource = readFileSync(resolve(testDir, "../features/app/useAppAdminDatabaseProps.ts"), "utf8");
const sharedButtonsSource = readFileSync(resolve(testDir, "../shared/ui/buttons.tsx"), "utf8");
const sharedNavigationSource = readFileSync(resolve(testDir, "../shared/ui/navigation.tsx"), "utf8");
const useTableResizeHandlersSource = readFileSync(resolve(testDir, "../components/shared/useTableResizeHandlers.ts"), "utf8");
const useReportColumnLayoutSource = readFileSync(resolve(testDir, "../features/reports/useReportColumnLayout.ts"), "utf8");
const reportTableBodySource = readFileSync(resolve(testDir, "../features/reports/ReportTableBody.tsx"), "utf8");
const reportsSectionSource = readFileSync(resolve(testDir, "../features/reports/ReportsSection.tsx"), "utf8");
const useReportRowsModelSource = readFileSync(resolve(testDir, "../features/reports/useReportRowsModel.ts"), "utf8");
const useAppReportsModelSource = readFileSync(resolve(testDir, "../features/app/useAppReportsModel.ts"), "utf8");
const useAppAdminReportsPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/useAppAdminReportsPrimaryContent.tsx"), "utf8");
const useAdminReportSettingsViewModelSource = readFileSync(resolve(testDir, "../features/reports/useAdminReportSettingsViewModel.ts"), "utf8");
const useDispatchSummaryViewModelSource = readFileSync(resolve(testDir, "../features/dispatch/useDispatchSummaryViewModel.ts"), "utf8");
const dispatchSectionSource = readFileSync(resolve(testDir, "../features/dispatch/DispatchSection.tsx"), "utf8");

const guardedSelectTopTabSource = useAppScreenPropsSource.match(/const guardedSelectTopTab = useCallback\([\s\S]*?\n  \}, \[[\s\S]*?\]\);/)?.[0] ?? "";
const guardedSelectPtoTabSource = useAppScreenPropsSource.match(/const guardedSelectPtoTab = useCallback\([\s\S]*?\n  \}, \[[\s\S]*?\]\);/)?.[0] ?? "";
const emptyPtoDateModel = createEmptyPtoDateModel("2026");

assert.equal(emptyPtoDateModel.isPtoSection, true);
assert.equal(emptyPtoDateModel.isPtoDateTab, false);
assert.equal(emptyPtoDateModel.isPtoBucketsSection, false);
assert.deepEqual(emptyPtoDateModel.ptoYearTabs, ["2026"]);
assert.deepEqual(emptyPtoDateModel.activePtoDateRows, []);
assert.deepEqual(emptyPtoDateModel.ptoBucketRowLookupSources, []);

assert.match(guardedSelectTopTabSource, /flushPtoDatabasePendingSave\(\)/);
assert.match(guardedSelectTopTabSource, /selectTopTab\(tab\)/);
assert.match(guardedSelectTopTabSource, /selectTopTab\(tab\);\s*void runtime\.flushPtoDatabasePendingSave\(\);/);
assert.doesNotMatch(guardedSelectTopTabSource, /if \(canNavigate\) selectTopTab\(tab\)/);
assert.match(guardedSelectPtoTabSource, /selectPtoTab\(tab\)/);
assert.doesNotMatch(guardedSelectPtoTabSource, /flushPtoDatabasePendingSave/);
assert.doesNotMatch(useAppSectionPreloaderSource, /PtoDateEditableTableContainer/);
assert.doesNotMatch(useAppSectionPreloaderSource, /PtoBucketsSection/);
assert.match(useTableResizeHandlersSource, /requestAnimationFrame\(flushResizeMove\)/);
assert.match(useTableResizeHandlersSource, /cancelAnimationFrame\(resizeFrameRef\.current\)/);
assert.match(useReportRowsModelSource, /if \(!needsAutoReportRows \|\| calculatedReportRows\.length === 0\) \{\s*derivedReportRowsCacheRef\.current = new Map\(\);\s*return \[\];\s*\}/);
assert.match(useReportRowsModelSource, /let reasonIndex: ReturnType<typeof createReportReasonIndex> \| null = null;/);
assert.match(useReportRowsModelSource, /reasonIndex \?\?= createReportReasonIndex\(reportReasons\)/);
assert.match(useReportRowsModelSource, /const derivedReportRowsCacheRef = useRef\(new Map<string, CachedDerivedReportRow>\(\)\);/);
assert.match(useReportRowsModelSource, /previous\?\.base === derivedRow/);
assert.match(useReportRowsModelSource, /return previous\.output;/);
assert.match(useAppReportsModelSource, /needsAdminReportAutoRows: boolean;/);
assert.match(useAppReportsModelSource, /const needsCalculatedReportRows = needsAutoReportRows \|\| needsAdminReportAutoRows;/);
assert.match(useAppReportsModelSource, /needsReportIndexes: \(needsReportIndexes \|\| needsAdminReportAutoRows\) && needsReportData/);
assert.match(useAppAdminReportsPrimaryContentSource, /const adminReportTabNeedsAutoRows = activeAdminReportSettingsTab === "display" \|\| activeAdminReportCustomer\.autoShowRows;/);
assert.match(useAppAdminReportsPrimaryContentSource, /needsAutoReportRows: false,/);
assert.match(useAdminReportSettingsViewModelSource, /needsAdminReportAutoRows: boolean;/);
assert.match(useAdminReportSettingsViewModelSource, /needsAdminReportAutoRows\s*\?\s*new Map\(derivedReportRows\.map/);
assert.match(useDispatchSummaryViewModelSource, /const normalizedDispatchSearch = useMemo\(\(\) => search\.trim\(\)\.toLowerCase\(\), \[search\]\);/);
assert.match(useDispatchSummaryViewModelSource, /const vehicleSearchRecords = useMemo/);
assert.match(useDispatchSummaryViewModelSource, /const dispatchVehicleSelectOptions = useMemo/);
assert.equal((useDispatchSummaryViewModelSource.match(/buildVehicleDisplayName\(vehicle\)/g) ?? []).length, 1);
assert.doesNotMatch(dispatchSectionSource, /buildVehicleDisplayName/);
assert.doesNotMatch(dispatchSectionSource, /useMemo/);
assert.match(useReportColumnLayoutSource, /createEmptyReportColumnValueLists/);
assert.match(useReportColumnLayoutSource, /valuesByKey\[key\]\.push\(textRow\[key\]\)/);
assert.doesNotMatch(useReportColumnLayoutSource, /reportColumnTextRows/);
assert.doesNotMatch(useReportColumnLayoutSource, /reportColumnTextRows\.map\(\(row\) => row\[key\]\)/);
assert.match(reportTableBodySource, /const bodyGroups = useMemo/);
assert.match(reportTableBodySource, /rowKey=\{rowDescriptor\.rowKey\}/);
assert.doesNotMatch(reportTableBodySource, /const rowKey = reportRowDisplayKey\(row\);\s*const dayReasonText/);
assert.match(reportsSectionSource, /createReportBodyLayout\(filteredReportAreaGroups\)/);
assert.match(reportsSectionSource, /const reportPrintLayoutToken = useMemo\(\(\) => \(\{[\s\S]*filteredReportAreaGroups,[\s\S]*reportColumnKeys,[\s\S]*reportDate,[\s\S]*reportHeaderLabel,[\s\S]*reportReasons,[\s\S]*\}\)/);
assert.match(reportsSectionSource, /const \[preparedReportPrintState, setPreparedReportPrintState\] = useState/);
assert.match(reportsSectionSource, /flushSync\(\(\) => setPreparedReportPrintState\(\{/);
assert.doesNotMatch(reportsSectionSource, /setPreparedReportPrintState\(null\)/);
assert.doesNotMatch(reportsSectionSource, /const reportPrintLayout = useMemo\(\(\) => createReportPrintLayout/);
assert.match(appPrimaryContentSource, /if \(shouldShowPtoDatabaseGateOnly\) \{\s*return <PtoDatabaseGate message=\{ptoDatabaseMessage\} \/>;\s*\}/);
assert.match(appPrimaryContentSource, /const ptoTabNeedsDatabase = isPtoDateTableKey\(appState\.ptoTab\) \|\| appState\.ptoTab === "buckets";/);
assert.match(appPrimaryContentSource, /useAppSectionPreloader\(!databaseConfigured \|\| ptoDatabaseReady\);/);
assert.match(initialAppDatabaseBootstrapSource, /storageChanged: boolean/);
assert.match(initialAppDataLoadStepsSource, /if \(databaseBootstrap\.storageChanged\) \{\s*storedState = readInitialStoredAppState\(\{ includePto: false \}\);\s*initialReportState = applySharedState\(storedState\);\s*\}/);
assert.match(useAppSectionPreloaderSource, /export function useAppSectionPreloader\(enabled: boolean\)/);
assert.match(useAppSectionPreloaderSource, /if \(!enabled\) return undefined;/);
assert.match(useAppSectionPreloaderSource, /const coreSectionPreloaders = \[/);
assert.match(useAppSectionPreloaderSource, /runNextPreload\(\);/);
assert.doesNotMatch(useAppSectionPreloaderSource, /function preloadCoreSections/);
assert.match(useAppAdminDatabasePropsSource, /const ptoMemoryTotal = useMemo\(\(\) => \(/);
assert.match(useAppAdminDatabasePropsSource, /const clientSnapshotStatsByKey = useMemo\(\(\) => new Map\(/);
assert.match(useAppAdminDatabasePropsSource, /clientSnapshotStatsByKey\.get\(snapshot\.key\) \?\? clientSnapshotStats\(snapshot\)/);
assert.match(sharedButtonsSource, /const topButtonActiveStyle: CSSProperties = \{/);
assert.match(sharedButtonsSource, /const topButtonGroupInactiveStyle: CSSProperties = \{/);
assert.doesNotMatch(sharedButtonsSource, /const buttonStyle: CSSProperties = \{/);
assert.match(sharedNavigationSource, /style=\{active \? headerSubtabButtonActiveStyle : headerSubtabButtonStyle\}/);
assert.doesNotMatch(sharedNavigationSource, /style=\{\{[\s\S]*headerSubtabButtonStyle/);
assert.match(ptoPrimaryContentSource, /createEmptyPtoDateModel\(appState\.ptoPlanYear\)/);
assert.match(ptoPrimaryContentSource, /import\("@\/features\/app\/PtoDataPrimaryContent"\)/);
assert.doesNotMatch(ptoPrimaryContentSource, /useAppPtoDateModel/);
assert.doesNotMatch(ptoPrimaryContentSource, /usePtoDateEditingGlobalReset/);
assert.match(ptoDataPrimaryContentSource, /export function PtoDataPrimaryContent/);
assert.match(ptoDataPrimaryContentSource, /useAppPtoDateModel/);
assert.match(ptoDataPrimaryContentSource, /usePtoDateEditingGlobalReset/);
assert.match(ptoPrimaryContentSource, /if \(!isPtoDateTab && !isPtoBucketsSection\)/);
assert.doesNotMatch(ptoPrimaryContentSource, /allPtoDateRows/);
assert.match(navigationSelectionHandlersSource, /const selectTopTab = useCallback\(\(tab: TopTab\) => \{\s*startTransition\(\(\) => \{\s*setTopTab\(tab\);\s*\}\);/);
assert.doesNotMatch(ptoBucketsGridModelSource, /editableGridRangeKeys/);
assert.doesNotMatch(ptoBucketsGridModelSource, /editableGridKeyAtOffset/);
assert.match(ptoBucketsGridModelSource, /rowKeys\.indexOf\(activeCell\.rowKey\)/);
assert.match(usePtoBucketsGridEditingSource, /editingMode \? rows\.map\(\(row\) => row\.key\) : \[\]/);
assert.match(usePtoBucketsGridEditingSource, /editingMode \? columns\.map\(\(column\) => column\.key\) : \[\]/);
assert.doesNotMatch(ptoDateEditableTableBodySource, /formulaCellsByRowId\.get\(row\.id\)/);
assert.match(ptoDateEditableTableBodySource, /rowProps\.formulaRowEditing\(row\.id\)/);
assert.doesNotMatch(ptoDateEditableTableBodySource, /some\(\(cell\) =>/);
assert.match(ptoDateEditableTableRowSource, /formulaCellEditing=\{formulaCellEditing\}/);
assert.match(ptoDateEditableTableRowSource, /export const PtoDateEditableTableRow = memo\(function PtoDateEditableTableRow/);
assert.match(ptoBucketsTableRowSource, /export const PtoBucketsTableRow = memo\(function PtoBucketsTableRow/);
assert.match(ptoBucketsTableSource, /const rowActiveCell = activeCell\?\.rowKey === row\.key \? activeCell : null;/);
assert.match(ptoBucketsTableSource, /draft=\{rowActiveCell \? draft : ""\}/);
assert.match(ptoBucketsPrimaryContentSource, /useAppPtoBucketSupplementalTables/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoPlanRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoOperRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoSurveyRows:/);
assert.doesNotMatch(ptoBucketsPrimaryContentSource, /ptoPlanImportInputRef:/);
assert.doesNotMatch(useAppPtoSupplementalTablesSource, /usePtoBucketsViewModel/);
assert.doesNotMatch(useAppPtoSupplementalTablesSource, /usePtoBucketsEditor/);
assert.match(useAppPtoBucketSupplementalTablesSource, /usePtoBucketsViewModel/);
assert.match(useAppPtoBucketSupplementalTablesSource, /usePtoBucketsEditor/);
assert.match(ptoDateTableViewModelSource, /const emptyPtoRowById = new Map<string, PtoPlanRow>\(\);/);
assert.match(ptoDateTableViewModelSource, /const rowById = ptoDateEditing \? new Map\(rows\.map\(\(row\) => \[row\.id, row\] as const\)\) : emptyPtoRowById;/);
assert.match(usePtoDateViewModelSource, /ptoDateEditing: boolean;/);
assert.match(usePtoDateViewModelSource, /isPtoDateTab \? yearMonths\(ptoPlanYear\) : \[\]/);
assert.match(usePtoDateViewModelSource, /if \(!isPtoDateTab \|\| !ptoDateEditing\) \{/);
