import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));

const mysqlSchemaSource = readFileSync(resolve(testDir, "../lib/server/mysql/schema.ts"), "utf8");
const mysqlSchemaDefinitionsSource = readFileSync(resolve(testDir, "../lib/server/mysql/schema-definitions.ts"), "utf8");
const authSchemaSource = readFileSync(resolve(testDir, "../lib/server/auth/schema.ts"), "utf8");
const mysqlPtoCommandsSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-commands.ts"), "utf8");
const mysqlPtoVersionSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-version.ts"), "utf8");
const mysqlPtoLoadSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-load.ts"), "utf8");
const databaseRouterSource = readFileSync(resolve(testDir, "../lib/server/database/router.ts"), "utf8");
const databaseAuthorizationSource = readFileSync(resolve(testDir, "../lib/server/database/authorization.ts"), "utf8");

assert.match(mysqlSchemaSource, /const schemaVersionMetaKey = createSchemaVersionMetaKey\(\);/);
assert.match(mysqlSchemaSource, /createHash\("sha256"\)/);
assert.match(mysqlSchemaSource, /SELECT 1 AS schema_ready FROM pto_meta WHERE meta_key = \? LIMIT 1/);
assert.match(mysqlSchemaSource, /if \(await mysqlSchemaVersionExists\(\)\) return;[\s\S]*await getMysqlPool\(\)\.execute\(ptoMetaTableStatement\);/);
assert.doesNotMatch(mysqlSchemaSource, /SELECT meta_key FROM pto_meta WHERE meta_key = \? LIMIT 1/);
assert.match(mysqlSchemaSource, /for \(const statement of schemaStatements\) \{[\s\S]*await getMysqlPool\(\)\.execute\(statement\);[\s\S]*\}/);
assert.match(mysqlSchemaSource, /for \(const migration of schemaMigrations\) \{[\s\S]*await applyMysqlSchemaMigration\(migration\);[\s\S]*\}/);
assert.match(mysqlSchemaSource, /INSERT IGNORE INTO pto_meta \(meta_key\) VALUES \(\?\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE vehicles ADD INDEX vehicles_sort_index_idx \(sort_index\)/);
assert.doesNotMatch(mysqlSchemaDefinitionsSource, /CREATE TABLE IF NOT EXISTS auth_users/);
assert.match(authSchemaSource, /CREATE TABLE IF NOT EXISTS auth_users/);
assert.match(authSchemaSource, /UNIQUE KEY auth_users_login_idx \(login\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_rows ADD INDEX pto_rows_sort_idx \(table_type, sort_index\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_day_values ADD INDEX pto_day_values_date_idx \(work_date\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_day_values ADD INDEX pto_day_values_date_row_idx \(work_date, table_type, row_id\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_day_values ADD INDEX pto_day_values_table_date_row_idx \(table_type, work_date, row_id\)/);
assert.match(mysqlSchemaDefinitionsSource, /CREATE TABLE IF NOT EXISTS pto_row_years/);
assert.match(mysqlSchemaDefinitionsSource, /PRIMARY KEY \(year_value, table_type, row_id\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_row_years ADD INDEX pto_row_years_row_idx \(table_type, row_id, year_value\)/);
assert.match(mysqlSchemaSource, /rebuildPtoRowYearMembership\(createSchemaSetupExecutor\(\)\)/);
assert.match(mysqlSchemaDefinitionsSource, /ALTER TABLE pto_bucket_rows ADD INDEX pto_bucket_rows_sort_idx \(sort_index\)/);
assert.doesNotMatch(mysqlPtoCommandsSource, /loadPtoUpdatedAtFromMysql/);
assert.match(mysqlPtoCommandsSource, /return await touchPtoVersion\(execute\)/);
assert.match(mysqlPtoVersionSource, /SELECT updated_at FROM pto_meta WHERE meta_key = \? LIMIT 1/);
assert.match(mysqlPtoLoadSource, /FROM pto_rows AS rows_for_year/);
assert.match(mysqlPtoLoadSource, /const ptoRowSelectColumns = \[/);
assert.match(mysqlPtoLoadSource, /const ptoDayValueSelectColumns = \[/);
assert.match(mysqlPtoLoadSource, /SELECT \$\{ptoRowSelectColumns\} FROM pto_rows ORDER BY table_type ASC, sort_index ASC/);
assert.match(mysqlPtoLoadSource, /SELECT \$\{ptoDayValueSelectColumns\} FROM pto_day_values ORDER BY work_date ASC/);
assert.match(mysqlPtoLoadSource, /rows_for_year\.\$\{column\}/);
assert.doesNotMatch(mysqlPtoLoadSource, /SELECT rows_for_year\.\*/);
assert.doesNotMatch(mysqlPtoLoadSource, /SELECT \* FROM pto_rows/);
assert.match(mysqlPtoLoadSource, /FROM pto_row_years AS row_years/);
assert.match(mysqlPtoLoadSource, /FROM pto_day_values AS values_for_year/);
assert.match(mysqlPtoLoadSource, /AND row_years\.year_value = \?/);
assert.doesNotMatch(mysqlPtoLoadSource, /WITH values_for_year AS \(/);
assert.match(mysqlPtoLoadSource, /JSON_CONTAINS\(COALESCE\(rows_for_year\.years, JSON_ARRAY\(\)\), JSON_QUOTE\(\?\)\)/);
assert.doesNotMatch(mysqlPtoLoadSource, /LEFT JOIN values_for_year/);
assert.match(mysqlPtoLoadSource, /EXISTS \(\s*SELECT 1\s*FROM pto_day_values AS values_for_year/);
assert.doesNotMatch(mysqlPtoLoadSource, /loadPtoStateFromMysqlForYear[\s\S]*SELECT \* FROM pto_rows ORDER BY table_type ASC, sort_index ASC/);
assert.match(databaseRouterSource, /authorizeDatabaseRequest\(session\.user, \{ resource, action, payload \}\)/);
assert.match(databaseRouterSource, /createDatabaseForbiddenResponse\(request\)/);
assert.match(databaseAuthorizationSource, /settingsKeyTabMap/);
assert.match(databaseAuthorizationSource, /adminStorageKeys\.reportReasons[\s\S]*"reports"/);
assert.match(databaseAuthorizationSource, /adminStorageKeys\.topTabs[\s\S]*"admin"/);

console.log("Database router source checks passed");
