import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const docsDir = resolve(testDir, "../docs");

const dispatchArchitecturePath = resolve(docsDir, "DISPATCH_SERVICE_ARCHITECTURE.md");
const workspacesArchitecturePath = resolve(docsDir, "WORKSPACES_ARCHITECTURE.md");
const editingAndConflictsPath = resolve(docsDir, "EDITING_AND_CONFLICTS.md");
const performancePath = resolve(docsDir, "PERFORMANCE_2GB_RAM.md");

assert.equal(existsSync(dispatchArchitecturePath), true);
assert.equal(existsSync(workspacesArchitecturePath), true);
assert.equal(existsSync(editingAndConflictsPath), true);
assert.equal(existsSync(performancePath), true);

const dispatchArchitecture = readFileSync(dispatchArchitecturePath, "utf8");
const workspacesArchitecture = readFileSync(workspacesArchitecturePath, "utf8");
const editingAndConflicts = readFileSync(editingAndConflictsPath, "utf8");
const performance = readFileSync(performancePath, "utf8");
const accessMatrixSource = readFileSync(resolve(testDir, "../lib/domain/access-control/accessMatrix.ts"), "utf8");
const effectivePermissionsSource = readFileSync(resolve(testDir, "../lib/domain/access-control/effectivePermissions.ts"), "utf8");
const moduleAccessPoliciesSource = readFileSync(resolve(testDir, "../lib/domain/access-control/moduleAccessPolicies.ts"), "utf8");
const accessGrantCommandsSource = readFileSync(resolve(testDir, "../lib/domain/access-control/grantCommands.ts"), "utf8");
const patchEditingSource = readFileSync(resolve(testDir, "../lib/domain/editing/patchEditing.ts"), "utf8");
const patchSavePolicySource = readFileSync(resolve(testDir, "../lib/domain/editing/patchSavePolicy.ts"), "utf8");
const changeHistorySource = readFileSync(resolve(testDir, "../lib/domain/audit/changeHistory.ts"), "utf8");
const miningGpsReconciliationSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/gpsReconciliation.ts"), "utf8");
const miningNonCompletionReasonsSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/nonCompletionReasons.ts"), "utf8");
const miningOperationalAccountingSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/operationalAccounting.ts"), "utf8");
const miningPlanFactSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/planFact.ts"), "utf8");
const miningReportClosureSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/reportClosure.ts"), "utf8");
const miningReportReadinessSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/reportReadiness.ts"), "utf8");
const miningContractsSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/service-contracts.ts"), "utf8");
const miningShiftReportCommandsSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/shiftReportCommands.ts"), "utf8");
const miningShiftReportLineSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/shiftReportLineModel.ts"), "utf8");
const miningShiftReportQueriesSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/shiftReportQueries.ts"), "utf8");
const miningSubmissionControlSource = readFileSync(resolve(testDir, "../lib/domain/dispatch/submissionControl.ts"), "utf8");
const taxationContractsSource = readFileSync(resolve(testDir, "../lib/domain/taxation/service-contracts.ts"), "utf8");
const taxationAssignmentPetitionsSource = readFileSync(resolve(testDir, "../lib/domain/taxation/assignmentPetitions.ts"), "utf8");
const taxationFuelAccountingSource = readFileSync(resolve(testDir, "../lib/domain/taxation/fuelAccounting.ts"), "utf8");
const taxationSupervisorControlSource = readFileSync(resolve(testDir, "../lib/domain/taxation/supervisorControl.ts"), "utf8");
const taxationSubstitutionSource = readFileSync(resolve(testDir, "../lib/domain/taxation/substitution.ts"), "utf8");
const taxationWaybillIssuanceSource = readFileSync(resolve(testDir, "../lib/domain/taxation/waybillIssuance.ts"), "utf8");
const smtsContractsSource = readFileSync(resolve(testDir, "../lib/domain/smts/service-contracts.ts"), "utf8");
const smtsEquipmentLifecycleSource = readFileSync(resolve(testDir, "../lib/domain/smts/equipmentLifecycle.ts"), "utf8");
const fleetContractsSource = readFileSync(resolve(testDir, "../lib/domain/fleet/service-contracts.ts"), "utf8");
const fleetVehicleMovementsSource = readFileSync(resolve(testDir, "../lib/domain/fleet/vehicleMovements.ts"), "utf8");
const commonContractsSource = readFileSync(resolve(testDir, "../lib/domain/common-processes/service-contracts.ts"), "utf8");
const commonProcessCommandsSource = readFileSync(resolve(testDir, "../lib/domain/common-processes/processCommands.ts"), "utf8");
const reportAggregationSource = readFileSync(resolve(testDir, "../lib/domain/reports/aggregation-contracts.ts"), "utf8");
const preparedReportsSource = readFileSync(resolve(testDir, "../lib/domain/reports/preparedReports.ts"), "utf8");
assert.match(performance, /2 GB RAM/);
assert.match(performance, /indexContracts\.ts/);
assert.match(performance, /indexMigrationPlan\.ts/);
assert.ok(performance.includes("\u043e\u0442\u0434\u0435\u043b\u044c\u043d\u043e\u0435 Node.js \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435"));
assert.ok(performance.includes("\u043e\u0442\u0434\u0435\u043b\u044c\u043d\u044b\u0435 \u0431\u0430\u0437\u044b"));
assert.match(performance, /server-side pagination/);
assert.match(editingAndConflicts, /version-based editing/);
assert.match(editingAndConflicts, /version/);
assert.match(editingAndConflicts, /patch/i);
assert.match(workspacesArchitecture, /lazy loading/i);
assert.match(workspacesArchitecture, /indexMigrationPlan\.ts/);
assert.ok(workspacesArchitecture.includes("\u043e\u0434\u043d\u043e\u0433\u043e Next.js \u043f\u0440\u043e\u0435\u043a\u0442\u0430") || workspacesArchitecture.includes("\u043e\u0434\u0438\u043d Next.js \u043f\u0440\u043e\u0435\u043a\u0442"));
assert.match(dispatchArchitecture, /user_id/);
assert.match(dispatchArchitecture, /can_view/);
assert.match(dispatchArchitecture, /can_edit/);
assert.match(dispatchArchitecture, /can_approve/);
assert.match(dispatchArchitecture, /can_export/);
assert.match(dispatchArchitecture, /supervisorControl\.ts/);
assert.match(dispatchArchitecture, /substitution\.ts/);

assert.match(accessMatrixSource, /AccessMatrixGrant/);
assert.match(accessMatrixSource, /canApprove/);
assert.match(accessMatrixSource, /workspaceAccessMatrixPreview/);
assert.match(effectivePermissionsSource, /getEffectiveAccess/);
assert.match(effectivePermissionsSource, /grantMatchesSubject/);
assert.match(effectivePermissionsSource, /grantMatchesScope/);
assert.match(effectivePermissionsSource, /hasAccessCapability/);
assert.match(moduleAccessPoliciesSource, /workspaceModuleAccessPolicies/);
assert.match(moduleAccessPoliciesSource, /getWorkspaceModulesWithoutAccessPolicy/);
assert.match(moduleAccessPoliciesSource, /canUseWorkspaceModuleAction/);
assert.match(moduleAccessPoliciesSource, /prepared-reports/);
assert.match(moduleAccessPoliciesSource, /access-matrix/);
assert.match(accessGrantCommandsSource, /createAccessMatrixGrantCreateCommand/);
assert.match(accessGrantCommandsSource, /createAccessMatrixGrantPatchCommand/);
assert.match(accessGrantCommandsSource, /normalizeAccessGrantCapabilities/);
assert.match(accessGrantCommandsSource, /elevated_reason_required/);
assert.match(patchEditingSource, /VersionedEntityReference/);
assert.match(patchEditingSource, /PatchSaveCommand/);
assert.match(patchEditingSource, /PatchSaveConflict/);
assert.match(patchEditingSource, /ChangeHistoryEntry/);
assert.match(patchEditingSource, /createPatchFieldChanges/);
assert.match(patchEditingSource, /applyPatchFieldChanges/);
assert.match(patchSavePolicySource, /evaluateVersionedPatchSave/);
assert.match(patchSavePolicySource, /createPatchSaveConflict/);
assert.match(patchSavePolicySource, /createPatchChangeHistoryBatch/);
assert.match(patchSavePolicySource, /currentVersion/);
assert.match(changeHistorySource, /ChangeHistoryBatch/);
assert.match(changeHistorySource, /createChangeHistoryEntries/);
assert.match(changeHistorySource, /reasonKind/);

assert.match(miningGpsReconciliationSource, /buildMiningGpsLineReconciliationRows/);
assert.match(miningGpsReconciliationSource, /summarizeMiningGpsReconciliations/);
assert.match(miningGpsReconciliationSource, /missingGpsVehicleIds/);
assert.match(miningGpsReconciliationSource, /toleranceTrips/);
assert.match(miningNonCompletionReasonsSource, /createMiningNonCompletionReasonRequirements/);
assert.match(miningNonCompletionReasonsSource, /reason_required/);
assert.match(miningNonCompletionReasonsSource, /summarizeMiningNonCompletionReasons/);
assert.match(miningOperationalAccountingSource, /createMiningOperationalAccountingRows/);
assert.match(miningOperationalAccountingSource, /acceptedVolume/);
assert.match(miningOperationalAccountingSource, /surveyAdjustedVolume/);
assert.match(miningOperationalAccountingSource, /finalVolume/);
assert.match(miningOperationalAccountingSource, /operationalAccountingAcceptedReportStatuses/);
assert.match(miningPlanFactSource, /createMiningPlanFactRows/);
assert.match(miningPlanFactSource, /MiningPlanTargetLine/);
assert.match(miningPlanFactSource, /behind_plan/);
assert.match(miningPlanFactSource, /isMiningPlanVersionUsableForPlanFact/);
assert.match(miningReportReadinessSource, /createMiningDispatchReportReadiness/);
assert.match(miningReportReadinessSource, /missing_submission/);
assert.match(miningReportReadinessSource, /gps_mismatch/);
assert.match(miningReportReadinessSource, /missing_non_completion_reason/);
assert.match(miningReportClosureSource, /createMiningDispatchReportClosureCommands/);
assert.match(miningReportClosureSource, /readiness_blockers/);
assert.match(miningReportClosureSource, /approval_permission_required/);
assert.match(miningReportClosureSource, /no_reports_to_close/);
assert.match(miningContractsSource, /MiningShiftReportStatus/);
assert.match(miningContractsSource, /MiningProductionLink/);
assert.match(miningContractsSource, /MiningSurveyAdjustment/);
assert.match(miningContractsSource, /MiningGpsReconciliation/);
assert.match(miningShiftReportCommandsSource, /createMiningShiftReportActionCommand/);
assert.match(miningShiftReportCommandsSource, /approval_permission_required/);
assert.match(miningShiftReportCommandsSource, /mining_shift_report/);
assert.match(miningShiftReportLineSource, /calculateMiningShiftReportLineVolume/);
assert.match(miningShiftReportLineSource, /validateMiningShiftReportLineDraft/);
assert.match(miningShiftReportLineSource, /createMiningShiftReportLinePatchCommand/);
assert.match(miningShiftReportLineSource, /productionLink/);
assert.match(miningShiftReportQueriesSource, /MiningShiftReportListQuery/);
assert.match(miningShiftReportQueriesSource, /normalizeMiningShiftReportListQuery/);
assert.match(miningShiftReportQueriesSource, /date\+section_id\+shift/);
assert.match(miningShiftReportQueriesSource, /hasBoundedMiningShiftReportPeriod/);
assert.match(miningSubmissionControlSource, /buildMiningShiftReportSubmissionControlRows/);
assert.match(miningSubmissionControlSource, /summarizeMiningShiftReportSubmissions/);
assert.match(miningSubmissionControlSource, /isOverdue/);
assert.match(miningSubmissionControlSource, /missingCount/);

assert.match(taxationContractsSource, /WaybillIssueMode/);
assert.match(taxationContractsSource, /AssignmentPetitionStatus/);
assert.match(taxationContractsSource, /FuelAccountingPeriodStatus/);
assert.match(taxationContractsSource, /ContractorFuelDebt/);
assert.match(taxationAssignmentPetitionsSource, /createTemporaryAssignmentCommandFromPetition/);
assert.match(taxationAssignmentPetitionsSource, /doAssignmentPeriodsOverlap/);
assert.match(taxationAssignmentPetitionsSource, /overlap_conflict/);
assert.match(taxationAssignmentPetitionsSource, /driver_has_overlapping_assignment/);
assert.match(taxationFuelAccountingSource, /createFuelAccountingPeriodDraft/);
assert.match(taxationFuelAccountingSource, /buildFuelTruckBalanceRows/);
assert.match(taxationFuelAccountingSource, /summarizeFuelTruckBalanceRows/);
assert.match(taxationFuelAccountingSource, /contractorTransferLiters/);
assert.match(taxationFuelAccountingSource, /discrepancyLiters/);
assert.match(taxationSupervisorControlSource, /buildTaxationSupervisorControlRows/);
assert.match(taxationSupervisorControlSource, /missing_waybill_by_assignment/);
assert.match(taxationSupervisorControlSource, /suspicious_economy/);
assert.match(taxationSupervisorControlSource, /fuel_period_not_closed/);
assert.match(taxationSubstitutionSource, /createTaxerSubstitutionSessionCommand/);
assert.match(taxationSubstitutionSource, /resolveTaxationActorContext/);
assert.match(taxationSubstitutionSource, /substitutionSessionId/);
assert.match(taxationWaybillIssuanceSource, /createBatchWaybillIssuePlan/);
assert.match(taxationWaybillIssuanceSource, /createSingleWaybillIssueCommand/);
assert.match(taxationWaybillIssuanceSource, /already_created/);
assert.match(taxationWaybillIssuanceSource, /basis_required/);
assert.match(taxationWaybillIssuanceSource, /superseded_by_temporary_assignment/);
assert.match(smtsContractsSource, /SmtsVehicleCard/);
assert.match(smtsContractsSource, /SmtsTerminalStatus/);
assert.match(smtsContractsSource, /FuelDrainCheckStatus/);
assert.match(smtsContractsSource, /ContractorMonitoringAccess/);
assert.match(smtsEquipmentLifecycleSource, /createSmtsInstallLifecycleCommand/);
assert.match(smtsEquipmentLifecycleSource, /createSmtsRemovalLifecycleCommand/);
assert.match(smtsEquipmentLifecycleSource, /summarizeSmtsInventory/);
assert.match(smtsEquipmentLifecycleSource, /buildSmtsEquipmentTimeline/);
assert.match(smtsEquipmentLifecycleSource, /terminal_not_available/);
assert.match(fleetContractsSource, /VehicleMovementStatus/);
assert.match(fleetContractsSource, /ServiceVehicleCard/);
assert.match(fleetContractsSource, /ServiceVehicleInsurance/);
assert.match(fleetContractsSource, /VehicleSectionHistoryEntry = VersionedEntityReference/);
assert.match(fleetVehicleMovementsSource, /createVehicleMovementActionCommand/);
assert.match(fleetVehicleMovementsSource, /createVehicleMovementHistoryCommands/);
assert.match(fleetVehicleMovementsSource, /current_section_mismatch/);
assert.match(fleetVehicleMovementsSource, /vehicle_section_history/);
assert.match(commonContractsSource, /OvertimeRequest/);
assert.match(commonContractsSource, /BusinessTripTaskType/);
assert.match(commonContractsSource, /DispatchServiceEventLogEntry/);
assert.match(commonProcessCommandsSource, /createOvertimeStatusCommand/);
assert.match(commonProcessCommandsSource, /createBusinessTripStatusCommand/);
assert.match(commonProcessCommandsSource, /createBusinessTripReadiness/);
assert.match(commonProcessCommandsSource, /approval_permission_required/);
assert.match(commonProcessCommandsSource, /task_not_finished/);
assert.match(reportAggregationSource, /PreparedReportAggregate/);
assert.match(reportAggregationSource, /usesPreparedAggregates: true/);
assert.match(reportAggregationSource, /ReportExportRequest/);
assert.match(preparedReportsSource, /validatePreparedReportQuery/);
assert.match(preparedReportsSource, /selectPreparedReportAggregates/);
assert.match(preparedReportsSource, /createReportExportRequestCommand/);
assert.match(preparedReportsSource, /date_range_too_large/);
assert.match(preparedReportsSource, /report_export_request/);

console.log("Dispatch service architecture checks passed");
