import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const runbookPath = resolve(testDir, "..", "docs", "LIVE_HANDLER_ACTIVATION_RUNBOOK.md");
const workspacesDoc = readFileSync(resolve(testDir, "..", "docs", "WORKSPACES_ARCHITECTURE.md"), "utf8");

assert.equal(existsSync(runbookPath), true);

const runbook = readFileSync(runbookPath, "utf8");

assert.match(runbook, /Live Handler Activation Runbook/);
assert.match(runbook, /`planned-only` to `live`/);
assert.match(runbook, /one action at a time/);
assert.match(runbook, /Do not activate write, export, import, workflow, Excel\/PDF, AI background/);
assert.match(runbook, /Keep one Next\.js project/);
assert.match(runbook, /Keep one `\/api\/database` route/);
assert.match(runbook, /Do not start a separate backend process/);
assert.match(runbook, /Do not add a separate module database/);
assert.match(runbook, /Do not register more than one live handler key/);
assert.match(runbook, /`reviewModuleHandlerActivation`/);
assert.match(runbook, /`reviewWriteLiveHandlerRegistrationCandidate`/);
assert.match(runbook, /npm run plan:write-handler-activation -- --resource taxation --action create-waybill --factory-kind create/);
assert.match(runbook, /`getModuleLiveHandlerStatus`/);
assert.match(runbook, /`appliesChanges = false`/);
assert.match(runbook, /`databaseConnection = false`/);
assert.match(runbook, /`liveRegistryMutation = false`/);
assert.match(runbook, /`handlerRegistrationMutation = false`/);
assert.match(runbook, /`write_handler_not_registered`/);
assert.match(runbook, /`verificationCommands` containing `npm run verify`/);
assert.match(runbook, /`activationScopeSize` equal to `1`/);
assert.match(runbook, /ready-to-register/);
assert.match(runbook, /createGuardedLiveModuleListHandler/);
assert.match(runbook, /createGuardedLiveModuleDetailHandler/);
assert.match(runbook, /public_read_model_response_envelope/);
assert.match(runbook, /createPublicReadModelListResponse/);
assert.match(runbook, /createPublicReadModelDetailResponse/);
assert.match(runbook, /execution\.createSqlPlan\(\)/);
assert.match(runbook, /declared `selectColumns`/);
assert.match(runbook, /`id` \+ scope query with `LIMIT 1`/);
assert.match(runbook, /Do not use `SELECT \*`/);
assert.match(runbook, /read-model executor helpers/);
assert.match(runbook, /read-model-executor\.ts/);
assert.match(runbook, /executeLiveModuleListReadModel/);
assert.match(runbook, /executeLiveModuleDetailReadModel/);
assert.match(runbook, /executeLiveModuleListReadModelWithRowsClient/);
assert.match(runbook, /executeLiveModuleDetailReadModelWithRowsClient/);
assert.match(runbook, /DatabaseReadModelRowsRequest/);
assert.match(runbook, /should not\s+open ad hoc connections/);
assert.match(runbook, /mysqlReadModelRowsClient/);
assert.match(runbook, /read-model-rows\.ts/);
assert.match(runbook, /existing `dbRows` helper/);
assert.match(runbook, /rejects `SELECT \*`/);
assert.match(runbook, /Do not create a second pool/);
assert.match(runbook, /createMysqlLiveModuleListReadModelHandler/);
assert.match(runbook, /createMysqlLiveModuleDetailReadModelHandler/);
assert.match(runbook, /mysql-read-model-handlers\.ts/);
assert.match(runbook, /Use a custom guarded handler only/);
assert.match(runbook, /reviewMysqlReadModelSchemaReadiness/);
assert.match(runbook, /read-model-schema-readiness\.ts/);
assert.match(runbook, /information_schema\.COLUMNS/);
assert.match(runbook, /listModuleReadModelSchemaRequirements/);
assert.match(runbook, /Activation is blocked if a required/);
assert.match(runbook, /npm run check:read-model-schema -- --workspace taxation/);
assert.match(runbook, /reports `ready: true`/);
assert.match(runbook, /npm run review:live-handler -- --resource taxation --action list-waybills/);
assert.match(runbook, /module-specific MySQL schema preflight/);
assert.match(runbook, /combined report returns\s+`ready: true`/);
assert.match(runbook, /registration candidate summary/);
assert.match(runbook, /not as\s+an\s+automatic registry mutation/);
assert.match(runbook, /createLiveReadModelJsonResponse/);
assert.match(runbook, /return\s+`422`/);
assert.match(runbook, /runs exactly that bounded query/);
assert.match(runbook, /server query policy/);
assert.match(runbook, /never return more rows than requested/);
assert.match(runbook, /return at most one row/);
assert.match(runbook, /return `version`/);
assert.match(runbook, /avoid exposing table names or column names/);
assert.match(runbook, /moduleLiveHandlerRegistry\.ts/);
assert.match(runbook, /module-live-handlers\.ts/);
assert.match(runbook, /Smoke the activated action and one still-planned action/);
assert.match(runbook, /`501 planned_module_database_action`/);
assert.match(runbook, /Remove the live registry key/);
assert.match(runbook, /Remove the guarded server registration/);

assert.match(workspacesDoc, /`docs\/LIVE_HANDLER_ACTIVATION_RUNBOOK\.md`/);
assert.match(workspacesDoc, /guarded\s+handler factories/);

console.log("Live handler activation runbook checks passed");
