import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const appLocalPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppLocalPersistence.ts"), "utf8");
const sharedDatabaseSaveQueueSource = readFileSync(resolve(testDir, "../features/app/useSharedDatabaseSaveQueue.ts"), "utf8");
const appPtoPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppPtoPersistence.ts"), "utf8");
const initialAppStorageSource = readFileSync(resolve(testDir, "../features/app/initialAppStorage.ts"), "utf8");
const ptoUiStateDatabaseSyncSource = readFileSync(resolve(testDir, "../features/pto/usePtoUiStateDatabaseSync.ts"), "utf8");
const ptoDatabaseLoadSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseLoad.ts"), "utf8");
const ptoDatabaseLoadRunnerSource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadRunner.ts"), "utf8");
const ptoDatabaseLoadApplySource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadApply.ts"), "utf8");
const ptoPersistenceStorageSource = readFileSync(resolve(testDir, "../features/pto/ptoPersistenceStorage.ts"), "utf8");
const ptoLocalPersistenceSource = readFileSync(resolve(testDir, "../features/pto/usePtoLocalPersistence.ts"), "utf8");
const ptoDatabaseSaveSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseSave.ts"), "utf8");
const initialAppDataLoadStepsSource = readFileSync(resolve(testDir, "../features/app/initialAppDataLoadSteps.ts"), "utf8");
const ptoDateRowValueEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateRowValueEditor.ts"), "utf8");
const ptoDateTableContextSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateTableContext.ts"), "utf8");
const ptoLinkedRowsEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoLinkedRowsEditor.ts"), "utf8");
const ptoYearEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoYearEditor.ts"), "utf8");
const ptoInlineDatabaseWriteSource = readFileSync(resolve(testDir, "../features/pto/ptoInlineDatabaseWrite.ts"), "utf8");
const mysqlPtoCommandsSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-commands.ts"), "utf8");
const mysqlPtoFreshnessSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-freshness.ts"), "utf8");
const supabasePtoCommandsSource = readFileSync(resolve(testDir, "../lib/supabase/pto-commands.ts"), "utf8");
const supabasePtoFreshnessSource = readFileSync(resolve(testDir, "../lib/supabase/pto-freshness.ts"), "utf8");

assert.match(ptoUiStateDatabaseSyncSource, /export function usePtoUiStateDatabaseSync/);
assert.match(appPtoPersistenceSource, /import \{ usePtoUiStateDatabaseSync \} from "@\/features\/pto\/usePtoUiStateDatabaseSync";/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseLoad\(\{[\s\S]*adminDataLoaded: ptoDatabaseLoadEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseSave\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoUiStateDatabaseSync\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*ptoDatabaseLoadedRef,[\s\S]*requestPtoDatabaseSave,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoLocalPersistence\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*skipUntilDatabaseLoaded: databaseConfigured,[\s\S]*\}\);/);
assert.match(initialAppStorageSource, /export const initialPtoStorageKeys = \[/);
assert.match(initialAppStorageSource, /initialAppStorageKeys = Object\.values\(adminStorageKeys\)\.filter\(\(key\) => !initialPtoStorageKeySet\.has\(key\)\)/);
assert.match(ptoDatabaseLoadSource, /runPtoDatabaseLoadOnce\(\{[\s\S]*isCancelled: \(\) => cancelled,[\s\S]*\}\)/);
assert.doesNotMatch(ptoDatabaseLoadSource, /\n\s*options,\n\s*\]\);/);
assert.match(ptoDatabaseLoadRunnerSource, /const includeBuckets = ptoTab === "buckets";/);
assert.match(ptoDatabaseLoadRunnerSource, /localPtoNeedsDatabaseFreshnessCheck/);
assert.match(ptoDatabaseLoadRunnerSource, /loadPtoStateFromDatabase\(\{ year: ptoPlanYear,\s*includeBuckets \}\)/);
assert.match(ptoDatabaseLoadRunnerSource, /preserveFallbackBuckets: !includeBuckets/);
assert.match(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(ptoPlanYear\)/);
assert.doesNotMatch(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(loadedState\.uiState\.ptoPlanYear\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseUpdatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = resolution\.kind === "empty-save-local";/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseState\?\.updatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadApplySource, /export function createPtoDatabaseLoadBaselineWithBuckets/);
assert.match(initialAppStorageSource, /export function readInitialStoredPtoState\(\)/);
assert.match(initialAppDataLoadStepsSource, /readInitialStoredAppState\(\{ includePto: !databaseConfigured \}\)/);
assert.match(initialAppDataLoadStepsSource, /const localInitialPtoState = buildInitialPtoState\(databaseConfigured \? readInitialStoredPtoState\(\) : storedState\);/);
assert.match(initialAppDataLoadStepsSource, /if \(!databaseConfigured \|\| localInitialPtoState\.hasSavedPtoState\) \{[\s\S]*applyInitialPtoState\(localInitialPtoState/);
assert.match(ptoDatabaseSaveSource, /return await savePtoDatabaseChanges\("manual"\);/);
assert.match(ptoDatabaseSaveSource, /return false;/);
assert.match(ptoDatabaseSaveSource, /return true;/);
assert.match(ptoDatabaseSaveSource, /const ptoDatabaseDirtyRef = useRef\(false\);/);
assert.match(ptoDatabaseSaveSource, /if \(!ptoDatabaseDirtyRef\.current\) \{[\s\S]*return true;[\s\S]*\}/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSaveShouldSkip\(mode, snapshotToSave, ptoDatabaseSaveSnapshotRef\.current\)\) \{[\s\S]*ptoDatabaseDirtyRef\.current = false;[\s\S]*return true;[\s\S]*\}/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseSaveSnapshotRef\.current = savedSnapshot;\s*ptoDatabaseDirtyRef\.current = false;/);
assert.match(ptoDatabaseSaveSource, /if \(!databaseConfigured \|\| !ptoDatabaseLoadedRef\.current \|\| ptoDatabaseLoadedYearRef\.current !== currentYear\) return;\s*ptoDatabaseDirtyRef\.current = true;/);
assert.match(ptoDatabaseSaveSource, /getPtoDatabaseExpectedUpdatedAt = useCallback/);
assert.match(ptoDatabaseSaveSource, /const isPtoDatabaseDirty = useCallback\(\(\) => ptoDatabaseDirtyRef\.current, \[\]\);/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSavingRef\.current\) \{[\s\S]*try \{[\s\S]*await ptoDatabaseActiveSaveRef\.current;[\s\S]*\} catch \{[\s\S]*return false;[\s\S]*\}/);
assert.doesNotMatch(ptoDatabaseSaveSource, /refreshPtoDatabaseSaveBaseline/);
assert.match(ptoDatabaseSaveSource, /let suppressQueuedRetry = false;/);
assert.match(ptoDatabaseSaveSource, /if \(isDatabaseConflictError\(error\)\) \{[\s\S]*suppressQueuedRetry = true;[\s\S]*ptoDatabaseSaveQueuedRef\.current = false;[\s\S]*setPtoDatabaseMessage\(ptoDatabaseMessages\.conflict\);/);
assert.match(ptoDatabaseSaveSource, /if \(!suppressQueuedRetry && ptoDatabaseSaveQueuedRef\.current\) \{/);
assert.match(ptoDatabaseSaveSource, /const saveAllYears = ptoDatabaseFullSaveNextRef\.current;/);
assert.match(ptoDatabaseSaveSource, /const stateToSave = ptoDatabaseStateRef\.current;/);
assert.match(ptoDatabaseSaveSource, /const stateAtWrite = ptoDatabaseStateRef\.current;/);
assert.match(ptoDatabaseSaveSource, /stateAtWrite === stateToSave[\s\S]*\? snapshotToSave[\s\S]*: serializePtoDatabaseState\(stateAtWrite\)/);
assert.match(ptoDatabaseSaveSource, /yearScope: saveAllYears \? undefined : stateAtWrite\.uiState\.ptoPlanYear/);
assert.match(ptoPersistenceStorageSource, /scopePtoStateForYear/);
assert.match(ptoPersistenceStorageSource, /const stateToSave = options\.yearScope \? scopePtoStateForYear\(state, options\.yearScope\) : state;/);
assert.match(ptoPersistenceStorageSource, /savePtoStateToDatabase\(stateToSave, \{ expectedUpdatedAt, yearScope: options\.yearScope \}\)/);
assert.match(ptoPersistenceStorageSource, /type PtoBrowserStorageSnapshotCache = \{[\s\S]*snapshot: PtoBrowserStorageSnapshot;[\s\S]*refs: Record<string, unknown>;[\s\S]*\};/);
assert.match(ptoPersistenceStorageSource, /export type PtoBrowserStorageSaveOptions = \{[\s\S]*markLocalUpdatedAt: boolean;[\s\S]*localUpdatedAt\?: string \| null;[\s\S]*\};/);
assert.match(ptoPersistenceStorageSource, /if \(cache && cache\.refs\[storageKey\] === ref && typeof cache\.snapshot\[storageKey\] === "string"\)/);
assert.match(ptoPersistenceStorageSource, /const updatedAt = options\.localUpdatedAt === undefined \? new Date\(\)\.toISOString\(\) : options\.localUpdatedAt;/);
assert.match(ptoPersistenceStorageSource, /if \(options\.markLocalUpdatedAt && updatedAt\) \{[\s\S]*window\.localStorage\.setItem\(adminStorageKeys\.ptoLocalUpdatedAt, updatedAt\);/);
assert.match(ptoPersistenceStorageSource, /window\.localStorage\.setItem\(adminStorageKeys\.appLocalUpdatedAt, updatedAt \?\? new Date\(\)\.toISOString\(\)\);/);
assert.match(ptoLocalPersistenceSource, /useRef<PtoBrowserStorageSnapshotCache \| null>\(null\)/);
assert.match(ptoLocalPersistenceSource, /const localUpdatedAt = markLocalUpdatedAt && !isPtoDatabaseDirty\(\)[\s\S]*\? getPtoDatabaseExpectedUpdatedAt\(\)[\s\S]*: undefined;/);
assert.match(ptoLocalPersistenceSource, /savePtoStateToBrowserStorage\([\s\S]*markLocalUpdatedAt,[\s\S]*localUpdatedAt,/);
assert.match(ptoLocalPersistenceSource, /ptoLocalSaveSnapshotRef\.current = result\.cache;/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseFullSaveNextRef\.current = false;/);
assert.match(ptoDateTableContextSource, /kind: "day-values"/);
assert.match(ptoInlineDatabaseWriteSource, /export function enqueuePtoInlineDatabaseWrite/);
assert.match(ptoInlineDatabaseWriteSource, /isDatabaseConflictError/);
assert.match(ptoInlineDatabaseWriteSource, /showSaveStatus\("error", inlineWriteErrorMessage\(label, error\)\)/);
assert.match(ptoInlineDatabaseWriteSource, /const result = await write\(\);[\s\S]*onSaved\(result\);[\s\S]*return result;/);
assert.doesNotMatch(ptoInlineDatabaseWriteSource, /\.then\(onSaved\)/);
assert.match(ptoDateTableContextSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "ячейка дня"[\s\S]*showSaveStatus[\s\S]*savePtoDayValueWithRowToDatabase/);
assert.match(ptoDateTableContextSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "значения месяца"[\s\S]*showSaveStatus[\s\S]*savePtoDayValuesWithRowToDatabase/);
assert.match(ptoLinkedRowsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "удаление строки"[\s\S]*deletePtoRowsFromDatabase/);
assert.match(ptoYearEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "удаление года"[\s\S]*deletePtoYearFromDatabase/);
assert.match(ptoDatabaseSaveSource, /markPtoDatabaseInlineWriteSaved/);
assert.match(ptoDatabaseSaveSource, /if \(!ptoDatabaseStateChanged\(ptoDatabaseStateRef\.current, ptoDatabaseSaveSnapshotRef\.current\)\) \{[\s\S]*ptoDatabaseDirtyRef\.current = false;[\s\S]*\}/);

assert.match(sharedDatabaseSaveQueueSource, /type SharedDatabaseSaveQueue = \{[\s\S]*storage: Record<string, string>;[\s\S]*settings: Record<string, unknown>;[\s\S]*\};/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSaveQueueRef = useRef<SharedDatabaseSaveQueue \| null>\(null\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSavingRef = useRef\(false\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseRetryTimerRef = useRef<ReturnType<typeof setTimeout> \| null>\(null\);/);
assert.match(sharedDatabaseSaveQueueSource, /clearTimeout\(sharedDatabaseRetryTimerRef\.current\);/);
assert.match(sharedDatabaseSaveQueueSource, /useEffect\(\(\) => clearSharedDatabaseRetryTimer, \[clearSharedDatabaseRetryTimer\]\);/);
assert.match(sharedDatabaseSaveQueueSource, /createAppStateStorageSnapshot/);
assert.match(sharedDatabaseSaveQueueSource, /const runSharedDatabaseSaveQueue = useCallback\(async \(\) => \{[\s\S]*while \(sharedDatabaseSaveQueueRef\.current\)[\s\S]*await saveSharedAppSettingsToDatabase\(queuedSave\.settings\);[\s\S]*if \(!appSettingsDatabaseLoadedRef\.current\) \{[\s\S]*await saveSharedAppStateToDatabase\(queuedSave\.storage\);[\s\S]*\}/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /conflictRetries/);
assert.match(sharedDatabaseSaveQueueSource, /let failed = false;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!isDatabaseConflictError\(error\)\) \{[\s\S]*sharedDatabaseSaveQueueRef\.current = sharedDatabaseSaveQueueRef\.current \?\? queuedSave;[\s\S]*failed = true;[\s\S]*throw error;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!failed\) \{[\s\S]*sharedDatabaseRetryDelayRef\.current = sharedDatabaseRetryInitialDelayMs;[\s\S]*if \(sharedDatabaseSaveQueueRef\.current\) \{[\s\S]*void runSharedDatabaseSaveQueue\(\);/);
assert.match(sharedDatabaseSaveQueueSource, /if \(sharedDatabaseSaveQueueRef\.current && !sharedDatabaseRetryTimerRef\.current\) \{[\s\S]*setTimeout\(\(\) => \{[\s\S]*void runSharedDatabaseSaveQueue\(\);[\s\S]*\}, retryDelay\);/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /refreshSharedDatabaseSaveBaselines/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /loadAppSettingsFromDatabase/);
assert.match(sharedDatabaseSaveQueueSource, /const savedSettings = await saveAppSettingsToDatabase\(delta\.settings/);
assert.match(sharedDatabaseSaveQueueSource, /if \(storageSnapshot === checkpoint\.storageSnapshot\) return;/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /const storageSnapshot = JSON\.stringify\(storage\)/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /JSON\.stringify\(checkpoint\.storage\)/);
assert.match(sharedDatabaseSaveQueueSource, /sharedDatabaseSaveQueueRef\.current = null;[\s\S]*failed = true;[\s\S]*showSaveStatus\([\s\S]*break;/);
assert.match(sharedDatabaseSaveQueueSource, /Данные на сервере изменились другим пользователем\. Локальная правка сохранена в браузере; обнови страницу перед повторным сохранением\./);
assert.match(sharedDatabaseSaveQueueSource, /Сохранение в базу не прошло\. Повторю автоматически через/);
assert.match(sharedDatabaseSaveQueueSource, /return useCallback\(\(savedLocalState: SharedAppStorageWriteResult\) => \{[\s\S]*sharedDatabaseSaveQueueRef\.current = \{[\s\S]*storage: savedLocalState\.storage,[\s\S]*settings: savedLocalState\.settings,[\s\S]*void runSharedDatabaseSaveQueue\(\);/);
assert.match(appLocalPersistenceSource, /import \{ useSharedDatabaseSaveQueue \} from "@\/features\/app\/useSharedDatabaseSaveQueue";/);
assert.match(appLocalPersistenceSource, /if \(savedLocalState\.changedKeys\.length > 0\) \{[\s\S]*enqueueSharedDatabaseSave\(savedLocalState\);[\s\S]*requestClientSnapshotSave\("app-state-save"\);/);
assert.match(appLocalPersistenceSource, /window\.addEventListener\("pagehide", flushAppLocalState\)/);
assert.match(appLocalPersistenceSource, /const savedLocalState = saveAppLocalState\(\);[\s\S]*if \(savedLocalState\.changedKeys\.length > 0\) \{[\s\S]*enqueueSharedDatabaseSave\(savedLocalState\);[\s\S]*requestClientSnapshotSave\("app-state-pagehide"\);/);

assert.match(ptoDateRowValueEditorSource, /if \(rowToSave\) saveDayPatch\(rowToSave, day, parsedValue\);\s*requestSave\(\);/);
assert.match(ptoDateRowValueEditorSource, /if \(rowToSave\) saveDayPatches\(rowToSave, patches\);\s*requestSave\(\);/);
assert.match(ptoDateTableContextSource, /savePtoDayValueWithRowToDatabase\(table, row, day, value, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(ptoDateTableContextSource, /savePtoDayValuesWithRowToDatabase\(table, row, values, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(ptoLinkedRowsEditorSource, /markPtoDatabaseInlineWriteSaved\(result\?\.updatedAt \?\? null,\s*\{[\s\S]*kind: "date-row"[\s\S]*action: "delete"[\s\S]*rowIds: \[row\.id\]/);
assert.match(ptoYearEditorSource, /markPtoDatabaseInlineWriteSaved\(result\?\.updatedAt \?\? null,\s*\{[\s\S]*kind: "year"[\s\S]*action: "delete"[\s\S]*year,/);
assert.match(supabasePtoCommandsSource, /expectedUpdatedAt: options\.expectedUpdatedAt/);
assert.match(supabasePtoCommandsSource, /assertSupabasePtoInlineMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, client\)/);
assert.match(supabasePtoCommandsSource, /supabasePtoInlineWriteResult\(client\)/);
assert.match(supabasePtoFreshnessSource, /export async function assertSupabasePtoInlineMatchesExpectedUpdatedAt/);
assert.match(supabasePtoFreshnessSource, /export async function loadSupabasePtoCurrentUpdatedAt/);
assert.match(mysqlPtoCommandsSource, /type PtoInlineWriteOptions = Pick<PtoSnapshotWriteOptions, "expectedUpdatedAt">;/);
assert.match(mysqlPtoCommandsSource, /const inlineDeleteBatchSize = 250;/);
assert.match(mysqlPtoCommandsSource, /DELETE FROM pto_day_values[\s\S]*AND \(row_id, work_date\) IN/);
assert.match(mysqlPtoCommandsSource, /DELETE FROM pto_bucket_values[\s\S]*WHERE \(row_key, equipment_key\) IN/);
assert.match(mysqlPtoFreshnessSource, /function mysqlUpdatedAfterExpectedClause/);
assert.match(mysqlPtoFreshnessSource, /return ` \$\{prefix\} updated_at > \?`;/);
assert.match(mysqlPtoFreshnessSource, /const freshCurrentRecords = currentRecords\.filter/);
assert.match(mysqlPtoFreshnessSource, /if \(freshCurrentRecords\.length === 0\) return;/);
assert.match(mysqlPtoFreshnessSource, /for \(const record of freshCurrentRecords\)/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValueWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValuesWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /deletePtoRowsFromMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
assert.match(mysqlPtoCommandsSource, /savePtoBucketValueToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
