import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const appLocalPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppLocalPersistence.ts"), "utf8");
const sharedDatabaseSaveQueueSource = readFileSync(resolve(testDir, "../features/app/useSharedDatabaseSaveQueue.ts"), "utf8");
const appPtoPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppPtoPersistence.ts"), "utf8");
const initialAppStorageSource = readFileSync(resolve(testDir, "../features/app/initialAppStorage.ts"), "utf8");
const ptoUiStateDatabaseSyncSource = readFileSync(resolve(testDir, "../features/pto/usePtoUiStateDatabaseSync.ts"), "utf8");
const ptoDatabaseLoadSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseLoad.ts"), "utf8");
const ptoDatabaseLoadRunnerSource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadRunner.ts"), "utf8");
const ptoDatabaseLoadApplySource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadApply.ts"), "utf8");
const ptoDatabaseSaveSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseSave.ts"), "utf8");
const initialAppDataLoadStepsSource = readFileSync(resolve(testDir, "../features/app/initialAppDataLoadSteps.ts"), "utf8");
const ptoDateRowValueEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateRowValueEditor.ts"), "utf8");
const ptoDateTableContextSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateTableContext.ts"), "utf8");
const mysqlPtoCommandsSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-commands.ts"), "utf8");
const supabasePtoCommandsSource = readFileSync(resolve(testDir, "../lib/supabase/pto-commands.ts"), "utf8");
const supabasePtoFreshnessSource = readFileSync(resolve(testDir, "../lib/supabase/pto-freshness.ts"), "utf8");

assert.match(ptoUiStateDatabaseSyncSource, /export function usePtoUiStateDatabaseSync/);
assert.match(appPtoPersistenceSource, /import \{ usePtoUiStateDatabaseSync \} from "@\/features\/pto\/usePtoUiStateDatabaseSync";/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseLoad\(\{[\s\S]*adminDataLoaded: ptoDatabaseLoadEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseSave\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoUiStateDatabaseSync\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*ptoDatabaseLoadedRef,[\s\S]*requestPtoDatabaseSave,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoLocalPersistence\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*skipUntilDatabaseLoaded: databaseConfigured,[\s\S]*\}\);/);
assert.match(initialAppStorageSource, /export const initialPtoStorageKeys = \[/);
assert.match(initialAppStorageSource, /initialAppStorageKeys = Object\.values\(adminStorageKeys\)\.filter\(\(key\) => !initialPtoStorageKeySet\.has\(key\)\)/);
assert.match(ptoDatabaseLoadSource, /runPtoDatabaseLoadOnce\(\{[\s\S]*isCancelled: \(\) => cancelled,[\s\S]*\}\)/);
assert.doesNotMatch(ptoDatabaseLoadSource, /\n\s*options,\n\s*\]\);/);
assert.match(ptoDatabaseLoadRunnerSource, /const includeBuckets = ptoTab === "buckets";/);
assert.match(ptoDatabaseLoadRunnerSource, /localPtoNeedsDatabaseFreshnessCheck/);
assert.match(ptoDatabaseLoadRunnerSource, /loadPtoStateFromDatabase\(\{ year: ptoPlanYear,\s*includeBuckets \}\)/);
assert.match(ptoDatabaseLoadRunnerSource, /preserveFallbackBuckets: !includeBuckets/);
assert.match(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(ptoPlanYear\)/);
assert.doesNotMatch(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(loadedState\.uiState\.ptoPlanYear\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseUpdatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = resolution\.kind === "empty-save-local";/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseState\?\.updatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadApplySource, /export function createPtoDatabaseLoadBaselineWithBuckets/);
assert.match(initialAppStorageSource, /export function readInitialStoredPtoState\(\)/);
assert.match(initialAppDataLoadStepsSource, /readInitialStoredAppState\(\{ includePto: !databaseConfigured \}\)/);
assert.match(initialAppDataLoadStepsSource, /const localInitialPtoState = buildInitialPtoState\(databaseConfigured \? readInitialStoredPtoState\(\) : storedState\);/);
assert.match(initialAppDataLoadStepsSource, /if \(!databaseConfigured \|\| localInitialPtoState\.hasSavedPtoState\) \{[\s\S]*applyInitialPtoState\(localInitialPtoState/);
assert.match(ptoDatabaseSaveSource, /return await savePtoDatabaseChanges\("manual"\);/);
assert.match(ptoDatabaseSaveSource, /return false;/);
assert.match(ptoDatabaseSaveSource, /return true;/);
assert.match(ptoDatabaseSaveSource, /getPtoDatabaseExpectedUpdatedAt = useCallback/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSavingRef\.current\) \{[\s\S]*try \{[\s\S]*await ptoDatabaseActiveSaveRef\.current;[\s\S]*\} catch \{[\s\S]*return false;[\s\S]*\}/);
assert.doesNotMatch(ptoDatabaseSaveSource, /refreshPtoDatabaseSaveBaseline/);
assert.match(ptoDatabaseSaveSource, /let suppressQueuedRetry = false;/);
assert.match(ptoDatabaseSaveSource, /if \(isDatabaseConflictError\(error\)\) \{[\s\S]*suppressQueuedRetry = true;[\s\S]*ptoDatabaseSaveQueuedRef\.current = false;[\s\S]*setPtoDatabaseMessage\(ptoDatabaseMessages\.conflict\);/);
assert.match(ptoDatabaseSaveSource, /if \(!suppressQueuedRetry && ptoDatabaseSaveQueuedRef\.current\) \{/);
assert.match(ptoDatabaseSaveSource, /const saveAllYears = ptoDatabaseFullSaveNextRef\.current;/);
assert.match(ptoDatabaseSaveSource, /yearScope: saveAllYears \? undefined : ptoDatabaseStateRef\.current\.uiState\.ptoPlanYear/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseFullSaveNextRef\.current = false;/);

assert.match(sharedDatabaseSaveQueueSource, /type SharedDatabaseSaveQueue = \{[\s\S]*storage: Record<string, string>;[\s\S]*settings: Record<string, unknown>;[\s\S]*\};/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSaveQueueRef = useRef<SharedDatabaseSaveQueue \| null>\(null\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSavingRef = useRef\(false\);/);
assert.match(sharedDatabaseSaveQueueSource, /const runSharedDatabaseSaveQueue = useCallback\(async \(\) => \{[\s\S]*while \(sharedDatabaseSaveQueueRef\.current\)[\s\S]*await saveSharedAppSettingsToDatabase\(queuedSave\.settings\);[\s\S]*await saveSharedAppStateToDatabase\(queuedSave\.storage\);/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /conflictRetries/);
assert.match(sharedDatabaseSaveQueueSource, /let failed = false;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!isDatabaseConflictError\(error\)\) \{[\s\S]*sharedDatabaseSaveQueueRef\.current = sharedDatabaseSaveQueueRef\.current \?\? queuedSave;[\s\S]*failed = true;[\s\S]*throw error;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!failed && sharedDatabaseSaveQueueRef\.current\) \{/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /refreshSharedDatabaseSaveBaselines/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /loadAppSettingsFromDatabase/);
assert.match(sharedDatabaseSaveQueueSource, /const savedSettings = await saveAppSettingsToDatabase\(delta\.settings/);
assert.match(sharedDatabaseSaveQueueSource, /sharedDatabaseSaveQueueRef\.current = null;[\s\S]*failed = true;[\s\S]*showSaveStatus\([\s\S]*break;/);
assert.match(sharedDatabaseSaveQueueSource, /Данные на сервере изменились другим пользователем\. Локальная правка сохранена в браузере; обнови страницу перед повторным сохранением\./);
assert.match(sharedDatabaseSaveQueueSource, /return useCallback\(\(savedLocalState: SharedAppStorageWriteResult\) => \{[\s\S]*sharedDatabaseSaveQueueRef\.current = \{[\s\S]*storage: savedLocalState\.storage,[\s\S]*settings: savedLocalState\.settings,[\s\S]*void runSharedDatabaseSaveQueue\(\);/);
assert.match(appLocalPersistenceSource, /import \{ useSharedDatabaseSaveQueue \} from "@\/features\/app\/useSharedDatabaseSaveQueue";/);
assert.match(appLocalPersistenceSource, /if \(savedLocalState\.changedKeys\.length > 0\) \{[\s\S]*enqueueSharedDatabaseSave\(savedLocalState\);[\s\S]*requestClientSnapshotSave\("app-state-save"\);/);

assert.match(ptoDateRowValueEditorSource, /if \(rowToSave\) saveDayPatch\(rowToSave, day, parsedValue\);\s*requestSave\(\);/);
assert.match(ptoDateRowValueEditorSource, /if \(rowToSave\) saveDayPatches\(rowToSave, patches\);\s*requestSave\(\);/);
assert.match(ptoDateTableContextSource, /savePtoDayValueWithRowToDatabase\(table, row, day, value, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(ptoDateTableContextSource, /savePtoDayValuesWithRowToDatabase\(table, row, values, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(supabasePtoCommandsSource, /expectedUpdatedAt: options\.expectedUpdatedAt/);
assert.match(supabasePtoCommandsSource, /assertSupabasePtoInlineMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, client\)/);
assert.match(supabasePtoCommandsSource, /supabasePtoInlineWriteResult\(client\)/);
assert.match(supabasePtoFreshnessSource, /export async function assertSupabasePtoInlineMatchesExpectedUpdatedAt/);
assert.match(supabasePtoFreshnessSource, /export async function loadSupabasePtoCurrentUpdatedAt/);
assert.match(mysqlPtoCommandsSource, /type PtoInlineWriteOptions = Pick<PtoSnapshotWriteOptions, "expectedUpdatedAt">;/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValueWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValuesWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /deletePtoRowsFromMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
assert.match(mysqlPtoCommandsSource, /savePtoBucketValueToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
