import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const appLocalPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppLocalPersistence.ts"), "utf8");
const sharedDatabaseSaveQueueSource = readFileSync(resolve(testDir, "../features/app/useSharedDatabaseSaveQueue.ts"), "utf8");
const appPtoPersistenceSource = readFileSync(resolve(testDir, "../features/app/useAppPtoPersistence.ts"), "utf8");
const appPtoPersistenceControllerSource = readFileSync(resolve(testDir, "../features/app/useAppPtoPersistenceController.ts"), "utf8");
const initialAppStorageSource = readFileSync(resolve(testDir, "../features/app/initialAppStorage.ts"), "utf8");
const ptoUiStateDatabaseSyncSource = readFileSync(resolve(testDir, "../features/pto/usePtoUiStateDatabaseSync.ts"), "utf8");
const ptoDatabaseLoadSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseLoad.ts"), "utf8");
const ptoDatabaseLoadRunnerSource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadRunner.ts"), "utf8");
const ptoDatabaseLocalHydrationSource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLocalHydration.ts"), "utf8");
const ptoDatabaseLoadMetricsSource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadMetrics.ts"), "utf8");
const ptoDatabaseLoadApplySource = readFileSync(resolve(testDir, "../features/pto/ptoDatabaseLoadApply.ts"), "utf8");
const ptoPersistenceComparisonSource = readFileSync(resolve(testDir, "../features/pto/ptoPersistenceComparison.ts"), "utf8");
const ptoPersistenceStorageSource = readFileSync(resolve(testDir, "../features/pto/ptoPersistenceStorage.ts"), "utf8");
const ptoLocalPersistenceSource = readFileSync(resolve(testDir, "../features/pto/usePtoLocalPersistence.ts"), "utf8");
const ptoDatabaseSaveSource = readFileSync(resolve(testDir, "../features/pto/usePtoDatabaseSave.ts"), "utf8");
const initialAppDataLoadStepsSource = readFileSync(resolve(testDir, "../features/app/initialAppDataLoadSteps.ts"), "utf8");
const ptoDateRowValueEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateRowValueEditor.ts"), "utf8");
const ptoDateTableContextSource = readFileSync(resolve(testDir, "../features/pto/usePtoDateTableContext.ts"), "utf8");
const ptoLinkedRowsEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoLinkedRowsEditor.ts"), "utf8");
const ptoYearEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoYearEditor.ts"), "utf8");
const ptoBucketsEditorSource = readFileSync(resolve(testDir, "../features/pto/usePtoBucketsEditor.ts"), "utf8");
const ptoInlineDatabaseWriteSource = readFileSync(resolve(testDir, "../features/pto/ptoInlineDatabaseWrite.ts"), "utf8");
const dataPtoSource = readFileSync(resolve(testDir, "../lib/data/pto.ts"), "utf8");
const mysqlPtoCommandsSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-commands.ts"), "utf8");
const mysqlPtoFreshnessSource = readFileSync(resolve(testDir, "../lib/server/mysql/pto-freshness.ts"), "utf8");
const supabasePtoCommandsSource = readFileSync(resolve(testDir, "../lib/supabase/pto-commands.ts"), "utf8");
const supabasePtoFreshnessSource = readFileSync(resolve(testDir, "../lib/supabase/pto-freshness.ts"), "utf8");

assert.match(ptoUiStateDatabaseSyncSource, /export function usePtoUiStateDatabaseSync/);
assert.match(ptoUiStateDatabaseSyncSource, /const databaseLoadedForUiStateRef = useRef\(false\);/);
assert.match(ptoUiStateDatabaseSyncSource, /databaseLoadedForUiStateRef\.current = false;/);
assert.match(ptoUiStateDatabaseSyncSource, /if \(!databaseLoadedForUiStateRef\.current\) \{[\s\S]*databaseLoadedForUiStateRef\.current = true;[\s\S]*previousUiStateSignatureRef\.current = uiStateSignature;[\s\S]*return;[\s\S]*\}/);
assert.match(appPtoPersistenceSource, /import \{ usePtoUiStateDatabaseSync \} from "@\/features\/pto\/usePtoUiStateDatabaseSync";/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseLoad\(\{[\s\S]*adminDataLoaded: ptoDatabaseLoadEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoDatabaseSave\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoUiStateDatabaseSync\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*ptoDatabaseLoadedRef,[\s\S]*requestPtoDatabaseSave,[\s\S]*\}\);/);
assert.match(appPtoPersistenceSource, /usePtoLocalPersistence\(\{[\s\S]*adminDataLoaded: ptoPersistenceEnabled,[\s\S]*skipUntilDatabaseLoaded: databaseConfigured,[\s\S]*\}\);/);
assert.match(appPtoPersistenceControllerSource, /const reportsNeedPtoDatabase = appState\.topTab === "reports"\s*\|\|\s*\(appState\.topTab === "admin" && appState\.adminSection === "reports"\);/);
assert.match(appPtoPersistenceControllerSource, /const activePtoTabNeedsDatabase = appState\.topTab === "pto"\s*&& \(isPtoDateTableKey\(appState\.ptoTab\) \|\| appState\.ptoTab === "buckets"\);/);
assert.match(appPtoPersistenceControllerSource, /const ptoDatabaseLoadEnabled = appState\.ptoDatabaseLoadStarted\s*\|\|\s*\([\s\S]*appState\.ptoBootstrapLoaded[\s\S]*&& \(!databaseConfigured \|\| reportsNeedPtoDatabase \|\| activePtoTabNeedsDatabase\)[\s\S]*\);/);
assert.match(initialAppStorageSource, /export const initialPtoStorageKeys = \[/);
assert.match(initialAppStorageSource, /initialAppStorageKeys = Object\.values\(adminStorageKeys\)\.filter\(\(key\) => !initialPtoStorageKeySet\.has\(key\)\)/);
assert.match(initialAppStorageSource, /const initialMeaningfulAppStorageKeys = initialAppStorageKeys\.filter/);
assert.match(initialAppStorageSource, /key !== adminStorageKeys\.appStateLocalUpdatedAt/);
assert.match(initialAppStorageSource, /key !== adminStorageKeys\.appSettingsLocalUpdatedAt/);
assert.match(initialAppStorageSource, /key !== adminStorageKeys\.vehiclesLocalUpdatedAt/);
assert.match(initialAppStorageSource, /key !== adminStorageKeys\.vehiclesSeedVersion/);
assert.match(initialAppStorageSource, /initialMeaningfulAppStorageKeys\.some\(\(key\) => window\.localStorage\.getItem\(key\) !== null\)/);
assert.match(initialAppStorageSource, /export function collectInitialStoredAppStorage/);
assert.match(initialAppStorageSource, /export function parseInitialStoredAppStateFromStorage/);
assert.match(ptoDatabaseLoadSource, /runPtoDatabaseLoadOnce\(\{[\s\S]*isCancelled: \(\) => cancelled,[\s\S]*\}\)/);
assert.doesNotMatch(ptoDatabaseLoadSource, /\n\s*options,\n\s*\]\);/);
assert.match(ptoDatabaseLoadRunnerSource, /const includeBuckets = ptoTab === "buckets";/);
assert.match(ptoDatabaseLoadRunnerSource, /createPtoDatabaseLoadMetrics\(\{ includeBuckets, year: ptoPlanYear \}\)/);
assert.match(ptoDatabaseLoadRunnerSource, /loadMetrics\.mark\("freshness-checked"/);
assert.match(ptoDatabaseLoadRunnerSource, /loadMetrics\.mark\("year-state-loaded"/);
assert.match(ptoDatabaseLoadRunnerSource, /loadMetrics\.mark\("state-normalized"\)/);
assert.match(ptoDatabaseLoadRunnerSource, /loadMetrics\.finish\(\{ mode: "database" \}\)/);
assert.match(ptoDatabaseLoadMetricsSource, /const slowPtoDatabaseLoadStepMs = 300/);
assert.match(ptoDatabaseLoadMetricsSource, /console\.info\("\[PTO database load\]"/);
assert.match(ptoDatabaseLoadMetricsSource, /stepMs < slowPtoDatabaseLoadStepMs/);
assert.match(ptoDatabaseLoadRunnerSource, /localPtoNeedsDatabaseFreshnessCheck/);
assert.match(ptoDatabaseLoadRunnerSource, /if \(currentYearLoaded && includeBuckets && !currentYearBucketsLoaded\) \{[\s\S]*loadPtoBucketsFromDatabase\(\)[\s\S]*return;[\s\S]*\}\s*\n\s*ptoDatabaseLoadedRef\.current = false;/);
assert.match(ptoDatabaseLoadRunnerSource, /loadPtoStateFromDatabase\(\{ year: ptoPlanYear,\s*includeBuckets \}\)/);
assert.match(ptoDatabaseLoadRunnerSource, /preserveFallbackBuckets: !includeBuckets/);
assert.match(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(ptoPlanYear\)/);
assert.match(dataPtoSource, /const ptoLoadRequestCache = new Map<string, Promise<unknown>>\(\);/);
assert.match(dataPtoSource, /function dedupePtoLoadRequest<T>\(key: string, load: \(\) => Promise<T>\): Promise<T>/);
assert.match(dataPtoSource, /ptoLoadRequestCache\.delete\(key\)/);
assert.match(dataPtoSource, /function mysqlPtoYearLoadKey\(year: string, includeBuckets: boolean\)/);
assert.match(dataPtoSource, /function latestPtoStateUpdatedAt\(values: Array<string \| null \| undefined>\)/);
assert.match(dataPtoSource, /const activeDateLoad = ptoLoadRequestCache\.get\(dateLoadKey\)/);
assert.match(dataPtoSource, /Promise\.all\(\[[\s\S]*activeDateLoad,[\s\S]*loadPtoBucketsFromDatabase\(\),[\s\S]*\]\)/);
assert.match(dataPtoSource, /updatedAt: latestPtoStateUpdatedAt\(\[dateState\.updatedAt, bucketState\.updatedAt\]\) \?\? dateState\.updatedAt/);
assert.match(dataPtoSource, /mysql:pto:load-updated-at/);
assert.match(dataPtoSource, /mysql:pto:load-buckets/);
assert.doesNotMatch(dataPtoSource, /dedupePtoLoadRequest\([^)]*"save/);
assert.doesNotMatch(ptoDatabaseLoadRunnerSource, /setPtoPlanYear\(loadedState\.uiState\.ptoPlanYear\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseUpdatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = resolution\.kind === "empty-save-local";/);
assert.match(ptoDatabaseLoadRunnerSource, /ptoDatabaseFullSaveNextRef\.current = true;[\s\S]*ptoDatabaseSaveSnapshotRef\.current = createPtoDatabaseSaveBaseline\("", databaseState\?\.updatedAt \?\? null\)/);
assert.match(ptoDatabaseLoadApplySource, /export function createPtoDatabaseLoadBaselineWithBuckets/);
assert.match(ptoDatabaseLoadApplySource, /function setDeferredPtoDatabaseLoadBaseline/);
assert.match(ptoDatabaseLoadApplySource, /const placeholderBaseline = createPtoDatabaseSaveBaseline\("", updatedAt\);/);
assert.match(ptoDatabaseLoadApplySource, /requestIdleCallback\(callback, \{ timeout: 2000 \}\)/);
assert.match(ptoDatabaseLoadApplySource, /if \(ptoDatabaseSaveSnapshotRef\.current !== placeholderBaseline\) return;/);
assert.match(ptoDatabaseLoadApplySource, /serializePtoDatabaseState\(snapshotState\)/);
assert.match(ptoPersistenceComparisonSource, /const ptoDatabaseStateSerializationCache = new WeakMap<DataPtoState, string>\(\);/);
assert.match(ptoPersistenceComparisonSource, /ptoDatabaseStateSerializationCache\.get\(state\)/);
assert.match(ptoPersistenceComparisonSource, /ptoDatabaseStateSerializationCache\.set\(state, serialized\)/);
assert.match(initialAppStorageSource, /const initialPtoDataStorageKeys = initialPtoStorageKeys\.filter/);
assert.match(initialAppStorageSource, /export function hasInitialStoredPtoState\(\)/);
assert.match(initialAppStorageSource, /initialPtoDataStorageKeys\.some\(\(key\) => window\.localStorage\.getItem\(key\) !== null\)/);
assert.match(initialAppStorageSource, /export function readInitialStoredPtoState\(\)/);
assert.match(initialAppDataLoadStepsSource, /readInitialStoredAppState\(\{ includePto: !databaseConfigured \}\)/);
assert.match(initialAppDataLoadStepsSource, /if \(!databaseConfigured\) \{[\s\S]*const localInitialPtoState = buildInitialPtoState\(storedState\);[\s\S]*applyInitialPtoState\(localInitialPtoState/);
assert.match(initialAppDataLoadStepsSource, /hasStoredPtoStateRef\.current = hasInitialStoredPtoState\(\);/);
assert.doesNotMatch(initialAppDataLoadStepsSource, /setPtoDatabaseLoadStarted\(true\)/);
assert.doesNotMatch(initialAppDataLoadStepsSource, /databaseConfigured \? readInitialStoredPtoState\(\) : storedState/);
assert.match(ptoDatabaseLoadRunnerSource, /import \{ hasInitialStoredPtoState \} from "@\/features\/app\/initialAppStorage";/);
assert.match(ptoDatabaseLoadRunnerSource, /createPtoDatabaseLocalHydration\(\{/);
assert.match(ptoDatabaseLocalHydrationSource, /import \{ hasInitialStoredPtoState, readInitialStoredPtoState \} from "@\/features\/app\/initialAppStorage";/);
assert.match(ptoDatabaseLocalHydrationSource, /const hydrateInitialLocalPtoState = \(\) => \{/);
assert.match(ptoDatabaseLocalHydrationSource, /buildInitialPtoState\(readInitialStoredPtoState\(\)\)/);
assert.match(ptoDatabaseLocalHydrationSource, /createPtoDatabaseState\(\{[\s\S]*manualYears: localInitialPtoState\.manualYears \?\? currentState\.manualYears/);
assert.match(ptoDatabaseLocalHydrationSource, /applyInitialPtoState\(localInitialPtoState/);
assert.match(ptoDatabaseLoadRunnerSource, /const hasLocalPtoSnapshot = hasStoredPtoStateRef\.current \|\| hasInitialStoredPtoState\(\);/);
assert.match(ptoDatabaseLoadRunnerSource, /localHydration\.hydrateInitialLocalPtoState\(\);[\s\S]*localPtoCanSkipFullDatabaseLoad/);
assert.match(ptoDatabaseLoadRunnerSource, /currentState: localHydration\.getLocalPtoStateForResolution\(\)/);
assert.match(ptoDatabaseLoadRunnerSource, /normalizeLoadedPtoDatabaseState\(databaseState, localHydration\.getLocalPtoStateForResolution\(\)/);
assert.match(ptoDatabaseSaveSource, /return await savePtoDatabaseChanges\("manual"\);/);
assert.match(ptoDatabaseSaveSource, /return false;/);
assert.match(ptoDatabaseSaveSource, /return true;/);
assert.match(ptoDatabaseSaveSource, /const ptoDatabaseDirtyRef = useRef\(false\);/);
assert.match(ptoDatabaseSaveSource, /const ptoDatabaseRetryTimerRef = useRef<number \| null>\(null\);/);
assert.match(ptoDatabaseSaveSource, /const ptoDatabaseRetryDelayRef = useRef\(ptoDatabaseRetryInitialDelayMs\);/);
assert.match(ptoDatabaseSaveSource, /const clearPtoDatabaseRetryTimer = useCallback/);
assert.match(ptoDatabaseSaveSource, /const schedulePtoDatabaseRetry = useCallback/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseRetryMaxDelayMs/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseMessages\.retrying\(retryDelay\)/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseRetryTimerRef\.current = window\.setTimeout/);
assert.match(ptoDatabaseSaveSource, /if \(!ptoDatabaseDirtyRef\.current\) \{[\s\S]*return true;[\s\S]*\}/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSaveShouldSkip\(mode, snapshotToSave, ptoDatabaseSaveSnapshotRef\.current\)\) \{[\s\S]*ptoDatabaseDirtyRef\.current = false;[\s\S]*return true;[\s\S]*\}/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSaveShouldSkip\(mode, snapshotAtWrite, ptoDatabaseSaveSnapshotRef\.current\)\) \{[\s\S]*return ptoDatabaseSaveSnapshotRef\.current;[\s\S]*\}/);
assert.match(ptoDatabaseSaveSource, /const baseline = readPtoDatabaseSaveBaseline\(ptoDatabaseSaveSnapshotRef\.current\);/);
assert.match(ptoDatabaseSaveSource, /if \(!ptoDatabaseDirtyRef\.current\) \{[\s\S]*setPtoDatabaseMessage\(ptoDatabaseMessages\.alreadySaved\);[\s\S]*return true;[\s\S]*\}\s*const stateToSave = ptoDatabaseStateRef\.current;\s*const snapshotToSave = serializePtoDatabaseState\(stateToSave\);/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseSaveSnapshotRef\.current = savedSnapshot;\s*ptoDatabaseFullSaveNextRef\.current = false;\s*ptoDatabaseRetryDelayRef\.current = ptoDatabaseRetryInitialDelayMs;\s*const hasPendingChanges = ptoDatabaseStateChanged\(ptoDatabaseStateRef\.current, savedSnapshot\);\s*ptoDatabaseDirtyRef\.current = hasPendingChanges;/);
assert.match(ptoDatabaseSaveSource, /if \(hasPendingChanges\) \{\s*setPtoSaveRevision\(\(current\) => current \+ 1\);\s*\}/);
assert.match(ptoDatabaseSaveSource, /if \(!databaseConfigured \|\| !ptoDatabaseLoadedRef\.current \|\| ptoDatabaseLoadedYearRef\.current !== currentYear\) return;\s*ptoDatabaseDirtyRef\.current = true;/);
assert.match(ptoDatabaseSaveSource, /getPtoDatabaseExpectedUpdatedAt = useCallback/);
assert.match(ptoDatabaseSaveSource, /const isPtoDatabaseDirty = useCallback\(\(\) => ptoDatabaseDirtyRef\.current, \[\]\);/);
assert.match(ptoDatabaseSaveSource, /if \(ptoDatabaseSavingRef\.current\) \{[\s\S]*try \{[\s\S]*await ptoDatabaseActiveSaveRef\.current;[\s\S]*\} catch \{[\s\S]*return false;[\s\S]*\}/);
assert.doesNotMatch(ptoDatabaseSaveSource, /refreshPtoDatabaseSaveBaseline/);
assert.match(ptoDatabaseSaveSource, /let suppressQueuedRetry = false;/);
assert.match(ptoDatabaseSaveSource, /if \(isDatabaseConflictError\(error\)\) \{[\s\S]*suppressQueuedRetry = true;[\s\S]*ptoDatabaseSaveQueuedRef\.current = false;[\s\S]*setPtoDatabaseMessage\(ptoDatabaseMessages\.conflict\);/);
assert.match(ptoDatabaseSaveSource, /schedulePtoDatabaseRetry\(\);/);
assert.match(ptoDatabaseSaveSource, /if \(!suppressQueuedRetry && ptoDatabaseSaveQueuedRef\.current\) \{/);
assert.match(ptoDatabaseSaveSource, /const saveAllYears = ptoDatabaseFullSaveNextRef\.current;/);
assert.match(ptoDatabaseSaveSource, /const stateToSave = ptoDatabaseStateRef\.current;/);
assert.match(ptoDatabaseSaveSource, /const stateAtWrite = ptoDatabaseStateRef\.current;/);
assert.match(ptoDatabaseSaveSource, /stateAtWrite === stateToSave[\s\S]*\? snapshotToSave[\s\S]*: serializePtoDatabaseState\(stateAtWrite\)/);
assert.match(ptoDatabaseSaveSource, /yearScope: saveAllYears \? undefined : stateAtWrite\.uiState\.ptoPlanYear/);
assert.match(ptoPersistenceStorageSource, /scopePtoStateForYear/);
assert.match(ptoPersistenceStorageSource, /const stateToSave = options\.yearScope \? scopePtoStateForYear\(state, options\.yearScope\) : state;/);
assert.match(ptoPersistenceStorageSource, /savePtoStateToDatabase\(stateToSave, \{ expectedUpdatedAt, yearScope: options\.yearScope \}\)/);
assert.match(ptoPersistenceStorageSource, /type PtoBrowserStorageSnapshotCache = \{[\s\S]*snapshot: PtoBrowserStorageSnapshot;[\s\S]*refs: Record<string, unknown>;[\s\S]*\};/);
assert.match(ptoPersistenceStorageSource, /export type PtoBrowserStorageSaveOptions = \{[\s\S]*markLocalUpdatedAt: boolean;[\s\S]*localUpdatedAt\?: string \| null;[\s\S]*includeBuckets\?: boolean;[\s\S]*\};/);
assert.match(ptoPersistenceStorageSource, /includeBuckets\?: boolean;/);
assert.match(ptoPersistenceStorageSource, /ptoBrowserStorageSnapshot\(state, previousCache, options\.includeBuckets \?\? true\)/);
assert.match(ptoPersistenceStorageSource, /if \(cache && cache\.refs\[storageKey\] === ref && typeof cache\.snapshot\[storageKey\] === "string"\)/);
assert.match(ptoPersistenceStorageSource, /function readBrowserStorageValue\(storageKey: string, failedLocalKeys: string\[\]\)/);
assert.match(ptoPersistenceStorageSource, /function writeBrowserStorageValue\(storageKey: string, value: string, failedLocalKeys: string\[\]\)/);
assert.match(ptoPersistenceStorageSource, /const failedLocalKeys: string\[\] = \[\];/);
assert.match(ptoPersistenceStorageSource, /const previousValue = previousCache\?\.snapshot\[storageKey\] \?\? readBrowserStorageValue\(storageKey, failedLocalKeys\);/);
assert.match(ptoPersistenceStorageSource, /if \(previousValue === value\) return;/);
assert.match(ptoPersistenceStorageSource, /const updatedAt = options\.localUpdatedAt === undefined \? new Date\(\)\.toISOString\(\) : options\.localUpdatedAt;/);
assert.match(ptoPersistenceStorageSource, /if \(options\.markLocalUpdatedAt && updatedAt\) \{[\s\S]*writeBrowserStorageValue\(adminStorageKeys\.ptoLocalUpdatedAt, updatedAt, failedLocalKeys\);/);
assert.doesNotMatch(ptoPersistenceStorageSource, /adminStorageKeys\.appLocalUpdatedAt/);
assert.match(ptoLocalPersistenceSource, /useRef<PtoBrowserStorageSnapshotCache \| null>\(null\)/);
assert.match(ptoLocalPersistenceSource, /ptoDatabaseLoadedBucketsYearRef: RefObject<string \| null>;/);
assert.match(ptoLocalPersistenceSource, /const currentPtoTabRef = useRef\(ptoTab\);/);
assert.match(ptoLocalPersistenceSource, /const currentPtoPlanYearRef = useRef\(ptoPlanYear\);/);
assert.match(ptoLocalPersistenceSource, /useEffect\(\(\) => \{[\s\S]*currentPtoTabRef\.current = ptoTab;[\s\S]*currentPtoPlanYearRef\.current = ptoPlanYear;[\s\S]*\}, \[ptoPlanYear, ptoTab\]\);/);
assert.match(ptoLocalPersistenceSource, /const includeBuckets = !skipUntilDatabaseLoaded[\s\S]*\|\| currentPtoTab === "buckets"[\s\S]*\|\| ptoDatabaseLoadedBucketsYearRef\.current === currentPtoPlanYear;/);
assert.match(ptoLocalPersistenceSource, /const localUpdatedAt = markLocalUpdatedAt && !isPtoDatabaseDirty\(\)[\s\S]*\? getPtoDatabaseExpectedUpdatedAt\(\)[\s\S]*: undefined;/);
assert.match(ptoLocalPersistenceSource, /savePtoStateToBrowserStorage\([\s\S]*markLocalUpdatedAt,[\s\S]*localUpdatedAt,/);
assert.match(ptoLocalPersistenceSource, /savePtoStateToBrowserStorage\([\s\S]*includeBuckets,[\s\S]*markLocalUpdatedAt,[\s\S]*localUpdatedAt,/);
assert.match(ptoLocalPersistenceSource, /ptoLocalSaveSnapshotRef\.current = result\.cache;/);
assert.match(ptoLocalPersistenceSource, /if \(result\.failedLocalKeys\.length > 0\) \{[\s\S]*showSaveStatus\("error", "Локальная копия ПТО не сохранена полностью\. Проверь свободное место браузера\."\);/);
assert.doesNotMatch(ptoLocalPersistenceSource, /ptoAreaFilter: string;/);
assert.doesNotMatch(ptoLocalPersistenceSource, /expandedPtoMonths: Record<string, boolean>;/);
assert.doesNotMatch(ptoLocalPersistenceSource, /\n\s*ptoTab,\n\s*expandedPtoMonths,\n\s*savePtoLocalState,/);
assert.match(ptoDatabaseSaveSource, /ptoDatabaseFullSaveNextRef\.current = false;/);
assert.match(ptoDateTableContextSource, /kind: "day-values"/);
assert.match(ptoInlineDatabaseWriteSource, /export function enqueuePtoInlineDatabaseWrite/);
assert.match(ptoInlineDatabaseWriteSource, /isDatabaseConflictError/);
assert.match(ptoInlineDatabaseWriteSource, /showSaveStatus\("error", inlineWriteErrorMessage\(label, error\)\)/);
assert.match(ptoInlineDatabaseWriteSource, /const result = await write\(\);[\s\S]*onSaved\(result\);[\s\S]*return result;/);
assert.match(ptoInlineDatabaseWriteSource, /onError\?: \(error: unknown\) => void;/);
assert.match(ptoInlineDatabaseWriteSource, /onError\?\.\(error\);/);
assert.doesNotMatch(ptoInlineDatabaseWriteSource, /\.then\(onSaved\)/);
assert.match(ptoDateTableContextSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "ячейка дня"[\s\S]*showSaveStatus[\s\S]*savePtoDayValueWithRowToDatabase/);
assert.match(ptoDateTableContextSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "значения месяца"[\s\S]*showSaveStatus[\s\S]*savePtoDayValuesWithRowToDatabase/);
assert.match(ptoLinkedRowsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "удаление строки"[\s\S]*deletePtoRowsFromDatabase/);
assert.match(ptoYearEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "удаление года"[\s\S]*deletePtoYearFromDatabase/);
assert.match(ptoBucketsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "ковш"[\s\S]*showSaveStatus[\s\S]*savePtoBucketValueToDatabase/);
assert.match(ptoBucketsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "очистка ковшей"[\s\S]*deletePtoBucketValuesFromDatabase/);
assert.match(ptoBucketsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "строка ковшей"[\s\S]*savePtoBucketRowToDatabase/);
assert.match(ptoBucketsEditorSource, /enqueuePtoInlineDatabaseWrite\(\{[\s\S]*label: "удаление строки ковшей"[\s\S]*deletePtoBucketRowFromDatabase/);
assert.doesNotMatch(ptoBucketsEditorSource, /Database PTO bucket .* failed/);
assert.match(ptoDatabaseSaveSource, /markPtoDatabaseInlineWriteSaved/);
assert.match(ptoDatabaseSaveSource, /if \(!ptoDatabaseStateChanged\(ptoDatabaseStateRef\.current, ptoDatabaseSaveSnapshotRef\.current\)\) \{[\s\S]*ptoDatabaseDirtyRef\.current = false;[\s\S]*\}/);

assert.match(sharedDatabaseSaveQueueSource, /type SharedDatabaseSaveQueue = \{[\s\S]*storage: Record<string, string>;[\s\S]*settings: Record<string, unknown>;[\s\S]*\};/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSaveQueueRef = useRef<SharedDatabaseSaveQueue \| null>\(null\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseSavingRef = useRef\(false\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedDatabaseRetryTimerRef = useRef<ReturnType<typeof setTimeout> \| null>\(null\);/);
assert.match(sharedDatabaseSaveQueueSource, /const sharedSettingsFallbackWarning =[\s\S]*Таблица app_settings недоступна[\s\S]*резервную таблицу app_state/);
assert.match(sharedDatabaseSaveQueueSource, /clearTimeout\(sharedDatabaseRetryTimerRef\.current\);/);
assert.match(sharedDatabaseSaveQueueSource, /useEffect\(\(\) => clearSharedDatabaseRetryTimer, \[clearSharedDatabaseRetryTimer\]\);/);
assert.match(sharedDatabaseSaveQueueSource, /createAppStateStorageSnapshot/);
assert.match(sharedDatabaseSaveQueueSource, /const runSharedDatabaseSaveQueue = useCallback\(async \(\) => \{[\s\S]*while \(sharedDatabaseSaveQueueRef\.current\)[\s\S]*await saveSharedAppSettingsToDatabase\(queuedSave\.settings\);[\s\S]*if \(!appSettingsDatabaseLoadedRef\.current\) \{[\s\S]*const fallbackSaved = await saveSharedAppStateToDatabase\(queuedSave\.storage\);[\s\S]*if \(fallbackSaved\) \{[\s\S]*showSaveStatus\("error", sharedSettingsFallbackWarning\);[\s\S]*\}/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /conflictRetries/);
assert.match(sharedDatabaseSaveQueueSource, /let failed = false;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!isDatabaseConflictError\(error\)\) \{[\s\S]*sharedDatabaseSaveQueueRef\.current = sharedDatabaseSaveQueueRef\.current \?\? queuedSave;[\s\S]*failed = true;[\s\S]*throw error;/);
assert.match(sharedDatabaseSaveQueueSource, /if \(!failed\) \{[\s\S]*sharedDatabaseRetryDelayRef\.current = sharedDatabaseRetryInitialDelayMs;[\s\S]*if \(sharedDatabaseSaveQueueRef\.current\) \{[\s\S]*void runSharedDatabaseSaveQueue\(\);/);
assert.match(sharedDatabaseSaveQueueSource, /if \(sharedDatabaseSaveQueueRef\.current && !sharedDatabaseRetryTimerRef\.current\) \{[\s\S]*setTimeout\(\(\) => \{[\s\S]*void runSharedDatabaseSaveQueue\(\);[\s\S]*\}, retryDelay\);/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /refreshSharedDatabaseSaveBaselines/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /loadAppSettingsFromDatabase/);
assert.match(sharedDatabaseSaveQueueSource, /const savedSettings = await saveAppSettingsToDatabase\(delta\.settings/);
assert.match(sharedDatabaseSaveQueueSource, /if \(storageSnapshot === checkpoint\.storageSnapshot\) return false;/);
assert.match(sharedDatabaseSaveQueueSource, /showSaveStatus\("saved", "Общие данные сохранены\."\);[\s\S]*return true;/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /const storageSnapshot = JSON\.stringify\(storage\)/);
assert.doesNotMatch(sharedDatabaseSaveQueueSource, /JSON\.stringify\(checkpoint\.storage\)/);
assert.match(sharedDatabaseSaveQueueSource, /sharedDatabaseSaveQueueRef\.current = null;[\s\S]*failed = true;[\s\S]*showSaveStatus\([\s\S]*break;/);
assert.match(sharedDatabaseSaveQueueSource, /Данные на сервере изменились другим пользователем\. Локальная правка сохранена в браузере; обнови страницу перед повторным сохранением\./);
assert.match(sharedDatabaseSaveQueueSource, /Сохранение в базу не прошло\. Повторю автоматически через/);
assert.match(sharedDatabaseSaveQueueSource, /return useCallback\(\(savedLocalState: SharedAppStorageWriteResult\) => \{[\s\S]*sharedDatabaseSaveQueueRef\.current = \{[\s\S]*storage: savedLocalState\.storage,[\s\S]*settings: savedLocalState\.settings,[\s\S]*void runSharedDatabaseSaveQueue\(\);/);
assert.match(appLocalPersistenceSource, /import \{ useSharedDatabaseSaveQueue \} from "@\/features\/app\/useSharedDatabaseSaveQueue";/);
assert.match(appLocalPersistenceSource, /const appLocalSaveDelayMs = 300;/);
assert.match(appLocalPersistenceSource, /const firstAppLocalSaveDelayMs = 1200;/);
assert.match(appLocalPersistenceSource, /const firstAppLocalIdleTimeoutMs = 2000;/);
assert.match(appLocalPersistenceSource, /const appStateSaveIdleRef = useRef<number \| null>\(null\);/);
assert.match(appLocalPersistenceSource, /const firstAppLocalSaveRef = useRef\(true\);/);
assert.match(appLocalPersistenceSource, /window\.cancelIdleCallback\?\.\(appStateSaveIdleRef\.current\)/);
assert.match(appLocalPersistenceSource, /const persistAppLocalState = useCallback\(\(reason: string\) => \{[\s\S]*if \(savedLocalState\.changedKeys\.length > 0\) \{[\s\S]*enqueueSharedDatabaseSave\(savedLocalState\);[\s\S]*requestClientSnapshotSave\(reason\);/);
assert.match(appLocalPersistenceSource, /if \(savedLocalState\.failedLocalKeys\.length > 0\) \{[\s\S]*showSaveStatus\("error", "Локальная копия общих данных не сохранена полностью\. Проверь свободное место браузера\."\);/);
assert.match(appLocalPersistenceSource, /if \(isFirstSave && window\.requestIdleCallback\) \{[\s\S]*window\.requestIdleCallback\(runSave, \{[\s\S]*timeout: firstAppLocalIdleTimeoutMs/);
assert.match(appLocalPersistenceSource, /isFirstSave \? firstAppLocalSaveDelayMs : appLocalSaveDelayMs/);
assert.match(appLocalPersistenceSource, /persistAppLocalState\("app-state-save"\)/);
assert.match(appLocalPersistenceSource, /window\.addEventListener\("pagehide", flushAppLocalState\)/);
assert.match(appLocalPersistenceSource, /clearScheduledAppLocalStateSave\(\);[\s\S]*persistAppLocalState\("app-state-pagehide"\);/);

assert.match(ptoDateRowValueEditorSource, /const inlineSaveQueued = rowToSave \? saveDayPatch\(rowToSave, day, parsedValue, requestSave\) : false;\s*if \(!inlineSaveQueued\) requestSave\(\);/);
assert.match(ptoDateRowValueEditorSource, /const inlineSaveQueued = rowToSave \? saveDayPatches\(rowToSave, patches, requestSave\) : false;\s*if \(!inlineSaveQueued\) requestSave\(\);/);
assert.match(ptoDateTableContextSource, /if \(!table \|\| !databaseConfigured \|\| !databaseLoadedRef\.current\) return false;/);
assert.match(ptoDateTableContextSource, /if \(!table \|\| !databaseConfigured \|\| !databaseLoadedRef\.current \|\| values\.length === 0\) return false;/);
assert.match(ptoDateTableContextSource, /onError,\s*\}\);\s*return true;/);
assert.match(ptoDateTableContextSource, /savePtoDayValueWithRowToDatabase\(table, row, day, value, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(ptoDateTableContextSource, /savePtoDayValuesWithRowToDatabase\(table, row, values, \{\s*expectedUpdatedAt: getPtoDatabaseExpectedUpdatedAt\(\),\s*\}\)/);
assert.match(ptoLinkedRowsEditorSource, /markPtoDatabaseInlineWriteSaved\(result\?\.updatedAt \?\? null,\s*\{[\s\S]*kind: "date-row"[\s\S]*action: "delete"[\s\S]*rowIds: \[row\.id\]/);
assert.match(ptoYearEditorSource, /markPtoDatabaseInlineWriteSaved\(result\?\.updatedAt \?\? null,\s*\{[\s\S]*kind: "year"[\s\S]*action: "delete"[\s\S]*year,/);
assert.match(supabasePtoCommandsSource, /expectedUpdatedAt: options\.expectedUpdatedAt/);
assert.match(supabasePtoCommandsSource, /assertSupabasePtoInlineMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, client\)/);
assert.match(supabasePtoCommandsSource, /supabasePtoInlineWriteResult\(client\)/);
assert.match(supabasePtoFreshnessSource, /export async function assertSupabasePtoInlineMatchesExpectedUpdatedAt/);
assert.match(supabasePtoFreshnessSource, /export async function loadSupabasePtoCurrentUpdatedAt/);
assert.match(mysqlPtoCommandsSource, /type PtoInlineWriteOptions = Pick<PtoSnapshotWriteOptions, "expectedUpdatedAt">;/);
assert.match(mysqlPtoCommandsSource, /import \{ chunkValues \} from "\.\/pto-write-utils";/);
assert.doesNotMatch(mysqlPtoCommandsSource, /const inlineDeleteBatchSize = 250;/);
assert.match(mysqlPtoCommandsSource, /for \(const rowIdBatch of chunkValues\(rowIds\)\) \{[\s\S]*DELETE FROM pto_day_values[\s\S]*DELETE FROM pto_rows/);
assert.match(mysqlPtoCommandsSource, /DELETE FROM pto_day_values[\s\S]*AND \(row_id, work_date\) IN/);
assert.match(mysqlPtoCommandsSource, /DELETE FROM pto_bucket_values[\s\S]*WHERE \(row_key, equipment_key\) IN/);
assert.match(mysqlPtoFreshnessSource, /function mysqlUpdatedAfterExpectedClause/);
assert.match(mysqlPtoFreshnessSource, /return ` \$\{prefix\} updated_at > \?`;/);
assert.match(mysqlPtoFreshnessSource, /const freshCurrentRecords = currentRecords\.filter/);
assert.match(mysqlPtoFreshnessSource, /if \(freshCurrentRecords\.length === 0\) return;/);
assert.match(mysqlPtoFreshnessSource, /for \(const record of freshCurrentRecords\)/);
assert.match(mysqlPtoFreshnessSource, /const ptoFreshRowSelectColumns = \[/);
assert.match(mysqlPtoFreshnessSource, /SELECT \$\{ptoFreshRowSelectColumns\} FROM pto_rows/);
assert.match(mysqlPtoFreshnessSource, /SELECT \$\{ptoFreshDayValueSelectColumns\} FROM pto_day_values/);
assert.match(mysqlPtoFreshnessSource, /SELECT \$\{ptoFreshBucketValueSelectColumns\} FROM pto_bucket_values/);
assert.doesNotMatch(mysqlPtoFreshnessSource, /SELECT \* FROM pto_/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValueWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /savePtoDayValuesWithRowToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);[\s\S]*await insertPtoRowsIfMissing/);
assert.match(mysqlPtoCommandsSource, /deletePtoRowsFromMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
assert.match(mysqlPtoCommandsSource, /savePtoBucketValueToMysql\([\s\S]*options: PtoInlineWriteOptions = \{\},[\s\S]*await assertPtoVersionMatchesExpectedUpdatedAt\(options\.expectedUpdatedAt, execute\);/);
