import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const rolloutPath = resolve(testDir, "..", "docs", "STAGE_2_READ_MODEL_ROLLOUT.md");

assert.equal(existsSync(rolloutPath), true);

const rollout = readFileSync(rolloutPath, "utf8");

assert.match(rollout, /first bounded read models/i);
assert.match(rollout, /one Next\.js project/);
assert.match(rollout, /one shared `\/api\/database` route/);
assert.match(rollout, /access matrix capability contract before the handler/);
assert.match(rollout, /server pagination, server filters, server sort, and bounded search/);
assert.match(rollout, /`501 planned_module_database_action`/);
assert.match(rollout, /avoid write, export, import, workflow, Excel\/PDF, and UI edit mode/);
assert.match(rollout, /`taxation-waybills`/);
assert.match(rollout, /`list-waybills`/);
assert.match(rollout, /`get-waybill`/);
assert.match(rollout, /`mining-shift-reports`/);
assert.match(rollout, /`list-shift-reports`/);
assert.match(rollout, /`get-shift-report`/);
assert.match(rollout, /Do not connect more than two modules in one pull request/);
assert.match(rollout, /`reviewModuleHandlerActivation` returns `ready-to-register`/);
assert.match(rollout, /`createServerListQueryEnvelope`/);
assert.match(rollout, /`createServerDetailQueryEnvelope`/);
assert.match(rollout, /`createPublicReadModelListResponse`/);
assert.match(rollout, /`createPublicReadModelDetailResponse`/);
assert.match(rollout, /live registry adds exactly one action at a time/);
assert.match(rollout, /authorization runs before the handler/);
assert.match(rollout, /section scope is enforced/);
assert.match(rollout, /detail response requires `id` and returns at most one row/);
assert.match(rollout, /public responses do not expose `query`, `cacheKey`, table names, column names/);
assert.match(rollout, /SQL text, SQL params or persistence metadata/);
assert.match(rollout, /no global React state for full tables/);
assert.match(rollout, /no edit button wired to a write endpoint/);
assert.match(rollout, /npm run verify/);
assert.match(rollout, /nextActivationGate/);
assert.match(rollout, /requiredCommands/);
assert.match(rollout, /schema preflight, activation preflight, and `npm run verify`/);
assert.match(rollout, /read-model checklist, `nextAction`, audit target, and evidence validator\s+carry the same `implementationPath` value/);
assert.match(rollout, /`lib\/server\/database\/module-live-handlers\.ts`/);
assert.match(rollout, /maxParallelActivations = 1/);
assert.match(rollout, /requiresSchemaPreflightBeforeActivation = true/);
assert.match(rollout, /requiresGreenVerifyBeforeActivation = true/);
assert.match(rollout, /noLiveRegistrationFromSummary = true/);
assert.match(rollout, /createStage2LiveReadinessSnapshot/);
assert.match(rollout, /firstBatchReadModelsReady/);
assert.match(rollout, /pendingReadModelActions/);
assert.match(rollout, /writeHandlersBlockedUntilReadModelsLive/);
assert.match(rollout, /liveActivationAllowedNow/);
assert.match(rollout, /npm run check:read-model-schema -- --workspace taxation/);
assert.match(rollout, /npm run check:read-model-schema -- --workspace taxation --dry-run/);
assert.match(rollout, /npm run check:read-model-schema -- --module taxation-waybills --dry-run/);
assert.match(rollout, /single read-model module/);
assert.match(rollout, /dry-run mode is a planning aid only/);
assert.match(rollout, /does not prove that the target\s+schema exists/);
assert.match(rollout, /schemaPreflightGate/);
assert.match(rollout, /liveActivationReady = false/);
assert.match(rollout, /databaseConnection = false/);
assert.match(rollout, /handlerRegistrationMutation = false/);
assert.match(rollout, /noLiveRegistrationFromPacket = true/);
assert.match(rollout, /not approval for live registration/);
assert.match(rollout, /npm run review:live-handler -- --resource taxation --action list-waybills/);
assert.match(rollout, /--contract-only/);
assert.match(rollout, /ready: false/);
assert.match(rollout, /schemaChecked: false/);
assert.match(rollout, /mysql_schema_not_checked/);
assert.match(rollout, /do not register a live\s+handler from contract-only output/i);
assert.match(rollout, /liveActivationGate/);
assert.match(rollout, /appliesChanges = false/);
assert.match(rollout, /liveRegistryMutation = false/);
assert.match(rollout, /handlerRegistrationMutation = false/);
assert.match(rollout, /noLiveRegistrationFromPreflight = true/);
assert.match(rollout, /liveActivationReady = false/);
assert.match(rollout, /information_schema\.COLUMNS/);
assert.match(rollout, /missing table or column blocks live\s+activation/);
assert.match(rollout, /activation review and the module-specific MySQL schema\s+preflight/);
assert.match(rollout, /registration\s+candidate summary matches the single action/);
assert.match(rollout, /HTTP\/1\.1 200 OK/);
assert.match(rollout, /Stop Conditions/);
assert.match(rollout, /new backend process/);
assert.match(rollout, /`useAppStateBundle` needs new document arrays/);
assert.match(rollout, /`AppRoot` needs business logic/);

console.log("Stage 2 read model rollout checks passed");
