import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const rolloutPath = resolve(testDir, "..", "docs", "STAGE_2_WRITE_HANDLER_ROLLOUT.md");

assert.equal(existsSync(rolloutPath), true);

const rollout = readFileSync(rolloutPath, "utf8");

assert.match(rollout, /Stage 2 Write Handler Rollout/);
assert.match(rollout, /does not authorize a\s+write handler by itself/);
assert.match(rollout, /Read-model rollout must come first/);
assert.match(rollout, /one-document actions/);
assert.match(rollout, /Do not activate batch writes, whole-table saves/);
assert.match(rollout, /One Next\.js project/);
assert.match(rollout, /One shared `\/api\/database` router/);
assert.match(rollout, /No separate Node\.js app per workspace/);
assert.match(rollout, /No separate database per module/);
assert.match(rollout, /No permanent worker process/);
assert.match(rollout, /No full table loaded into React state/);
assert.match(rollout, /No write response that returns a full table/);
assert.match(rollout, /access-matrix authorization/);
assert.match(rollout, /section scope/);
assert.match(rollout, /moduleCreateMutationPlans\.ts/);
assert.match(rollout, /modulePatchMutationPlans\.ts/);
assert.match(rollout, /moduleWritePipelinePlans\.ts/);
assert.match(rollout, /atomic_write_transaction/);
assert.match(rollout, /expected_version_check/);
assert.match(rollout, /change_history_write/);
assert.match(rollout, /post_commit_side_effects_only/);
assert.match(rollout, /compact_write_response/);
assert.match(rollout, /npm run plan:stage2-write-handlers -- --requested-by backend-engineer --summary-only/);
assert.match(rollout, /does not query\s+MySQL or register live handlers/);
assert.match(rollout, /expected guarded factory/);
assert.match(rollout, /read-model prerequisites/);
assert.match(rollout, /listAction/);
assert.match(rollout, /detailAction/);
assert.match(rollout, /listReady/);
assert.match(rollout, /detailReady/);
assert.match(rollout, /current `planned-only` live status/);
assert.match(rollout, /write smoke after\s+activation needs a test database/);
assert.match(rollout, /appliesChanges = false/);
assert.match(rollout, /databaseConnection = false/);
assert.match(rollout, /liveRegistryMutation = false/);
assert.match(rollout, /handlerRegistrationMutation = false/);
assert.match(rollout, /doesNotRegisterHandlers = true/);
assert.match(rollout, /stopConditions/);
assert.match(rollout, /do not register from planner output/);
assert.match(rollout, /readModelPrerequisites\.ready/);
assert.match(rollout, /plan:write-handler-activation` or `review:write-handler/);
assert.match(rollout, /compact_write_response/);
assert.match(rollout, /more than one entity row/);
assert.match(rollout, /nextActivationGate/);
assert.match(rollout, /requiredCommands/);
assert.match(rollout, /requiresReadModelsLiveBeforeActivation = true/);
assert.match(rollout, /blockedUntilReadModelsLive = true/);
assert.match(rollout, /liveActivationAllowedNow = false/);
assert.match(rollout, /requiresGreenVerifyBeforeActivation = true/);
assert.match(rollout, /requiresTestDatabaseForWriteSmoke = true/);
assert.match(rollout, /noLiveRegistrationFromSummary = true/);
assert.match(rollout, /createStage2LiveReadinessSnapshot/);
assert.match(rollout, /firstBatchReadModelsReady = true/);
assert.match(rollout, /writeHandlersBlockedUntilReadModelsLive = true/);
assert.match(rollout, /liveActivationAllowedNow = false/);
assert.match(rollout, /npm run plan:write-handler-activation -- --resource taxation --action create-waybill --factory-kind create/);
assert.match(rollout, /appliesChanges = false/);
assert.match(rollout, /databaseConnection = false/);
assert.match(rollout, /liveRegistryMutation = false/);
assert.match(rollout, /handlerRegistrationMutation = false/);
assert.match(rollout, /write_handler_not_registered/);
assert.match(rollout, /readModelLivePrerequisites/);
assert.match(rollout, /same module list\/detail read models must be\s+`live`/);
assert.match(rollout, /read_model_live_prerequisite_missing/);
assert.match(rollout, /stop before live write registration/);
assert.match(rollout, /createWriteReadModelLivePrerequisites/);
assert.match(rollout, /use the same\s+read-model live gate/);
assert.match(rollout, /npm run review:write-handler -- --resource taxation --action create-waybill/);
assert.match(rollout, /Write handler implementation paths must live under/);
assert.match(rollout, /lib\/server\/database\/handlers\/<resource>\/<action>\.ts/);
assert.match(rollout, /module-live-handlers\.ts` file is only for read-model registration/);
assert.match(rollout, /must match the requested resource and action exactly/);
assert.match(rollout, /expectedImplementationPath/);
assert.match(rollout, /generated `review:write-handler` command must use that expected\s+path/);
assert.match(rollout, /must not print a\s+`review:write-handler` next command/);
assert.match(rollout, /Activation evidence must also use the exact implementation path/);
assert.match(rollout, /not merely any file under `lib\/server\/database\/handlers\/`/);
assert.match(rollout, /evidence validator JSON prints `expectedImplementationPath`/);
assert.match(rollout, /write-handler checklist, `nextAction`, audit target, and evidence validator\s+must carry the same `implementationPath` value/);
assert.match(rollout, /createExpectedWriteImplementationPath/);
assert.match(rollout, /Resource and action segments must stay lowercase path segments/);
assert.match(rollout, /traversal, slashes, and backslashes collapse to an invalid marker/);
assert.match(rollout, /handler_key_invalid/);
assert.match(rollout, /stopConditions` must tell the operator to stop/);
assert.match(rollout, /ready = true/);
assert.match(rollout, /not an automatic registry\s+mutation/);
assert.match(rollout, /liveActivationReady/);
assert.match(rollout, /remain `false` until `readModelLivePrerequisites\.requiredActions` are all\s+`live`/);
assert.match(rollout, /blocking actual write-handler live activation/);
assert.match(rollout, /guarded `create` factory/);
assert.match(rollout, /guarded `patch` factory/);
assert.match(rollout, /module-write-execution\.ts/);
assert.match(rollout, /version = 1/);
assert.match(rollout, /WHERE id = \? AND version = \?/);
assert.match(rollout, /per-field change-history insert/);
assert.match(rollout, /commitCondition = all_steps_ok/);
assert.match(rollout, /post-commit side-effect plan only after commit/);
assert.match(rollout, /compact success, conflict, or duplicate response/);
assert.match(rollout, /opened `version`/);
assert.match(rollout, /one affected entity row/);
assert.match(rollout, /`409` conflict/);
assert.match(rollout, /change history writes one row per changed field/);
assert.match(rollout, /2 GB RAM/);
assert.match(rollout, /no full-table duplicate detection/);
assert.match(rollout, /no inline aggregate recalculation/);
assert.match(rollout, /no whole-table response after a write/);
assert.match(rollout, /queue bounded prepared-aggregate refreshes/);
assert.match(rollout, /Stop Conditions/);
assert.match(rollout, /no ready read-model path/);
assert.match(rollout, /expected guarded factory/);
assert.match(rollout, /new API route, new database, or new backend process/);
assert.match(rollout, /AppRoot/);
assert.match(rollout, /useAppStateBundle/);
assert.match(rollout, /npm run verify/);
assert.match(rollout, /npm run smoke:local/);
assert.match(rollout, /`501 planned_module_database_action`/);
assert.match(rollout, /`planned-only` live status/);

console.log("Stage 2 write handler rollout checks passed");
