import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));

function readSource(relativePath: string) {
  return readFileSync(resolve(testDir, "..", relativePath), "utf8");
}

const workspaceDomainSource = readSource("lib/domain/workspaces/workspaces.ts");
const workspaceModuleCatalogSource = readSource("lib/domain/workspaces/moduleCatalog.ts");
const workspaceReadinessSource = readSource("lib/domain/workspaces/readiness.ts");
const workspaceGuardrailsSource = readSource("lib/domain/workspaces/guardrails.ts");
const workspaceModuleDataAccessGuardrailsSource = readSource("lib/domain/workspaces/moduleDataAccessGuardrails.ts");
const workspaceModuleReadModelGuardrailsSource = readSource("lib/domain/workspaces/moduleReadModelGuardrails.ts");
const workspaceModuleDataRouteGuardrailsSource = readSource("lib/domain/workspaces/moduleDataRouteGuardrails.ts");
const workspaceModuleListQueryGuardrailsSource = readSource("lib/domain/workspaces/moduleListQueryGuardrails.ts");
const workspaceModuleWriteModelGuardrailsSource = readSource("lib/domain/workspaces/moduleWriteModelGuardrails.ts");
const workspaceGuardrailTypesSource = readSource("lib/domain/workspaces/guardrailTypes.ts");
const workspaceGuardrailRulesSource = [
  workspaceGuardrailsSource,
  workspaceModuleDataAccessGuardrailsSource,
  workspaceModuleReadModelGuardrailsSource,
  workspaceModuleDataRouteGuardrailsSource,
  workspaceModuleListQueryGuardrailsSource,
  workspaceModuleWriteModelGuardrailsSource,
  workspaceGuardrailTypesSource,
].join("\n");
const workspaceWorkflowGuardrailsSource = readSource("lib/domain/workspaces/workflowGuardrails.ts");
const moduleActionPreflightSource = readSource("lib/domain/workspaces/moduleActionPreflight.ts");
const workflowTransitionsSource = readSource("lib/domain/workflows/statusTransitions.ts");
const subdomainRoutingSource = readSource("lib/domain/workspaces/subdomainRouting.ts");
const paginationSource = readSource("lib/domain/data-access/pagination.ts");
const indexContractsSource = readSource("lib/domain/data-access/indexContracts.ts");
const indexContractCatalogSource = readSource("lib/domain/data-access/indexContractCatalog.ts");
const indexMigrationPlanSource = readSource("lib/domain/data-access/indexMigrationPlan.ts");
const moduleDataRoutesSource = readSource("lib/domain/data-access/moduleDataRoutes.ts");
const moduleDataRouteCatalogSource = readSource("lib/domain/data-access/moduleDataRouteCatalog.ts");
const moduleListQueryPlansSource = readSource("lib/domain/data-access/moduleListQueryPlans.ts");
const moduleListQueryPlanCatalogSource = readSource("lib/domain/data-access/moduleListQueryPlanCatalog.ts");
const moduleDetailQueryPlansSource = readSource("lib/domain/data-access/moduleDetailQueryPlans.ts");
const moduleDetailQueryPlanCatalogSource = readSource("lib/domain/data-access/moduleDetailQueryPlanCatalog.ts");
const modulePatchMutationPlansSource = readSource("lib/domain/data-access/modulePatchMutationPlans.ts");
const modulePatchMutationPlanCatalogSource = readSource("lib/domain/data-access/modulePatchMutationPlanCatalog.ts");
const modulePatchPayloadValidationSource = readSource("lib/domain/data-access/modulePatchPayloadValidation.ts");
const moduleCreateMutationPlansSource = readSource("lib/domain/data-access/moduleCreateMutationPlans.ts");
const moduleCreateMutationPlanCatalogSource = readSource("lib/domain/data-access/moduleCreateMutationPlanCatalog.ts");
const moduleExportPlansSource = readSource("lib/domain/data-access/moduleExportPlans.ts");
const moduleExportPlanCatalogSource = readSource("lib/domain/data-access/moduleExportPlanCatalog.ts");
const moduleDatabaseRequestsSource = readSource("lib/domain/data-access/moduleDatabaseRequests.ts");
const moduleDatabaseRequestValidationSource = readSource("lib/domain/data-access/moduleDatabaseRequestValidation.ts");
const moduleWorkflowTransitionsSource = readSource("lib/domain/data-access/moduleWorkflowTransitions.ts");
const moduleHandlerRuntimeContractsSource = readSource("lib/domain/data-access/moduleHandlerRuntimeContracts.ts");
const moduleDatabaseAuthorizationSource = readSource("lib/domain/data-access/moduleDatabaseAuthorization.ts");
const stage2WriteHandlerActivationChecklistSource = readSource("lib/domain/workspaces/stage2WriteHandlerActivationChecklist.ts");
const stage2WriteHandlerActivationSummarySource = readSource("lib/domain/workspaces/stage2WriteHandlerActivationSummary.ts");
const stage2WriteHandlerActivationCliSource = readSource("scripts/plan-stage-2-write-handler-activation.ts");
const queryPolicySource = readSource("lib/domain/data-access/queryPolicy.ts");
const workspaceQueryPoliciesSource = readSource("lib/domain/data-access/workspaceQueryPolicies.ts");
const persistenceContractsSource = readSource("lib/domain/data-access/persistenceContracts.ts");
const persistenceContractCatalogSource = readSource("lib/domain/data-access/persistenceContractCatalog.ts");
const databaseQueryPolicySource = readSource("lib/server/database/query-policy.ts");
const databaseListQueryBuilderSource = readSource("lib/server/database/list-query-builder.ts");
const databaseMutationSqlBuilderSource = readSource("lib/server/database/mutation-sql-builder.ts");
const databaseMutationSqlEvaluatorSource = readSource("lib/server/database/mutation-sql-evaluators.ts");
const databaseMutationTransactionPlanSource = readSource("lib/server/database/mutation-transaction-plan.ts");
const databaseMutationSideEffectsPlanSource = readSource("lib/server/database/mutation-side-effects-plan.ts");
const databaseMutationResponsePlanSource = readSource("lib/server/database/mutation-response-plan.ts");
const databaseModuleWriteExecutionSource = readSource("lib/server/database/module-write-execution.ts");
const databaseModuleAuthorizationSource = readSource("lib/server/database/module-authorization.ts");
const writeHandlerRegistrationReviewSource = readSource("lib/server/database/write-handler-registration-review.ts");
const writeHandlerRegistrationReviewCliSource = readSource("scripts/review-write-handler-registration.ts");
const writeHandlerActivationPacketCliSource = readSource("scripts/plan-write-handler-activation-packet.ts");
const plannedModuleActionsSource = readSource("lib/server/database/planned-module-actions.ts");

assert.match(workspaceDomainSource, /dispatchServiceWorkspaces/);
assert.match(workspaceDomainSource, /workspaceSubdomainRoutes/);
assert.match(workspaceModuleCatalogSource, /workspaceModuleCatalog/);
assert.match(workspaceModuleCatalogSource, /server-paginated/);
assert.match(workspaceModuleCatalogSource, /versioned-patch/);
assert.match(workspaceModuleCatalogSource, /getWorkspaceModuleCatalog/);
assert.match(workspaceReadinessSource, /createWorkspaceReadinessSummary/);
assert.match(workspaceReadinessSource, /server-pagination/);
assert.match(workspaceReadinessSource, /createWorkspaceGuardrailReport/);
assert.match(workspaceReadinessSource, /guardrails/);
assert.match(workspaceGuardrailRulesSource, /createWorkspaceGuardrailReport/);
assert.match(workspaceGuardrailRulesSource, /missing_query_policy/);
assert.match(workspaceGuardrailRulesSource, /missing_index_contract/);
assert.match(workspaceGuardrailRulesSource, /index_contract_missing_required_filter/);
assert.match(workspaceGuardrailRulesSource, /index_migration_definition_issue/);
assert.match(workspaceGuardrailRulesSource, /duplicate_index_migration_name/);
assert.match(workspaceGuardrailRulesSource, /missing_list_query_plan/);
assert.match(workspaceGuardrailRulesSource, /list_query_plan_missing_required_filter/);
assert.match(workspaceGuardrailRulesSource, /list_query_plan_unsafe_identifier/);
assert.match(workspaceGuardrailRulesSource, /missing_persistence_contract/);
assert.match(workspaceGuardrailRulesSource, /patch_contract_without_version_history/);
assert.match(workspaceGuardrailRulesSource, /missing_patch_mutation_plan/);
assert.match(workspaceGuardrailRulesSource, /patch_mutation_plan_without_version_history/);
assert.match(workspaceGuardrailRulesSource, /patch_mutation_plan_missing_section_scope/);
assert.match(workspaceGuardrailRulesSource, /patch_mutation_plan_unsafe_identifier/);
assert.match(workspaceGuardrailRulesSource, /missing_workflow_transition_binding/);
assert.match(workspaceGuardrailRulesSource, /workflow_transition_workspace_mismatch/);
assert.match(workspaceGuardrailRulesSource, /getWorkflowTransitionGuardrailIssues/);
assert.match(workspaceWorkflowGuardrailsSource, /getWorkflowModulesWithoutTransitionBinding/);
assert.match(workspaceWorkflowGuardrailsSource, /getWorkflowTransitionBindingWorkspaceMismatches/);
assert.match(workspaceGuardrailRulesSource, /missing_create_mutation_plan/);
assert.match(workspaceGuardrailRulesSource, /create_mutation_plan_without_duplicate_keys/);
assert.match(workspaceGuardrailRulesSource, /create_mutation_plan_missing_section_scope/);
assert.match(workspaceGuardrailRulesSource, /missing_export_plan/);
assert.match(workspaceGuardrailRulesSource, /export_plan_without_bounded_query/);
assert.match(workspaceGuardrailRulesSource, /missing_detail_query_plan/);
assert.match(workspaceGuardrailRulesSource, /detail_query_plan_missing_version/);
assert.match(workspaceGuardrailRulesSource, /detail_query_plan_unsafe_identifier/);
assert.match(workspaceGuardrailRulesSource, /database_authorization_gap/);
assert.match(workspaceGuardrailRulesSource, /duplicate_database_action/);
assert.match(workspaceGuardrailRulesSource, /getModuleDatabaseAuthorizationGaps/);
assert.match(moduleActionPreflightSource, /preflightWorkspaceModuleAction/);
assert.match(moduleActionPreflightSource, /access_denied/);
assert.match(moduleActionPreflightSource, /query_rejected/);
assert.match(moduleActionPreflightSource, /missing_persistence_contract/);
assert.match(moduleActionPreflightSource, /export_plan_missing/);
assert.match(moduleActionPreflightSource, /export_query_rejected/);
assert.match(workflowTransitionsSource, /workflowDefinitions/);
assert.match(workflowTransitionsSource, /requiresVersionCheck: true/);
assert.match(workflowTransitionsSource, /writesChangeHistory: true/);
assert.match(workflowTransitionsSource, /getAllowedNextStatuses/);
assert.match(workflowTransitionsSource, /canTransitionStatus/);
assert.match(workflowTransitionsSource, /"waybill"/);
assert.match(workflowTransitionsSource, /WaybillStatus/);
assert.match(workflowTransitionsSource, /fuel-accounting-period/);
assert.match(workflowTransitionsSource, /vehicle-movement/);
assert.match(subdomainRoutingSource, /resolveWorkspaceByHost/);
assert.match(subdomainRoutingSource, /normalizeWorkspaceHost/);
assert.match(paginationSource, /dispatchPageSizeOptions/);
assert.match(paginationSource, /ServerPageQuery/);
assert.match(paginationSource, /recommendedDatabaseIndexes/);
assert.match(paginationSource, /date\+section_id/);
assert.match(indexContractsSource, /moduleDatabaseIndexContracts/);
assert.match(indexContractsSource, /indexContractCatalog/);
assert.match(indexContractsSource, /getWorkspaceModulesWithoutIndexContract/);
assert.match(indexContractsSource, /getIndexContractsMissingRequiredFilters/);
assert.match(indexContractCatalogSource, /taxation_waybills_driver_date_idx/);
assert.match(indexContractCatalogSource, /smts_fuel_drains_date_section_vehicle_status_idx/);
assert.match(indexMigrationPlanSource, /createModuleDatabaseIndexMigrationStatements/);
assert.match(indexMigrationPlanSource, /ALTER TABLE/);
assert.match(indexMigrationPlanSource, /quoteMysqlIdentifier/);
assert.match(indexMigrationPlanSource, /getDuplicateModuleDatabaseIndexNames/);
assert.match(indexMigrationPlanSource, /getModuleDatabaseIndexDefinitionIssues/);
assert.match(moduleDataRoutesSource, /moduleDataRouteContracts/);
assert.match(moduleDataRoutesSource, /moduleDataRouteCatalog/);
assert.match(moduleDataRoutesSource, /single-database-router/);
assert.match(moduleDataRoutesSource, /\/api\/database/);
assert.match(moduleDataRouteCatalogSource, /single-database-router/);
assert.match(moduleDataRouteCatalogSource, /list-waybills/);
assert.match(moduleDataRouteCatalogSource, /load-ai-context/);
assert.match(moduleDataRoutesSource, /getWorkspaceModulesWithoutDataRouteContract/);
assert.match(moduleDataRoutesSource, /getDataRouteContractsOutsideSingleDatabaseRouter/);
assert.match(moduleDataRoutesSource, /getDuplicateModuleDataRouteActions/);
assert.match(moduleDataRoutesSource, /listModuleDataRouteActionBindings/);
assert.match(moduleDataRoutesSource, /getModuleDataRouteContractByDatabaseAction/);
assert.match(moduleListQueryPlansSource, /moduleListQueryPlans/);
assert.match(moduleListQueryPlansSource, /getWorkspaceModulesWithoutListQueryPlan/);
assert.match(moduleListQueryPlansSource, /getListQueryPlansMissingRequiredFilterColumns/);
assert.match(moduleListQueryPlansSource, /getUnsafeListQueryPlanIdentifiers/);
assert.match(moduleListQueryPlansSource, /moduleListQueryPlanCatalog/);
assert.match(moduleListQueryPlanCatalogSource, /taxation_waybills/);
assert.match(moduleDetailQueryPlansSource, /moduleDetailQueryPlans/);
assert.match(moduleDetailQueryPlansSource, /requiresId: true/);
assert.match(moduleDetailQueryPlansSource, /maxRows: 1/);
assert.match(moduleDetailQueryPlansSource, /getMissingDetailQueryPlans/);
assert.match(moduleDetailQueryPlansSource, /moduleDetailQueryPlanCatalog/);
assert.match(moduleDetailQueryPlanCatalogSource, /taxation_waybills/);
assert.match(modulePatchMutationPlansSource, /modulePatchMutationPlans/);
assert.match(modulePatchMutationPlansSource, /requiresExpectedVersion: true/);
assert.match(modulePatchMutationPlansSource, /writesChangeHistory: true/);
assert.match(modulePatchMutationPlansSource, /getMissingPatchMutationPlans/);
assert.match(modulePatchMutationPlansSource, /validateModulePatchPayload/);
assert.match(modulePatchPayloadValidationSource, /patch_field_not_allowed/);
assert.match(modulePatchPayloadValidationSource, /allowedFieldGroups/);
assert.match(modulePatchMutationPlansSource, /modulePatchMutationPlanCatalog/);
assert.match(modulePatchMutationPlanCatalogSource, /taxation_waybills/);
assert.match(moduleCreateMutationPlansSource, /moduleCreateMutationPlans/);
assert.match(moduleCreateMutationPlansSource, /moduleCreateMutationPlanCatalog/);
assert.match(moduleCreateMutationPlansSource, /validateModuleCreatePayload/);
assert.match(moduleCreateMutationPlansSource, /create_field_group_missing/);
assert.match(moduleCreateMutationPlanCatalogSource, /initialVersion: 1/);
assert.match(moduleCreateMutationPlanCatalogSource, /duplicateKeyGroups/);
assert.match(moduleCreateMutationPlanCatalogSource, /taxation_waybills/);
assert.match(moduleExportPlansSource, /moduleExportPlans/);
assert.match(moduleExportPlansSource, /moduleExportPlanCatalog/);
assert.match(moduleExportPlanCatalogSource, /createsQueuedRequest: true/);
assert.match(moduleExportPlanCatalogSource, /storesFileByReference: true/);
assert.match(moduleExportPlanCatalogSource, /prepared-aggregate/);
assert.match(moduleExportPlanCatalogSource, /report_export_requests/);
assert.match(moduleDatabaseRequestsSource, /createWorkspaceModuleDatabaseRequest/);
assert.match(moduleDatabaseRequestsSource, /preflightWorkspaceModuleAction/);
assert.match(moduleDatabaseRequestsSource, /validateWorkspaceModuleDatabaseRequestPayload/);
assert.match(moduleDatabaseRequestsSource, /resolveModuleDatabaseSectionId/);
assert.match(moduleDatabaseRequestsSource, /\/api\/database/);
assert.match(moduleDatabaseRequestValidationSource, /patch_payload_required/);
assert.match(moduleDatabaseRequestValidationSource, /validateModulePatchPayload/);
assert.match(moduleDatabaseRequestValidationSource, /section_scope_required/);
assert.match(moduleDatabaseRequestValidationSource, /validateModuleCreatePayload/);
assert.match(moduleDatabaseRequestValidationSource, /validateModuleWorkflowTransitionPayload/);
assert.match(moduleDatabaseRequestValidationSource, /reason: input\.reason/);
assert.match(moduleDatabaseRequestValidationSource, /export_format_required/);
assert.match(moduleDatabaseRequestValidationSource, /export_format_unsupported/);
assert.match(moduleDatabaseRequestValidationSource, /createModuleDatabaseAuthorizationContext/);
assert.match(moduleWorkflowTransitionsSource, /moduleWorkflowTransitionBindings/);
assert.match(moduleWorkflowTransitionsSource, /getWorkflowModulesWithoutTransitionBinding/);
assert.match(moduleWorkflowTransitionsSource, /getWorkflowTransitionBindingWorkspaceMismatches/);
assert.match(moduleWorkflowTransitionsSource, /getWorkflowTransitionBindingsForUnknownModules/);
assert.match(moduleWorkflowTransitionsSource, /getWorkflowTransitionBindingsWithUnknownWorkflows/);
assert.match(moduleWorkflowTransitionsSource, /getWorkflowTransitionBindingWorkflowWorkspaceMismatches/);
assert.match(moduleWorkflowTransitionsSource, /workflow_transition_not_allowed/);
assert.match(moduleWorkflowTransitionsSource, /workflow_approval_required/);
assert.match(moduleHandlerRuntimeContractsSource, /compact_write_response/);
assert.match(stage2WriteHandlerActivationChecklistSource, /createStage2WriteHandlerActivationChecklist/);
assert.match(stage2WriteHandlerActivationChecklistSource, /validateStage2WriteHandlerActivationChecklist/);
assert.match(stage2WriteHandlerActivationChecklistSource, /readModelPrerequisites/);
assert.match(stage2WriteHandlerActivationChecklistSource, /stage2FirstReadModelModuleIds/);
assert.match(stage2WriteHandlerActivationChecklistSource, /appliesChanges: false/);
assert.match(stage2WriteHandlerActivationChecklistSource, /databaseConnection: false/);
assert.match(stage2WriteHandlerActivationChecklistSource, /liveRegistryMutation: false/);
assert.match(stage2WriteHandlerActivationChecklistSource, /handlerRegistrationMutation: false/);
assert.match(stage2WriteHandlerActivationChecklistSource, /doesNotRegisterHandlers: true/);
assert.match(stage2WriteHandlerActivationChecklistSource, /noWriteSmokeAfterLiveWithoutTestDatabase: true/);
assert.match(stage2WriteHandlerActivationSummarySource, /createStage2WriteHandlerActivationSummary/);
assert.match(stage2WriteHandlerActivationSummarySource, /createWriteReadModelLivePrerequisites/);
assert.match(stage2WriteHandlerActivationSummarySource, /blockedUntilReadModelsLive/);
assert.match(stage2WriteHandlerActivationSummarySource, /liveActivationAllowedNow/);
assert.match(stage2WriteHandlerActivationCliSource, /createStage2WriteHandlerActivationChecklist/);
assert.match(stage2WriteHandlerActivationCliSource, /createStage2WriteHandlerActivationSummary/);
assert.match(stage2WriteHandlerActivationCliSource, /does not query MySQL/);
assert.match(stage2WriteHandlerActivationCliSource, /does not register live handlers/);
assert.doesNotMatch(stage2WriteHandlerActivationCliSource, /loadDotEnvLocal|closeMysqlPool|process\.env\.DB|dbRows|dbExecute/);
assert.match(moduleDatabaseAuthorizationSource, /getModuleDatabaseAuthorizationRequirement/);
assert.match(moduleDatabaseAuthorizationSource, /createModuleDatabaseAuthorizationContext/);
assert.match(moduleDatabaseAuthorizationSource, /resolveModuleDatabaseSectionId/);
assert.match(moduleDatabaseAuthorizationSource, /missingSectionScope/);
assert.match(moduleDatabaseAuthorizationSource, /requiredCapability/);
assert.match(moduleDatabaseAuthorizationSource, /requiresAccessMatrix: true/);
assert.match(moduleDatabaseAuthorizationSource, /getModuleDatabaseAuthorizationGaps/);
assert.match(queryPolicySource, /defaultHeavyTableQueryPolicy/);
assert.match(queryPolicySource, /gpsEventsQueryPolicy/);
assert.match(queryPolicySource, /periodSectionStatusQueryPolicy/);
assert.match(queryPolicySource, /vehicleScopedStatusQueryPolicy/);
assert.match(queryPolicySource, /adminMatrixQueryPolicy/);
assert.match(queryPolicySource, /validateServerPageQueryPolicy/);
assert.match(queryPolicySource, /date_range_too_large/);
assert.match(queryPolicySource, /search_requires_filters/);
assert.match(workspaceQueryPoliciesSource, /workspaceModuleQueryPolicyBindings/);
assert.match(workspaceQueryPoliciesSource, /getWorkspaceModulesWithoutQueryPolicy/);
assert.match(workspaceQueryPoliciesSource, /smts-fuel-drains/);
assert.match(workspaceQueryPoliciesSource, /taxation-fuel-periods/);
assert.match(persistenceContractsSource, /modulePersistenceContracts/);
assert.match(persistenceContractsSource, /persistenceContractCatalog/);
assert.match(persistenceContractsSource, /getWorkspaceModulesWithoutPersistenceContract/);
assert.match(persistenceContractsSource, /getPatchContractsWithoutVersioning/);
assert.match(persistenceContractCatalogSource, /supplier_fuel_invoices/);
assert.match(persistenceContractCatalogSource, /prepared_report_aggregates/);
assert.match(persistenceContractCatalogSource, /continuous background analysis/);
assert.match(databaseQueryPolicySource, /assertDatabaseListQueryPolicy/);
assert.match(databaseQueryPolicySource, /DatabasePayloadError/);
assert.match(databaseQueryPolicySource, /normalizeServerPageQueryDraft/);
assert.match(databaseListQueryBuilderSource, /createDatabaseListQuerySqlPlan/);
assert.match(databaseListQueryBuilderSource, /LIMIT \? OFFSET \?/);
assert.match(databaseListQueryBuilderSource, /quoteMysqlColumnPath/);
assert.match(databaseMutationSqlBuilderSource, /createDatabasePatchMutationWhereSqlPlan/);
assert.match(databaseMutationSqlBuilderSource, /createDatabasePatchMutationSetSqlPlan/);
assert.match(databaseMutationSqlBuilderSource, /createDatabaseChangeHistoryInsertSqlPlan/);
assert.match(databaseMutationSqlBuilderSource, /createDatabaseCreateEntityInsertSqlPlan/);
assert.match(databaseMutationSqlBuilderSource, /createDatabaseCreateDuplicateCheckSqlPlans/);
assert.match(databaseMutationSqlBuilderSource, /evaluateDatabaseCreateDuplicateCheckResults/);
assert.match(databaseMutationSqlEvaluatorSource, /create_duplicate_found/);
assert.match(databaseMutationSqlBuilderSource, /evaluateDatabaseCreateEntityInsertResult/);
assert.match(databaseMutationSqlEvaluatorSource, /create_entity_inserted/);
assert.match(databaseMutationSqlBuilderSource, /evaluateDatabaseChangeHistoryInsertResult/);
assert.match(databaseMutationSqlEvaluatorSource, /change_history_row_count_mismatch/);
assert.match(databaseMutationSqlBuilderSource, /evaluateDatabasePatchMutationResult/);
assert.match(databaseMutationSqlEvaluatorSource, /patch_conflict_or_scope_mismatch/);
assert.match(databaseMutationSqlBuilderSource, /forbidsReservedColumnPatch/);
assert.match(databaseMutationSqlBuilderSource, /writesPerField/);
assert.match(databaseMutationSqlBuilderSource, /old_value_json/);
assert.match(databaseMutationSqlBuilderSource, /forbidsReservedColumnOverride/);
assert.match(databaseMutationSqlBuilderSource, /maxEntityRowWrites: 1/);
assert.match(databaseMutationSqlBuilderSource, /requiresExpectedVersion: true/);
assert.match(databaseMutationSqlBuilderSource, /LIMIT 1/);
assert.match(databaseMutationSqlBuilderSource, /quoteMysqlColumnPath/);
assert.match(databaseMutationTransactionPlanSource, /createDatabaseCreateWriteTransactionSqlPlan/);
assert.match(databaseMutationTransactionPlanSource, /createDatabasePatchWriteTransactionSqlPlan/);
assert.match(databaseMutationTransactionPlanSource, /commitCondition: "all_steps_ok"/);
assert.match(databaseMutationTransactionPlanSource, /rollbackOnAnyStepFailure: true/);
assert.match(databaseMutationTransactionPlanSource, /noPostCommitSideEffectsBeforeCommit: true/);
assert.match(databaseMutationTransactionPlanSource, /evaluateDatabaseCreateDuplicateCheckResults/);
assert.match(databaseMutationTransactionPlanSource, /evaluateDatabasePatchMutationResult/);
assert.match(databaseMutationTransactionPlanSource, /evaluateDatabaseChangeHistoryInsertResult/);
assert.match(databaseMutationSideEffectsPlanSource, /createDatabasePostCommitSideEffectsPlan/);
assert.match(databaseMutationSideEffectsPlanSource, /requiresCommittedTransaction: true/);
assert.match(databaseMutationSideEffectsPlanSource, /queueMode: "post-commit"/);
assert.match(databaseMutationSideEffectsPlanSource, /queue-prepared-aggregate-refresh/);
assert.match(databaseMutationSideEffectsPlanSource, /createReportAggregateRefreshEnvelope/);
assert.match(databaseMutationSideEffectsPlanSource, /noInlineReportRecalculation: true/);
assert.match(databaseMutationSideEffectsPlanSource, /noFullReportRebuild: true/);
assert.match(databaseMutationSideEffectsPlanSource, /noResidentProcess: true/);
assert.match(databaseMutationResponsePlanSource, /createDatabaseCreateWriteSuccessResponsePlan/);
assert.match(databaseMutationResponsePlanSource, /createDatabasePatchWriteSuccessResponsePlan/);
assert.match(databaseMutationResponsePlanSource, /createDatabasePatchConflictResponsePlan/);
assert.match(databaseMutationResponsePlanSource, /createDatabaseCreateDuplicateResponsePlan/);
assert.match(databaseMutationResponsePlanSource, /returnsFullTable: false/);
assert.match(databaseMutationResponsePlanSource, /maxResponseRows: 1/);
assert.match(databaseMutationResponsePlanSource, /single-row-detail-query/);
assert.match(databaseMutationResponsePlanSource, /queuedAggregateRefreshIds/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseCreateDuplicateCheckSqlPlans/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseCreateEntityInsertSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePatchMutationSetSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePatchMutationWhereSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseChangeHistoryInsertSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseCreateWriteTransactionSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePatchWriteTransactionSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePostCommitSideEffectsPlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseCreateWriteSuccessResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePatchWriteSuccessResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabasePatchConflictResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /createDatabaseCreateDuplicateResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /evaluateDatabaseCreateDuplicateCheckResults/);
assert.match(databaseModuleWriteExecutionSource, /evaluateDatabaseCreateEntityInsertResult/);
assert.match(databaseModuleWriteExecutionSource, /evaluateDatabaseChangeHistoryInsertResult/);
assert.match(databaseModuleWriteExecutionSource, /evaluateDatabasePatchMutationResult/);
assert.match(databaseModuleWriteExecutionSource, /createDuplicateCheckSqlPlans/);
assert.match(databaseModuleWriteExecutionSource, /createEntityInsertSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /evaluateEntityInsertResult/);
assert.match(databaseModuleWriteExecutionSource, /evaluateChangeHistoryInsertResult/);
assert.match(databaseModuleWriteExecutionSource, /evaluateDuplicateCheckResults/);
assert.match(databaseModuleWriteExecutionSource, /createPatchWhereSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createPatchSetSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createChangeHistoryInsertSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createWriteTransactionSqlPlan/);
assert.match(databaseModuleWriteExecutionSource, /createPostCommitSideEffectsPlan/);
assert.match(databaseModuleWriteExecutionSource, /createWriteSuccessResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /createConflictResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /createDuplicateResponsePlan/);
assert.match(databaseModuleWriteExecutionSource, /evaluatePatchResult/);
assert.match(databaseModuleAuthorizationSource, /authorizeModuleDatabaseRequestWithCurrentTabs/);
assert.match(databaseModuleAuthorizationSource, /workspaceCurrentTabFallbacks/);
assert.match(databaseModuleAuthorizationSource, /missing_section_scope/);
assert.match(databaseModuleAuthorizationSource, /current_tab_permission_denied/);
assert.match(writeHandlerRegistrationReviewSource, /reviewWriteLiveHandlerRegistrationCandidate/);
assert.match(writeHandlerRegistrationReviewSource, /reviewModuleHandlerActivation/);
assert.match(writeHandlerRegistrationReviewSource, /getModuleWritePipelinePlan/);
assert.match(writeHandlerRegistrationReviewSource, /compact_write_response/);
assert.match(writeHandlerRegistrationReviewSource, /doesNotRegisterHandler: true/);
assert.match(writeHandlerRegistrationReviewCliSource, /reviewWriteLiveHandlerRegistrationCandidate/);
assert.match(writeHandlerRegistrationReviewCliSource, /databaseConnection: false/);
assert.match(writeHandlerRegistrationReviewCliSource, /liveRegistryMutation: false/);
assert.match(writeHandlerRegistrationReviewCliSource, /npm run verify/);
assert.match(writeHandlerActivationPacketCliSource, /reviewWriteLiveHandlerRegistrationCandidate/);
assert.match(writeHandlerActivationPacketCliSource, /reviewModuleHandlerActivation/);
assert.match(writeHandlerActivationPacketCliSource, /getModuleLiveHandlerStatus/);
assert.match(writeHandlerActivationPacketCliSource, /write_handler_not_registered/);
assert.match(writeHandlerActivationPacketCliSource, /handlerRegistrationMutation: false/);
assert.match(writeHandlerActivationPacketCliSource, /databaseConnection: false/);
assert.match(writeHandlerActivationPacketCliSource, /liveRegistryMutation: false/);
assert.match(writeHandlerActivationPacketCliSource, /npm run verify/);
assert.match(plannedModuleActionsSource, /plannedModuleDatabaseActionCode/);
assert.match(plannedModuleActionsSource, /getPlannedModuleDatabaseAction/);
assert.match(plannedModuleActionsSource, /createPlannedModuleDatabaseActionResponse/);

console.log("Workspace data-access architecture checks passed");
