import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));

const adminNavigationSource = readFileSync(resolve(testDir, "../lib/domain/admin/navigation.ts"), "utf8");
const navigationTabsSource = readFileSync(resolve(testDir, "../lib/domain/navigation/tabs.ts"), "utf8");
const workspacesSource = readFileSync(resolve(testDir, "../lib/domain/workspaces/workspaces.ts"), "utf8");
const appPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/AppPrimaryContent.tsx"), "utf8");
const appRootSource = readFileSync(resolve(testDir, "../features/app/AppRoot.tsx"), "utf8");
const useAppStateBundleSource = readFileSync(resolve(testDir, "../features/app/useAppStateBundle.ts"), "utf8");
const lazyPrimaryContentSource = readFileSync(resolve(testDir, "../features/app/lazyPrimaryContent.tsx"), "utf8");
const useAppSectionPreloaderSource = readFileSync(resolve(testDir, "../features/app/useAppSectionPreloader.ts"), "utf8");
const lazySectionsSource = readFileSync(resolve(testDir, "../features/app/lazySections.ts"), "utf8");
const workspaceOverviewSource = readFileSync(resolve(testDir, "../features/workspaces/WorkspaceOverviewSection.tsx"), "utf8");
const commonProcessesSource = readFileSync(resolve(testDir, "../features/workspaces/CommonProcessesSection.tsx"), "utf8");
const fuelSectionSource = readFileSync(resolve(testDir, "../features/fuel/FuelSection.tsx"), "utf8");
const safetySectionSource = readFileSync(resolve(testDir, "../features/safety-driving/SafetySection.tsx"), "utf8");
const adminScreenSource = readFileSync(resolve(testDir, "../features/app/useAppAdminScreenProps.tsx"), "utf8");
const adminAccessSectionSource = readFileSync(resolve(testDir, "../features/admin/access/AdminAccessMatrixSection.tsx"), "utf8");

assert.match(adminNavigationSource, /"access"/);
assert.match(navigationTabsSource, /"home"/);
assert.match(navigationTabsSource, /"common"/);
assert.match(workspacesSource, /legacyWorkspaceTopTabBridges/);
assert.match(workspacesSource, /topTab: "pto"/);
assert.match(workspacesSource, /workspaceId: "mining-dispatch"/);
assert.match(workspacesSource, /topTab: "contractors"/);
assert.match(workspacesSource, /workspaceId: "taxation"/);
assert.match(appPrimaryContentSource, /renderedTopTab === "home"/);
assert.match(appPrimaryContentSource, /renderedTopTab === "common"/);
assert.doesNotMatch(appRootSource, /service-contracts/);
assert.doesNotMatch(appRootSource, /workspaceAccessMatrixPreview/);
assert.doesNotMatch(useAppStateBundleSource, /service-contracts/);
assert.doesNotMatch(useAppStateBundleSource, /workspaceAccessMatrixPreview/);
assert.match(lazyPrimaryContentSource, /WorkspaceOverviewPrimaryContent/);
assert.match(lazyPrimaryContentSource, /CommonProcessesPrimaryContent/);
assert.ok(lazyPrimaryContentSource.includes("\u0413\u043e\u0440\u043d\u0430\u044f \u0434\u0438\u0441\u043f\u0435\u0442\u0447\u0435\u0440\u0438\u0437\u0430\u0446\u0438\u044f"));
assert.ok(lazyPrimaryContentSource.includes("\u0422\u0430\u043a\u0441\u0438\u0440\u043e\u0432\u043a\u0430"));
assert.ok(lazyPrimaryContentSource.includes("\u0421\u041c\u0422\u0421 / GPS"));
assert.match(fuelSectionSource, /<SectionCard title=""/);
assert.doesNotMatch(fuelSectionSource, /\u0422\u0430\u043a\u0441\u0438\u0440\u043e\u0432\u043a\u0430 \/ \u0442\u043e\u043f\u043b\u0438\u0432\u043e \u2014/);
assert.ok(safetySectionSource.includes("GPS / \u0422\u0411"));
assert.doesNotMatch(useAppSectionPreloaderSource, /PtoPrimaryContent/);
assert.doesNotMatch(useAppSectionPreloaderSource, /ReportsPrimaryContent/);
assert.doesNotMatch(useAppSectionPreloaderSource, /AdminPrimaryContent/);
assert.doesNotMatch(workspaceOverviewSource, /@\/features\/dispatch|@\/features\/fuel|@\/features\/pto|@\/features\/reports/);
assert.doesNotMatch(workspaceOverviewSource, /createWorkspaceReadinessSummary/);
assert.doesNotMatch(workspaceOverviewSource, /createWorkspaceHandlerRolloutSummary/);
assert.doesNotMatch(workspaceOverviewSource, /createWorkspaceImplementationRoadmap/);
assert.doesNotMatch(workspaceOverviewSource, /createStage2FirstReadModelActivationSummary/);
assert.doesNotMatch(workspaceOverviewSource, /createStage2FirstReadModelBatch/);
assert.doesNotMatch(workspaceOverviewSource, /stage2ReadModelActivationChecklist/);
assert.match(workspaceOverviewSource, /getWorkspaceModuleCatalog/);
assert.match(workspaceOverviewSource, /workspace\.performanceRule/);
assert.ok(workspaceOverviewSource.includes("\u043b\u0435\u0433\u043a\u0438\u0439 \u0432\u0445\u043e\u0434"));
assert.doesNotMatch(workspaceOverviewSource, /roadmap\.nextBatch/);
assert.doesNotMatch(workspaceOverviewSource, /stage2Summary\.ready/);
assert.doesNotMatch(commonProcessesSource, /@\/features\/dispatch|@\/features\/fuel|@\/features\/pto|@\/features\/reports/);
assert.match(lazySectionsSource, /AdminAccessMatrixSection/);
assert.match(adminScreenSource, /adminSection === "access"/);
assert.ok(adminAccessSectionSource.includes("\u041c\u0430\u0442\u0440\u0438\u0446\u0430 \u0434\u043e\u0441\u0442\u0443\u043f\u0430"));
assert.ok(adminAccessSectionSource.toLowerCase().includes("\u043d\u0435 \u043c\u0435\u043d\u044f\u0435\u0442 \u0442\u0435\u043a\u0443\u0449\u0443\u044e \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044e"));

console.log("Workspace UI source checks passed");
