import type { ModulePatchMutationPlan } from "./modulePatchMutationPlans";

function createPatchMutationPlan(input: Omit<
  ModulePatchMutationPlan,
  | "idColumn"
  | "versionColumn"
  | "updatedAtColumn"
  | "updatedByColumn"
  | "changeHistoryEntity"
  | "patchOnly"
  | "requiresExpectedVersion"
  | "writesChangeHistory"
  | "scopeColumns"
> & { scopeColumns?: ModulePatchMutationPlan["scopeColumns"] }) {
  return {
    idColumn: "id",
    versionColumn: "version",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    changeHistoryEntity: "change_history_entries",
    patchOnly: true,
    requiresExpectedVersion: true,
    writesChangeHistory: true,
    scopeColumns: {},
    ...input,
  } satisfies ModulePatchMutationPlan;
}

export const modulePatchMutationPlans: ModulePatchMutationPlan[] = [
  createPatchMutationPlan({
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    action: "edit",
    databaseAction: "patch-shift-report",
    tableName: "mining_shift_reports",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["header", "lines", "non_completion_reason"],
  }),
  createPatchMutationPlan({
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    action: "approve",
    databaseAction: "transition-shift-report",
    tableName: "mining_shift_reports",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "mining-operational-accounting",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    action: "edit",
    databaseAction: "patch-operational-accounting-row",
    tableName: "mining_operational_accounting_rows",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["survey_adjustment", "correction_reason"],
  }),
  createPatchMutationPlan({
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    resource: "taxation",
    action: "edit",
    databaseAction: "patch-waybill",
    tableName: "taxation_waybills",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["driver", "vehicle", "shift", "basis", "print_state"],
  }),
  createPatchMutationPlan({
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    resource: "taxation",
    action: "approve",
    databaseAction: "transition-waybill",
    tableName: "taxation_waybills",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    resource: "taxation",
    action: "edit",
    databaseAction: "patch-fuel-period",
    tableName: "fuel_accounting_periods",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["period_totals", "invoice_link", "contractor_debt"],
  }),
  createPatchMutationPlan({
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    resource: "taxation",
    action: "approve",
    databaseAction: "transition-fuel-period",
    tableName: "fuel_accounting_periods",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "smts-vehicle-cards",
    workspaceId: "smts-gps",
    resource: "smts",
    action: "edit",
    databaseAction: "patch-vehicle-card",
    tableName: "smts_vehicle_cards",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["terminal", "sim", "dut", "ecodriving", "comment"],
  }),
  createPatchMutationPlan({
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    resource: "smts",
    action: "edit",
    databaseAction: "patch-fuel-drain-event",
    tableName: "smts_fuel_drain_events",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["verification", "comment"],
  }),
  createPatchMutationPlan({
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    resource: "smts",
    action: "approve",
    databaseAction: "transition-fuel-drain-event",
    tableName: "smts_fuel_drain_events",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    resource: "fleet",
    action: "edit",
    databaseAction: "patch-vehicle-movement",
    tableName: "vehicle_movements",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["movement_dates", "sections", "basis", "comment"],
  }),
  createPatchMutationPlan({
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    resource: "fleet",
    action: "approve",
    databaseAction: "transition-vehicle-movement",
    tableName: "vehicle_movements",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "service-vehicle",
    workspaceId: "fleet",
    resource: "fleet",
    action: "edit",
    databaseAction: "patch-service-vehicle-record",
    tableName: "service_vehicle_records",
    statusColumn: "status",
    allowedFieldGroups: ["maintenance", "insurance", "tires", "repair", "reminder"],
  }),
  createPatchMutationPlan({
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    resource: "common-processes",
    action: "edit",
    databaseAction: "patch-overtime-request",
    tableName: "common_overtime_requests",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["employee", "hours", "basis", "reason"],
  }),
  createPatchMutationPlan({
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    resource: "common-processes",
    action: "approve",
    databaseAction: "transition-overtime-request",
    tableName: "common_overtime_requests",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    resource: "common-processes",
    action: "edit",
    databaseAction: "patch-business-trip",
    tableName: "common_business_trips",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["route", "period", "tasks", "costs", "report"],
  }),
  createPatchMutationPlan({
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    resource: "common-processes",
    action: "approve",
    databaseAction: "transition-business-trip",
    tableName: "common_business_trips",
    statusColumn: "status",
    scopeColumns: { section_id: "section_id" },
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "access-matrix",
    workspaceId: "admin",
    resource: "admin",
    action: "edit",
    databaseAction: "patch-access-grant",
    tableName: "access_matrix_grants",
    statusColumn: "status",
    allowedFieldGroups: ["capabilities", "scope", "reason"],
  }),
  createPatchMutationPlan({
    moduleId: "access-matrix",
    workspaceId: "admin",
    resource: "admin",
    action: "delete",
    databaseAction: "delete-access-grant",
    tableName: "access_matrix_grants",
    statusColumn: "status",
    allowedFieldGroups: ["status"],
  }),
  createPatchMutationPlan({
    moduleId: "access-matrix",
    workspaceId: "admin",
    resource: "admin",
    action: "admin",
    databaseAction: "admin-access-grant",
    tableName: "access_matrix_grants",
    statusColumn: "status",
    allowedFieldGroups: ["capabilities", "scope", "reason", "status"],
  }),
];
