import type { ModuleListQueryPlan } from "./moduleListQueryPlans";

export const moduleListQueryPlans: ModuleListQueryPlan[] = [
  {
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    databaseAction: "list-shift-reports",
    tableName: "mining_shift_reports",
    selectColumns: ["id", "version", "report_date", "section_id", "shift", "status", "report_number", "updated_at"],
    filterColumns: {
      date: "report_date",
      section_id: "section_id",
      shift: "shift",
      status: "status",
    },
    searchColumns: ["report_number", "excavator_name", "work_type"],
    sortColumns: {
      date: "report_date",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "mining-operational-accounting",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    databaseAction: "list-operational-accounting",
    tableName: "mining_operational_accounting_rows",
    selectColumns: ["id", "version", "report_date", "section_id", "shift", "excavator_name", "vehicle_number", "final_volume", "updated_at"],
    filterColumns: {
      date: "report_date",
      section_id: "section_id",
      shift: "shift",
    },
    searchColumns: ["excavator_name", "vehicle_number", "work_type"],
    sortColumns: {
      date: "report_date",
      shift: "shift",
      updated_at: "updated_at",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    resource: "taxation",
    databaseAction: "list-waybills",
    tableName: "taxation_waybills",
    selectColumns: ["id", "version", "work_date", "section_id", "shift", "waybill_number", "driver_id", "driver_name", "vehicle_id", "vehicle_number", "status"],
    filterColumns: {
      date: "work_date",
      section_id: "section_id",
      shift: "shift",
      driver_id: "driver_id",
      vehicle_id: "vehicle_id",
      status: "status",
    },
    searchColumns: ["waybill_number", "driver_name", "vehicle_number"],
    sortColumns: {
      date: "work_date",
      status: "status",
      driver: "driver_name",
      vehicle: "vehicle_number",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    resource: "taxation",
    databaseAction: "list-fuel-periods",
    tableName: "fuel_accounting_periods",
    selectColumns: ["id", "version", "section_id", "period_id", "period_label", "status", "supplier_invoice_number", "contractor_id", "contractor_name", "updated_at"],
    filterColumns: {
      section_id: "section_id",
      period_id: "period_id",
      status: "status",
      contractor_id: "contractor_id",
    },
    searchColumns: ["period_label", "supplier_invoice_number", "contractor_name"],
    sortColumns: {
      period: "period_id",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "period", direction: "desc" },
  },
  {
    moduleId: "smts-vehicle-cards",
    workspaceId: "smts-gps",
    resource: "smts",
    databaseAction: "list-vehicle-cards",
    tableName: "smts_vehicle_cards",
    selectColumns: ["id", "version", "section_id", "vehicle_id", "vehicle_number", "terminal_id", "imei", "wialon_id", "status", "updated_at"],
    filterColumns: {
      section_id: "section_id",
      vehicle_id: "vehicle_id",
      terminal_id: "terminal_id",
      status: "status",
    },
    searchColumns: ["vehicle_number", "imei", "wialon_id"],
    sortColumns: {
      vehicle: "vehicle_number",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "vehicle", direction: "asc" },
  },
  {
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    resource: "smts",
    databaseAction: "list-fuel-drain-events",
    tableName: "smts_fuel_drain_events",
    selectColumns: ["id", "version", "event_date", "section_id", "vehicle_id", "vehicle_number", "status", "location_name", "updated_at"],
    filterColumns: {
      date: "event_date",
      section_id: "section_id",
      vehicle_id: "vehicle_id",
      status: "status",
    },
    searchColumns: ["vehicle_number", "location_name", "check_comment"],
    sortColumns: {
      date: "event_date",
      status: "status",
      vehicle: "vehicle_number",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    resource: "fleet",
    databaseAction: "list-vehicle-movements",
    tableName: "vehicle_movements",
    selectColumns: ["id", "version", "section_id", "vehicle_id", "vehicle_number", "status", "updated_at"],
    filterColumns: {
      section_id: "section_id",
      vehicle_id: "vehicle_id",
      status: "status",
    },
    searchColumns: ["vehicle_number", "basis", "reason"],
    sortColumns: {
      updated_at: "updated_at",
      status: "status",
      vehicle: "vehicle_number",
    },
    defaultSort: { field: "updated_at", direction: "desc" },
  },
  {
    moduleId: "service-vehicle",
    workspaceId: "fleet",
    resource: "fleet",
    databaseAction: "list-service-vehicle-records",
    tableName: "service_vehicle_records",
    selectColumns: ["id", "version", "vehicle_id", "vehicle_number", "record_type", "status", "updated_at"],
    filterColumns: {
      vehicle_id: "vehicle_id",
      status: "status",
    },
    searchColumns: ["vehicle_number", "document_number", "service_name"],
    sortColumns: {
      updated_at: "updated_at",
      status: "status",
      vehicle: "vehicle_number",
    },
    defaultSort: { field: "updated_at", direction: "desc" },
  },
  {
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    resource: "common-processes",
    databaseAction: "list-overtime-requests",
    tableName: "common_overtime_requests",
    selectColumns: ["id", "version", "work_date", "section_id", "employee_id", "employee_name", "status", "updated_at"],
    filterColumns: {
      date: "work_date",
      section_id: "section_id",
      status: "status",
    },
    searchColumns: ["employee_name", "position_title", "reason"],
    sortColumns: {
      date: "work_date",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    resource: "common-processes",
    databaseAction: "list-business-trips",
    tableName: "common_business_trips",
    selectColumns: ["id", "version", "start_date", "section_id", "employee_id", "employee_name", "status", "updated_at"],
    filterColumns: {
      date: "start_date",
      section_id: "section_id",
      status: "status",
    },
    searchColumns: ["employee_name", "route", "trip_goal"],
    sortColumns: {
      date: "start_date",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "prepared-reports",
    workspaceId: "reports",
    resource: "reports",
    databaseAction: "list-prepared-report-aggregates",
    tableName: "prepared_report_aggregates",
    selectColumns: ["id", "report_date", "section_id", "report_type", "status", "prepared_at"],
    filterColumns: {
      date: "report_date",
      section_id: "section_id",
      status: "status",
    },
    searchColumns: ["report_type", "section_name"],
    sortColumns: {
      date: "report_date",
      status: "status",
      updated_at: "updated_at",
    },
    defaultSort: { field: "date", direction: "desc" },
  },
  {
    moduleId: "access-matrix",
    workspaceId: "admin",
    resource: "admin",
    databaseAction: "list-access-grants",
    tableName: "access_matrix_grants",
    selectColumns: ["id", "version", "user_id", "role_id", "section_id", "module_id", "status", "updated_at"],
    filterColumns: {
      section_id: "section_id",
      status: "status",
    },
    searchColumns: ["user_id", "role_id", "module_id"],
    sortColumns: {
      updated_at: "updated_at",
      status: "status",
      user: "user_id",
      role: "role_id",
    },
    defaultSort: { field: "updated_at", direction: "desc" },
  },
];
