import type { ModuleDetailQueryPlan } from "./moduleDetailQueryPlans";

function createDetailQueryPlan(input: Omit<
  ModuleDetailQueryPlan,
  "idColumn" | "requiresId" | "maxRows"
> & { idColumn?: string }) {
  return {
    idColumn: "id",
    requiresId: true,
    maxRows: 1,
    ...input,
  } satisfies ModuleDetailQueryPlan;
}

export const moduleDetailQueryPlans: ModuleDetailQueryPlan[] = [
  createDetailQueryPlan({
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    databaseAction: "get-shift-report",
    tableName: "mining_shift_reports",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "version", "report_date", "section_id", "shift", "status", "updated_at", "updated_by"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "mining-operational-accounting",
    workspaceId: "mining-dispatch",
    resource: "dispatch",
    databaseAction: "get-operational-accounting-row",
    tableName: "mining_operational_accounting_rows",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "version", "report_date", "section_id", "shift", "status", "final_volume", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    resource: "taxation",
    databaseAction: "get-waybill",
    tableName: "taxation_waybills",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id", driver_id: "driver_id", vehicle_id: "vehicle_id" },
    selectColumns: ["id", "version", "work_date", "section_id", "shift", "driver_id", "vehicle_id", "status"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    resource: "taxation",
    databaseAction: "get-fuel-period",
    tableName: "fuel_accounting_periods",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id", period_id: "period_id" },
    selectColumns: ["id", "version", "section_id", "period_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "smts-vehicle-cards",
    workspaceId: "smts-gps",
    resource: "smts",
    databaseAction: "get-vehicle-card",
    tableName: "smts_vehicle_cards",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id", vehicle_id: "vehicle_id", terminal_id: "terminal_id" },
    selectColumns: ["id", "version", "section_id", "vehicle_id", "terminal_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    resource: "smts",
    databaseAction: "get-fuel-drain-event",
    tableName: "smts_fuel_drain_events",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id", vehicle_id: "vehicle_id" },
    selectColumns: ["id", "version", "event_date", "section_id", "vehicle_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    resource: "fleet",
    databaseAction: "get-vehicle-movement",
    tableName: "vehicle_movements",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id", vehicle_id: "vehicle_id" },
    selectColumns: ["id", "version", "section_id", "vehicle_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "service-vehicle",
    workspaceId: "fleet",
    resource: "fleet",
    databaseAction: "get-service-vehicle-record",
    tableName: "service_vehicle_records",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { vehicle_id: "vehicle_id" },
    selectColumns: ["id", "version", "vehicle_id", "record_type", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    resource: "common-processes",
    databaseAction: "get-overtime-request",
    tableName: "common_overtime_requests",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "version", "work_date", "section_id", "employee_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    resource: "common-processes",
    databaseAction: "get-business-trip",
    tableName: "common_business_trips",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "version", "start_date", "section_id", "employee_id", "status", "updated_at"],
    returnsVersion: true,
  }),
  createDetailQueryPlan({
    moduleId: "prepared-reports",
    workspaceId: "reports",
    resource: "reports",
    databaseAction: "get-prepared-report",
    tableName: "prepared_report_aggregates",
    statusColumn: "status",
    updatedAtColumn: "prepared_at",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "report_date", "section_id", "report_type", "status", "aggregate_payload", "prepared_at"],
    returnsVersion: false,
  }),
  createDetailQueryPlan({
    moduleId: "access-matrix",
    workspaceId: "admin",
    resource: "admin",
    databaseAction: "get-access-grant",
    tableName: "access_matrix_grants",
    versionColumn: "version",
    statusColumn: "status",
    updatedAtColumn: "updated_at",
    updatedByColumn: "updated_by",
    scopeColumns: { section_id: "section_id" },
    selectColumns: ["id", "version", "user_id", "role_id", "section_id", "module_id", "status", "updated_at"],
    returnsVersion: true,
  }),
];
