import type { ModuleDataRouteContract } from "./moduleDataRoutes";

export const moduleDataRouteContracts: ModuleDataRouteContract[] = [
  {
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "dispatch",
    actions: {
      list: "list-shift-reports",
      open: "get-shift-report",
      create: "create-shift-report",
      edit: "patch-shift-report",
      approve: "transition-shift-report",
      export: "export-shift-report",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Future shift reports stay inside the shared database router.",
  },
  {
    moduleId: "mining-operational-accounting",
    workspaceId: "mining-dispatch",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "dispatch",
    actions: {
      list: "list-operational-accounting",
      open: "get-operational-accounting-row",
      edit: "patch-operational-accounting-row",
      export: "export-operational-accounting",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Operational accounting reads prepared rows and patch-adjusts correction layers.",
  },
  {
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "taxation",
    actions: {
      list: "list-waybills",
      open: "get-waybill",
      create: "create-waybill",
      edit: "patch-waybill",
      approve: "transition-waybill",
      export: "export-waybills",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Waybill issue and repeat print actions use one resource with preflight.",
  },
  {
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "taxation",
    actions: {
      list: "list-fuel-periods",
      open: "get-fuel-period",
      create: "create-fuel-period",
      edit: "patch-fuel-period",
      approve: "transition-fuel-period",
      export: "export-fuel-period",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Fuel periods, supplier invoices and contractor debts share the taxation resource.",
  },
  {
    moduleId: "smts-vehicle-cards",
    workspaceId: "smts-gps",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "smts",
    actions: {
      list: "list-vehicle-cards",
      open: "get-vehicle-card",
      edit: "patch-vehicle-card",
      export: "export-vehicle-cards",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "SMTS card edits stay in the shared router and write equipment history separately.",
  },
  {
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "smts",
    actions: {
      list: "list-fuel-drain-events",
      open: "get-fuel-drain-event",
      edit: "patch-fuel-drain-event",
      approve: "transition-fuel-drain-event",
      export: "export-fuel-drain-events",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "GPS/Wialon event checks require bounded period preflight before the shared router runs.",
  },
  {
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "fleet",
    actions: {
      list: "list-vehicle-movements",
      open: "get-vehicle-movement",
      create: "create-vehicle-movement",
      edit: "patch-vehicle-movement",
      approve: "transition-vehicle-movement",
      export: "export-vehicle-movements",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Vehicle movement documents update section history through one fleet resource.",
  },
  {
    moduleId: "service-vehicle",
    workspaceId: "fleet",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "fleet",
    actions: {
      list: "list-service-vehicle-records",
      open: "get-service-vehicle-record",
      create: "create-service-vehicle-record",
      edit: "patch-service-vehicle-record",
      export: "export-service-vehicle-records",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Service vehicle maintenance, insurance and repair records stay under the fleet resource.",
  },
  {
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "common-processes",
    actions: {
      list: "list-overtime-requests",
      open: "get-overtime-request",
      create: "create-overtime-request",
      edit: "patch-overtime-request",
      approve: "transition-overtime-request",
      export: "export-overtime-requests",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Overtime requests use the common-processes resource and workflow preflight.",
  },
  {
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "common-processes",
    actions: {
      list: "list-business-trips",
      open: "get-business-trip",
      create: "create-business-trip",
      edit: "patch-business-trip",
      approve: "transition-business-trip",
      export: "export-business-trips",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Business trips and installer task lists stay in the shared common-processes resource.",
  },
  {
    moduleId: "prepared-reports",
    workspaceId: "reports",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "reports",
    actions: {
      list: "list-prepared-report-aggregates",
      open: "get-prepared-report",
      export: "create-report-export-request",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Reports read prepared aggregates and queue export requests through one resource.",
  },
  {
    moduleId: "access-matrix",
    workspaceId: "admin",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "admin",
    actions: {
      list: "list-access-grants",
      open: "get-access-grant",
      create: "create-access-grant",
      edit: "patch-access-grant",
      delete: "delete-access-grant",
      admin: "admin-access-grant",
      export: "export-access-grants",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "Access matrix remains part of the single admin/database router path.",
  },
  {
    moduleId: "ai-on-demand",
    workspaceId: "ai-assistant",
    endpoint: "/api/database",
    routeKind: "single-database-router",
    resource: "ai-assistant",
    actions: {
      open: "load-ai-context",
      list: "list-ai-request-artifacts",
    },
    requiresPreflight: true,
    implementationStatus: "planned",
    notes: "AI artifacts are requested on demand and do not run a separate service.",
  },
];
