import type { ModulePersistenceContract } from "./persistenceContracts";

export const modulePersistenceContracts: ModulePersistenceContract[] = [
  {
    moduleId: "mining-shift-reports",
    workspaceId: "mining-dispatch",
    primaryEntities: ["mining_shift_reports", "mining_shift_report_lines"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["date", "section_id", "shift", "status", "vehicle_id"],
    historyEntities: ["change_history_entries"],
    notes: "Shift reports and lines must keep original trips, status workflow and field history.",
  },
  {
    moduleId: "mining-operational-accounting",
    workspaceId: "mining-dispatch",
    primaryEntities: ["mining_operational_accounting_rows", "mining_survey_adjustments"],
    writeMode: "versioned-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    aggregateOnly: true,
    requiredIndexes: ["date", "section_id", "shift", "status", "vehicle_id"],
    historyEntities: ["change_history_entries"],
    notes: "Operational accounting is prepared from accepted reports; survey adjustments patch the correction layer.",
  },
  {
    moduleId: "taxation-waybills",
    workspaceId: "taxation",
    primaryEntities: ["waybills", "waybill_print_events"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["date", "section_id", "shift", "driver_id", "vehicle_id", "status"],
    historyEntities: ["change_history_entries"],
    notes: "Waybill issue avoids duplicates and stores repeat print events separately.",
  },
  {
    moduleId: "taxation-fuel-periods",
    workspaceId: "taxation",
    primaryEntities: [
      "fuel_accounting_periods",
      "fuel_movements",
      "fuel_transfer_acts",
      "fuel_reconciliation_acts",
      "supplier_fuel_invoices",
      "contractor_fuel_debts",
    ],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["section_id", "period_id", "status", "contractor_id", "vehicle_id"],
    historyEntities: ["change_history_entries"],
    notes: "Fuel periods are scoped by 1C period; truck balances are derived from movements and invoices.",
  },
  {
    moduleId: "smts-vehicle-cards",
    workspaceId: "smts-gps",
    primaryEntities: ["smts_vehicle_cards", "smts_terminals", "smts_sim_cards", "smts_equipment_events"],
    writeMode: "versioned-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["section_id", "vehicle_id", "terminal_id", "status", "updated_at"],
    historyEntities: ["change_history_entries", "smts_equipment_events"],
    notes: "Terminal, SIM and vehicle card lifecycle is stored as versioned state plus append-only equipment events.",
  },
  {
    moduleId: "smts-fuel-drains",
    workspaceId: "smts-gps",
    primaryEntities: ["smts_fuel_drain_events"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["date", "section_id", "vehicle_id", "status"],
    historyEntities: ["change_history_entries"],
    notes: "Fuel drain checks keep Wialon events bounded by period and store verification status changes.",
  },
  {
    moduleId: "fleet-movements",
    workspaceId: "fleet",
    primaryEntities: ["vehicle_movements", "vehicle_section_history"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["section_id", "vehicle_id", "status", "date"],
    historyEntities: ["change_history_entries", "vehicle_section_history"],
    notes: "Vehicle section must change through movement documents and history, not direct card overwrite.",
  },
  {
    moduleId: "service-vehicle",
    workspaceId: "fleet",
    primaryEntities: [
      "service_vehicle_cards",
      "service_vehicle_maintenance",
      "service_vehicle_insurance",
      "service_vehicle_tires",
      "service_vehicle_repairs",
    ],
    writeMode: "versioned-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["vehicle_id", "status", "updated_at"],
    historyEntities: ["change_history_entries"],
    notes: "Service vehicle maintenance, insurance, tire and repair records must be edited by field patches.",
  },
  {
    moduleId: "common-overtime",
    workspaceId: "common-processes",
    primaryEntities: ["overtime_requests"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["date", "section_id", "status", "updated_at"],
    historyEntities: ["change_history_entries"],
    notes: "Overtime and substitution requests keep approval history and are listed by bounded periods.",
  },
  {
    moduleId: "common-business-trips",
    workspaceId: "common-processes",
    primaryEntities: ["business_trips", "business_trip_tasks"],
    writeMode: "workflow-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["date", "section_id", "status", "updated_at"],
    historyEntities: ["change_history_entries"],
    notes: "Business trips and installer task lists are workflow documents with field history.",
  },
  {
    moduleId: "prepared-reports",
    workspaceId: "reports",
    primaryEntities: ["prepared_report_aggregates", "report_export_requests"],
    writeMode: "queued-export",
    versioned: false,
    patchOnly: false,
    writesChangeHistory: false,
    aggregateOnly: true,
    exportOnDemand: true,
    requiredIndexes: ["date", "section_id", "status", "created_at"],
    notes: "Reports read prepared aggregates and create export requests on demand instead of recalculating in the browser.",
  },
  {
    moduleId: "access-matrix",
    workspaceId: "admin",
    primaryEntities: ["access_matrix_grants"],
    writeMode: "versioned-patch",
    versioned: true,
    patchOnly: true,
    writesChangeHistory: true,
    requiredIndexes: ["section_id", "status", "updated_at"],
    historyEntities: ["change_history_entries"],
    notes: "Access grants are administrative, versioned and auditable changes.",
  },
  {
    moduleId: "ai-on-demand",
    workspaceId: "ai-assistant",
    primaryEntities: ["ai_request_artifacts", "ai_task_context"],
    writeMode: "on-demand",
    versioned: false,
    patchOnly: false,
    writesChangeHistory: false,
    exportOnDemand: false,
    requiredIndexes: ["created_at", "updated_at"],
    notes: "AI artifacts are created on request and must not run continuous background analysis.",
  },
];
