import type { AiAssistantDataset, AiAssistantRole } from "@/features/ai-assistant/types";

export const defaultAiAssistantRole: AiAssistantRole = "supervisor";

export const defaultAiAssistantDataset: AiAssistantDataset = {
  currentWorkDate: "2026-04-24",
  currentDateTime: "2026-04-24T16:00",
  chatMessages: [
    {
      id: "chat-001",
      role: "system",
      author: "Система",
      text: "Чат используется для вопросов, анализа и подготовки черновиков. Критические действия автоматически попадают во вкладку Одобрения.",
      createdAt: "2026-04-24T15:05:00.000Z",
    },
    {
      id: "chat-002",
      role: "user",
      author: "Начальник диспетчерской службы",
      text: "Проверь причину невыполнения суточного плана по Аксу и подготовь формулировку.",
      createdAt: "2026-04-24T15:15:00.000Z",
      linkedTaskId: "ai-task-001",
    },
    {
      id: "chat-003",
      role: "assistant",
      author: "AI-ассистент",
      text: "Найдено отставание. Я подготовил черновик причины и поместил действие в Одобрения, потому что текст пойдет в официальный отчет.",
      createdAt: "2026-04-24T15:20:00.000Z",
      linkedTaskId: "ai-task-001",
    },
  ],
  approvalActions: [
    {
      id: "approval-001",
      taskId: "ai-task-001",
      title: "Подтвердить причину для отчета Аксу",
      actionType: "ask-assistant",
      risk: "critical",
      status: "required",
      targetConnector: "ai-api",
      targetLabel: "Отчетность Аксу",
      draftText: "Основной вклад в отставание дают простои транспортировочной техники и погодные ограничения.",
      requestedBy: "AI-ассистент",
      createdAt: "2026-04-24T15:20:00.000Z",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "approval-002",
      taskId: "ai-task-002",
      title: "Отправить WhatsApp подрядчику Qaz Trucks",
      actionType: "send-whatsapp",
      risk: "critical",
      status: "required",
      targetConnector: "whatsapp",
      targetLabel: "Qaz Trucks",
      draftText: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      requestedBy: "Диспетчер",
      createdAt: "2026-04-24T13:50:00.000Z",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
    {
      id: "approval-003",
      taskId: "ai-task-003",
      title: "Подготовить документ по маркзамеру",
      actionType: "prepare-document",
      risk: "critical",
      status: "approved",
      targetConnector: "documentolog",
      targetLabel: "Маркзамер за апрель",
      draftText: "Собрать последний маркзамер и недостающий оперучет до рабочей даты.",
      requestedBy: "ПТО",
      approver: "Начальник диспетчерской службы",
      createdAt: "2026-04-24T11:30:00.000Z",
      updatedAt: "2026-04-24T12:10:00.000Z",
    },
  ],
  tasks: [
    {
      id: "ai-task-001",
      title: "Проверить причину невыполнения суточного плана по Аксу",
      kind: "ask",
      status: "needs-approval",
      channel: "app",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "report",
        id: "report-aksu-2026-04-24",
        label: "Отчетность Аксу за 24.04.2026",
      },
      prompt: "Сопоставить план, факт, ремонты и простои по участку Аксу.",
      resultDraft: "Основной вклад в отставание дают простои транспортировочной техники и погодные ограничения.",
      evidenceIds: ["ev-001", "ev-002"],
      approvalStatus: "required",
      approvalActionId: "approval-001",
      owner: "Начальник диспетчерской службы",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "ai-task-002",
      title: "Подготовить сообщение подрядчику по GPS",
      kind: "draft-message",
      status: "draft",
      channel: "whatsapp",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "vehicle",
        id: "vehicle-gps-qaz-trucks",
        label: "Техника Qaz Trucks без активности GPS",
      },
      prompt: "Сформировать корректное уведомление о необходимости проверить GPS.",
      resultDraft: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      evidenceIds: ["ev-003"],
      approvalStatus: "required",
      approvalActionId: "approval-002",
      owner: "Диспетчер",
      updatedAt: "2026-04-24T13:45:00.000Z",
    },
    {
      id: "ai-task-003",
      title: "Собрать материалы для справки по маркзамеру",
      kind: "summarize",
      status: "queued",
      channel: "documentolog",
      sourceEntity: {
        type: "pto",
        id: "survey-2026-04",
        label: "Маркшейдерский замер за апрель",
      },
      prompt: "Собрать последние замеры и недостающий оперучет до рабочей даты.",
      evidenceIds: ["ev-004"],
      approvalStatus: "approved",
      approvalActionId: "approval-003",
      owner: "ПТО",
      updatedAt: "2026-04-24T11:30:00.000Z",
    },
  ],
  notifications: [
    {
      id: "ai-note-001",
      title: "Напоминание о согласовании причины",
      channel: "app",
      status: "queued",
      target: "Руководитель участка Аксу",
      body: "Нужно подтвердить причину отставания перед отправкой отчета заказчику.",
      approvalStatus: "not-required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-001",
      plannerItemId: "plan-ai-001",
      updatedAt: "2026-04-24T15:25:00.000Z",
    },
    {
      id: "ai-note-002",
      title: "Черновик WhatsApp подрядчику",
      channel: "whatsapp",
      status: "draft",
      target: "Qaz Trucks",
      body: "Просим проверить GPS и подтвердить готовность техники к смене.",
      approvalStatus: "required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-002",
      plannerItemId: "plan-ai-002",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
  ],
  plannerItems: [
    {
      id: "plan-ai-001",
      title: "Проверить причину невыполнения плана по Аксу",
      description: "Сформировать черновик причины и вывести действие на согласование.",
      plannedDate: "2026-04-24",
      plannedTime: "15:00",
      status: "needs-decision",
      priority: "high",
      owner: "Начальник диспетчерской службы",
      target: "Руководитель участка Аксу",
      channel: "app",
      actionType: "update-report-reason",
      preparedText: "Проверить причины невыполнения и подготовить текст для отчета.",
      requireApproval: true,
      linkedTaskId: "ai-task-001",
      linkedNotificationId: "ai-note-001",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "plan-ai-002",
      title: "Подготовить уведомление по GPS подрядчика",
      description: "Собрать технику без сигнала GPS и подготовить сообщение подрядчику.",
      plannedDate: "2026-04-24",
      plannedTime: "13:30",
      status: "needs-decision",
      priority: "normal",
      owner: "Диспетчер",
      target: "Qaz Trucks",
      channel: "whatsapp",
      actionType: "send-whatsapp",
      preparedText: "Просим проверить GPS и подтвердить готовность техники к смене.",
      requireApproval: true,
      linkedTaskId: "ai-task-002",
      linkedNotificationId: "ai-note-002",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
    {
      id: "plan-ai-003",
      title: "Проверить недостающий оперучет после маркзамера",
      description: "На следующую рабочую дату сверить маркзамер и оперучет перед отчетом.",
      plannedDate: "2026-04-25",
      plannedTime: "10:00",
      status: "planned",
      priority: "normal",
      owner: "ПТО",
      target: "ПТО",
      channel: "app",
      actionType: "ask-assistant",
      preparedText: "Сверить маркзамер и оперучет перед отчетом.",
      requireApproval: false,
      comment: "Появится в Задачах 25.04.2026.",
      updatedAt: "2026-04-24T16:10:00.000Z",
    },
  ],
  integrations: [
    {
      key: "ai-api",
      title: "AI API",
      status: "planned",
      mode: "read-write",
      description: "Серверный обработчик запросов, черновиков и анализа причин.",
      requiredScopes: ["ai.chat.read", "ai.chat.write", "ai.context.dispatcher.read"],
    },
    {
      key: "whatsapp",
      title: "WhatsApp",
      status: "planned",
      mode: "write",
      description: "Черновики и отправка сообщений после согласования.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
    },
    {
      key: "documentolog",
      title: "Documentolog",
      status: "planned",
      mode: "read-write",
      description: "Поиск документов, создание черновиков и маршрутов согласования.",
      requiredScopes: ["ai.documentolog.read", "ai.documentolog.write"],
    },
    {
      key: "mail",
      title: "Почта",
      status: "planned",
      mode: "read-write",
      description: "Черновики писем, чтение согласованных входящих и контроль отправки.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
    },
    {
      key: "calendar",
      title: "Календарь",
      status: "planned",
      mode: "read-write",
      description: "События, напоминания, сроки согласований и сменные задачи.",
      requiredScopes: ["ai.calendar.read", "ai.calendar.write"],
    },
    {
      key: "push",
      title: "Push-уведомления",
      status: "disabled",
      mode: "write",
      description: "Внутренние уведомления пользователям после включения ролей.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
    },
    {
      key: "knowledge-base",
      title: "База знаний",
      status: "planned",
      mode: "read",
      description: "Регламенты, инструкции, шаблоны причин и история решений.",
      requiredScopes: ["ai.knowledge.read"],
    },
  ],
  knowledgeSources: [
    {
      id: "kb-001",
      title: "Правила заполнения причин невыполнения плана",
      source: "manual",
      access: "internal",
      owner: "Диспетчерская служба",
      updatedAt: "2026-04-23T10:00:00.000Z",
      tags: ["отчетность", "причины", "план"],
    },
    {
      id: "kb-002",
      title: "Регламент согласования сообщений подрядчикам",
      source: "file",
      access: "restricted",
      owner: "Администрация",
      updatedAt: "2026-04-20T09:30:00.000Z",
      tags: ["подрядчики", "whatsapp", "согласование"],
    },
    {
      id: "kb-003",
      title: "Порядок учета маркзамера и оперучета",
      source: "system",
      access: "internal",
      owner: "ПТО",
      updatedAt: "2026-04-18T08:15:00.000Z",
      tags: ["ПТО", "замер", "оперучет"],
    },
  ],
  evidence: [
    {
      id: "ev-001",
      source: {
        type: "dispatch-summary",
        id: "summary-2026-04-24",
        label: "Сводка за сутки",
      },
      summary: "Зафиксирован ремонт транспортировочной техники и простой ДСК.",
      confidence: 0.78,
    },
    {
      id: "ev-002",
      source: {
        type: "report",
        id: "report-aksu-2026-04-24",
        label: "План-факт Аксу",
      },
      summary: "Отклонение по факту ниже плана на рабочую дату.",
      confidence: 0.84,
    },
    {
      id: "ev-003",
      source: {
        type: "vehicle",
        id: "fleet-qaz-trucks-gps",
        label: "GPS подрядчика",
      },
      summary: "Часть техники подрядчика не передает последние координаты.",
      confidence: 0.72,
    },
    {
      id: "ev-004",
      source: {
        type: "pto",
        id: "survey-oper-april",
        label: "Замер и оперучет",
      },
      summary: "Последний маркзамер нужно дополнить оперучетом до текущей рабочей даты.",
      confidence: 0.81,
    },
  ],
  auditEvents: [
    {
      id: "audit-001",
      timestamp: "2026-04-24T15:20:00.000Z",
      actor: "Начальник диспетчерской службы",
      role: "supervisor",
      action: "Создан черновик анализа",
      connector: "ai-api",
      target: "Отчетность Аксу",
      status: "success",
      summary: "Сформирован черновик причины с двумя источниками.",
    },
    {
      id: "audit-002",
      timestamp: "2026-04-24T13:50:00.000Z",
      actor: "Диспетчер",
      role: "operator",
      action: "Подготовлен черновик сообщения",
      connector: "whatsapp",
      target: "Qaz Trucks",
      status: "success",
      summary: "Отправка заблокирована до согласования.",
    },
    {
      id: "audit-003",
      timestamp: "2026-04-24T11:30:00.000Z",
      actor: "ПТО",
      role: "operator",
      action: "Запрошена сводка по замеру",
      connector: "documentolog",
      target: "Маркзамер за апрель",
      status: "blocked",
      summary: "Интеграция еще не подключена, задача оставлена в очереди.",
    },
  ],
};
