import type { AiAssistantDataset, AiAssistantRole } from "@/features/ai-assistant/types";

export const defaultAiAssistantRole: AiAssistantRole = "supervisor";

export const defaultAiAssistantDataset: AiAssistantDataset = {
  currentWorkDate: "2026-04-24",
  currentDateTime: "2026-04-24T16:00",
  agents: [
    {
      id: "agent-main",
      title: "Главный ассистент",
      role: "main-assistant",
      description: "Координирует чат, задачи, одобрения и передачу действий внутренним агентам.",
      status: "active",
      permissions: ["ai.chat.read", "ai.chat.write", "ai.context.dispatcher.read", "ai.knowledge.read"],
      allowedActions: ["ask-assistant", "draft", "prepare-document"],
      blockedActions: ["send-whatsapp", "send-mail", "start-documentolog", "delete-data"],
      requiredConnectors: ["ai-api", "knowledge-base"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:45:00.000Z",
    },
    {
      id: "agent-whatsapp",
      title: "WhatsApp-монитор",
      role: "whatsapp-monitor",
      description: "Находит поручения и события в рабочих группах, но не отправляет сообщения без решения пользователя.",
      status: "planned",
      permissions: ["ai.external.draft", "ai.external.send"],
      allowedActions: ["draft", "send-whatsapp", "create-business-trip"],
      blockedActions: ["delete-data", "start-documentolog"],
      requiredConnectors: ["whatsapp"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:46:00.000Z",
    },
    {
      id: "agent-task-planner",
      title: "Агент задач",
      role: "task-planner",
      description: "Следит за сроками, повторяющимися задачами и выводит действия на текущую рабочую дату.",
      status: "active",
      permissions: ["ai.chat.read", "ai.chat.write", "ai.calendar.read"],
      allowedActions: ["ask-assistant", "create-calendar-event", "create-push-notification"],
      blockedActions: ["send-mail", "send-whatsapp", "delete-data"],
      requiredConnectors: ["calendar", "push"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:47:00.000Z",
    },
    {
      id: "agent-document",
      title: "Агент документов",
      role: "document-agent",
      description: "Готовит служебные записки, письма и отчеты как черновики.",
      status: "planned",
      permissions: ["ai.documentolog.read", "ai.documentolog.write", "ai.external.draft"],
      allowedActions: ["prepare-document", "start-documentolog"],
      blockedActions: ["send-whatsapp", "delete-data"],
      requiredConnectors: ["documentolog"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:48:00.000Z",
    },
    {
      id: "agent-mail",
      title: "Агент почты",
      role: "mail-agent",
      description: "Готовит письма и отслеживает согласованные входящие сообщения.",
      status: "planned",
      permissions: ["ai.external.draft", "ai.external.send"],
      allowedActions: ["send-mail", "draft"],
      blockedActions: ["delete-data", "start-documentolog"],
      requiredConnectors: ["mail"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:49:00.000Z",
    },
    {
      id: "agent-calendar",
      title: "Агент календаря",
      role: "calendar-agent",
      description: "Готовит события, дедлайны и напоминания, связанные с задачами.",
      status: "planned",
      permissions: ["ai.calendar.read", "ai.calendar.write"],
      allowedActions: ["create-calendar-event"],
      blockedActions: ["send-mail", "send-whatsapp", "delete-data"],
      requiredConnectors: ["calendar"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:50:00.000Z",
    },
    {
      id: "agent-documentolog",
      title: "Агент Documentolog",
      role: "documentolog-agent",
      description: "Передает официальные документы в Documentolog только после подтверждения на сайте.",
      status: "planned",
      permissions: ["ai.documentolog.read", "ai.documentolog.write"],
      allowedActions: ["start-documentolog", "prepare-document"],
      blockedActions: ["send-whatsapp", "delete-data"],
      requiredConnectors: ["documentolog"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:51:00.000Z",
    },
    {
      id: "agent-mentor",
      title: "Агент-наставник",
      role: "mentor-agent",
      description: "Подсказывает пользователям, как оформить действие без потери бизнес-смысла.",
      status: "planned",
      permissions: ["ai.chat.read", "ai.chat.write", "ai.knowledge.read"],
      allowedActions: ["ask-assistant", "draft"],
      blockedActions: ["send-mail", "send-whatsapp", "delete-data"],
      requiredConnectors: ["knowledge-base"],
      requiresUserApproval: false,
      updatedAt: "2026-04-24T15:52:00.000Z",
    },
    {
      id: "agent-development",
      title: "Агент развития / ТЗ / Codex",
      role: "development-agent",
      description: "Переводит идеи развития в ТЗ, критерии приемки и промты для Codex.",
      status: "active",
      permissions: ["ai.chat.read", "ai.chat.write", "ai.knowledge.read"],
      allowedActions: ["draft", "ask-assistant"],
      blockedActions: ["send-mail", "send-whatsapp", "delete-data", "start-documentolog"],
      requiredConnectors: ["ai-api", "knowledge-base"],
      requiresUserApproval: true,
      updatedAt: "2026-04-24T15:53:00.000Z",
    },
    {
      id: "agent-qa",
      title: "QA-агент",
      role: "qa-agent",
      description: "Проверяет сценарии, риски регрессий и полноту критериев приемки.",
      status: "planned",
      permissions: ["ai.chat.read", "ai.knowledge.read", "ai.audit.read"],
      allowedActions: ["ask-assistant", "draft"],
      blockedActions: ["send-mail", "send-whatsapp", "delete-data"],
      requiredConnectors: ["knowledge-base"],
      requiresUserApproval: false,
      updatedAt: "2026-04-24T15:54:00.000Z",
    },
    {
      id: "agent-security",
      title: "Агент безопасности",
      role: "security-agent",
      description: "Контролирует запрет ключей в клиентском коде и действия с высоким риском.",
      status: "planned",
      permissions: ["ai.audit.read", "ai.knowledge.read"],
      allowedActions: ["ask-assistant"],
      blockedActions: ["send-mail", "send-whatsapp", "start-documentolog", "delete-data"],
      requiredConnectors: ["knowledge-base"],
      requiresUserApproval: false,
      updatedAt: "2026-04-24T15:55:00.000Z",
    },
  ],
  whatsappGroups: [
    {
      id: "wa-group-dispatch-work",
      title: "ДС / рабочая",
      status: "planned",
      canRead: true,
      canWrite: false,
      writeMode: "approval-required",
      description: "Рабочая группа для поручений, сменных вопросов и быстрых уведомлений.",
      updatedAt: "2026-04-24T14:00:00.000Z",
    },
  ],
  whatsappMessageCandidates: [
    {
      id: "wa-candidate-balkhash-trip",
      groupId: "wa-group-dispatch-work",
      author: "Руководитель проекта",
      messageText: "Нужно ехать на Балхаш завтра утром",
      detectedIntent: "trip",
      confidence: 0.82,
      suggestedAction: "Возможная командировка на Балхаш",
      linkedTaskId: "ai-task-004",
      approvalRequired: true,
      status: "needs-approval",
      createdAt: "2026-04-24T09:05:00.000Z",
    },
  ],
  documents: [
    {
      id: "doc-trip-balkhash",
      title: "Служебная записка на командировку",
      type: "business-trip",
      status: "review",
      linkedTaskId: "ai-task-004",
      linkedApprovalId: "approval-004",
      documentologId: "doclog-trip-balkhash",
      updatedAt: "2026-04-24T09:30:00.000Z",
    },
  ],
  documentTemplates: [
    {
      id: "template-business-trip",
      title: "Служебная записка на командировку",
      documentType: "business-trip",
      description: "Шаблон для подготовки командировки после подтверждения пользователем.",
      owner: "Администрация",
      updatedAt: "2026-04-20T08:00:00.000Z",
    },
  ],
  mailItems: [
    {
      id: "mail-gps-source",
      from: "gps@qaztrucks.example",
      to: ["dispatcher@aam-dispatch.kz"],
      subject: "GPS по технике",
      bodyPreview: "Просим подтвердить список техники для проверки GPS.",
      receivedAt: "2026-04-24T12:40:00.000Z",
      linkedTaskId: "ai-task-005",
    },
  ],
  mailDrafts: [
    {
      id: "mail-draft-gps",
      to: ["gps@qaztrucks.example"],
      cc: [],
      subject: "Проверка GPS по технике подрядчика",
      body: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      status: "needs-approval",
      linkedTaskId: "ai-task-005",
      linkedApprovalId: "approval-005",
      updatedAt: "2026-04-24T13:52:00.000Z",
    },
  ],
  calendarEvents: [
    {
      id: "calendar-trip-balkhash",
      title: "Командировка на Балхаш",
      startsAt: "2026-04-25T08:00:00.000Z",
      endsAt: "2026-04-25T18:00:00.000Z",
      participants: ["Начальник диспетчерской службы"],
      status: "needs-approval",
      linkedTaskId: "ai-task-004",
      updatedAt: "2026-04-24T09:35:00.000Z",
    },
  ],
  documentologItems: [
    {
      id: "doclog-trip-balkhash",
      title: "Служебная записка на командировку",
      externalId: "DOC-2026-00041",
      status: "in-approval",
      approver: "Директор",
      comment: "Ожидает согласования маршрута.",
      linkedDocumentId: "doc-trip-balkhash",
      updatedAt: "2026-04-24T10:05:00.000Z",
    },
  ],
  knowledgeRules: [
    {
      id: "rule-rented-equipment-no-operators",
      category: "Техника",
      rule: "Если техника арендована без операторов, ассистент не предлагает закрепление водителей без ручного подтверждения.",
      exceptions: ["Разовое ходатайство", "Временное перемещение по приказу"],
      example: "Арендованный самосвал без экипажа попадает в список проверки, а не в автоматическую выдачу путевого листа.",
      status: "active",
      createdBy: "Администратор",
      updatedAt: "2026-04-24T08:30:00.000Z",
    },
  ],
  knowledgeBaseItems: [
    {
      id: "kb-item-trip-rule",
      title: "Порядок подготовки командировки",
      content: "Командировка создается из события только после подтверждения пользователя на сайте.",
      source: "manual",
      access: "internal",
      tags: ["командировка", "согласование", "Documentolog"],
      updatedAt: "2026-04-24T08:45:00.000Z",
    },
  ],
  developmentIdeas: [
    {
      id: "idea-whatsapp-trip",
      title: "Создание командировки из WhatsApp-сообщения",
      description: "Ассистент распознает сообщение о поездке, создает задачу, готовит служебную записку и выводит действие на согласование.",
      benefit: "Сокращает ручную подготовку командировок и уменьшает риск забыть поручение из чата.",
      risks: ["Неверное распознавание даты", "Запуск официального документа без подтверждения запрещен"],
      affectedModules: ["AI-ассистент", "Планировщик", "Documentolog", "WhatsApp"],
      businessLogic: [
        "WhatsApp используется только как источник события и канал уведомления.",
        "Официальный документ создается только после подтверждения на сайте.",
      ],
      accessRoles: ["supervisor", "admin"],
      missingQuestions: ["Кто согласует командировки по участкам?", "Какие поля обязательны для Documentolog?"],
      acceptanceCriteria: [
        "Сообщение попадает в кандидаты WhatsApp.",
        "Пользователь видит задачу в блоке Требуют моего решения.",
        "Documentolog не запускается без подтверждения.",
      ],
      status: "reviewing",
      codexPromptDraftId: "codex-prompt-whatsapp-trip",
      updatedAt: "2026-04-24T10:20:00.000Z",
    },
  ],
  codexPromptDrafts: [
    {
      id: "codex-prompt-whatsapp-trip",
      title: "Промт Codex: командировка из WhatsApp",
      body: "Добавить backend-safe поток: WhatsApp candidate -> task -> approval -> document draft -> Documentolog dry-run. Не подключать реальные ключи, не выполнять внешние действия без approval.",
      linkedIdeaId: "idea-whatsapp-trip",
      status: "draft",
      updatedAt: "2026-04-24T10:25:00.000Z",
    },
  ],
  chatMessages: [
    {
      id: "chat-001",
      role: "system",
      author: "Система",
      text: "Чат используется для вопросов, анализа и подготовки черновиков. Критические действия автоматически попадают во вкладку Одобрения.",
      createdAt: "2026-04-24T15:05:00.000Z",
    },
    {
      id: "chat-002",
      role: "user",
      author: "Начальник диспетчерской службы",
      text: "Проверь причину невыполнения суточного плана по Аксу и подготовь формулировку.",
      createdAt: "2026-04-24T15:15:00.000Z",
      linkedTaskId: "ai-task-001",
    },
    {
      id: "chat-003",
      role: "assistant",
      author: "AI-ассистент",
      text: "Найдено отставание. Я подготовил черновик причины и поместил действие в Одобрения, потому что текст пойдет в официальный отчет.",
      createdAt: "2026-04-24T15:20:00.000Z",
      linkedTaskId: "ai-task-001",
    },
  ],
  approvalActions: [
    {
      id: "approval-001",
      taskId: "ai-task-001",
      title: "Подтвердить причину для отчета Аксу",
      actionType: "ask-assistant",
      risk: "critical",
      status: "required",
      targetConnector: "ai-api",
      targetLabel: "Отчетность Аксу",
      draftText: "Основной вклад в отставание дают простои транспортировочной техники и погодные ограничения.",
      requestedBy: "AI-ассистент",
      createdAt: "2026-04-24T15:20:00.000Z",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "approval-002",
      taskId: "ai-task-002",
      title: "Отправить WhatsApp подрядчику Qaz Trucks",
      actionType: "send-whatsapp",
      risk: "critical",
      status: "required",
      targetConnector: "whatsapp",
      targetLabel: "Qaz Trucks",
      draftText: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      requestedBy: "Диспетчер",
      createdAt: "2026-04-24T13:50:00.000Z",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
    {
      id: "approval-003",
      taskId: "ai-task-003",
      title: "Подготовить документ по маркзамеру",
      actionType: "prepare-document",
      risk: "critical",
      status: "approved",
      targetConnector: "documentolog",
      targetLabel: "Маркзамер за апрель",
      draftText: "Собрать последний маркзамер и недостающий оперучет до рабочей даты.",
      requestedBy: "ПТО",
      approver: "Начальник диспетчерской службы",
      createdAt: "2026-04-24T11:30:00.000Z",
      updatedAt: "2026-04-24T12:10:00.000Z",
    },
    {
      id: "approval-004",
      taskId: "ai-task-004",
      title: "Подготовить командировку на Балхаш",
      actionType: "create-business-trip",
      risk: "critical",
      status: "required",
      targetConnector: "documentolog",
      targetLabel: "Служебная записка на командировку",
      draftText: "Подготовить служебную записку на командировку на Балхаш на 25.04.2026.",
      requestedBy: "WhatsApp-монитор",
      createdAt: "2026-04-24T09:20:00.000Z",
      updatedAt: "2026-04-24T09:30:00.000Z",
    },
    {
      id: "approval-005",
      taskId: "ai-task-005",
      title: "Отправить письмо подрядчику по GPS",
      actionType: "send-mail",
      risk: "critical",
      status: "required",
      targetConnector: "mail",
      targetLabel: "gps@qaztrucks.example",
      draftText: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      requestedBy: "Агент почты",
      createdAt: "2026-04-24T13:52:00.000Z",
      updatedAt: "2026-04-24T13:52:00.000Z",
    },
  ],
  tasks: [
    {
      id: "ai-task-001",
      title: "Проверить причину невыполнения суточного плана по Аксу",
      kind: "ask",
      status: "needs-approval",
      channel: "app",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "report",
        id: "report-aksu-2026-04-24",
        label: "Отчетность Аксу за 24.04.2026",
      },
      prompt: "Сопоставить план, факт, ремонты и простои по участку Аксу.",
      resultDraft: "Основной вклад в отставание дают простои транспортировочной техники и погодные ограничения.",
      evidenceIds: ["ev-001", "ev-002"],
      approvalStatus: "required",
      approvalActionId: "approval-001",
      owner: "Начальник диспетчерской службы",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "ai-task-002",
      title: "Подготовить сообщение подрядчику по GPS",
      kind: "draft-message",
      status: "draft",
      channel: "whatsapp",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "vehicle",
        id: "vehicle-gps-qaz-trucks",
        label: "Техника Qaz Trucks без активности GPS",
      },
      prompt: "Сформировать корректное уведомление о необходимости проверить GPS.",
      resultDraft: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      evidenceIds: ["ev-003"],
      approvalStatus: "required",
      approvalActionId: "approval-002",
      owner: "Диспетчер",
      updatedAt: "2026-04-24T13:45:00.000Z",
    },
    {
      id: "ai-task-003",
      title: "Собрать материалы для справки по маркзамеру",
      kind: "summarize",
      status: "queued",
      channel: "documentolog",
      sourceEntity: {
        type: "pto",
        id: "survey-2026-04",
        label: "Маркшейдерский замер за апрель",
      },
      prompt: "Собрать последние замеры и недостающий оперучет до рабочей даты.",
      evidenceIds: ["ev-004"],
      approvalStatus: "approved",
      approvalActionId: "approval-003",
      owner: "ПТО",
      updatedAt: "2026-04-24T11:30:00.000Z",
    },
    {
      id: "ai-task-004",
      title: "Возможная командировка на Балхаш",
      kind: "prepare-document",
      status: "needs-approval",
      channel: "documentolog",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "document",
        id: "wa-candidate-balkhash-trip",
        label: "WhatsApp: Нужно ехать на Балхаш завтра утром",
      },
      prompt: "Проверить сообщение, уточнить дату поездки и подготовить служебную записку.",
      resultDraft: "Подготовить служебную записку на командировку на Балхаш на 25.04.2026.",
      evidenceIds: ["ev-005"],
      approvalStatus: "required",
      approvalActionId: "approval-004",
      owner: "Начальник диспетчерской службы",
      updatedAt: "2026-04-24T09:30:00.000Z",
    },
    {
      id: "ai-task-005",
      title: "Подготовить письмо подрядчику по GPS",
      kind: "draft-message",
      status: "needs-approval",
      channel: "mail",
      workDate: "2026-04-24",
      sourceEntity: {
        type: "vehicle",
        id: "mail-gps-source",
        label: "Письмо по GPS подрядчика",
      },
      prompt: "Сформировать письмо подрядчику по проверке GPS.",
      resultDraft: "Просим проверить GPS на закрепленной технике и подтвердить восстановление сигнала.",
      evidenceIds: ["ev-003"],
      approvalStatus: "required",
      approvalActionId: "approval-005",
      owner: "Диспетчер",
      updatedAt: "2026-04-24T13:52:00.000Z",
    },
  ],
  notifications: [
    {
      id: "ai-note-001",
      title: "Напоминание о согласовании причины",
      channel: "app",
      status: "queued",
      target: "Руководитель участка Аксу",
      body: "Нужно подтвердить причину отставания перед отправкой отчета заказчику.",
      approvalStatus: "not-required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-001",
      plannerItemId: "plan-ai-001",
      updatedAt: "2026-04-24T15:25:00.000Z",
    },
    {
      id: "ai-note-002",
      title: "Черновик WhatsApp подрядчику",
      channel: "whatsapp",
      status: "draft",
      target: "Qaz Trucks",
      body: "Просим проверить GPS и подтвердить готовность техники к смене.",
      approvalStatus: "required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-002",
      plannerItemId: "plan-ai-002",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
    {
      id: "ai-note-003",
      title: "Найдена возможная командировка",
      channel: "app",
      status: "needs-approval",
      target: "Начальник диспетчерской службы",
      body: "WhatsApp-монитор нашел сообщение о поездке на Балхаш и подготовил действие на согласование.",
      approvalStatus: "required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-004",
      updatedAt: "2026-04-24T09:30:00.000Z",
    },
    {
      id: "ai-note-004",
      title: "Черновик письма по GPS",
      channel: "mail",
      status: "draft",
      target: "gps@qaztrucks.example",
      body: "Подготовлен черновик письма подрядчику по GPS. Отправка требует решения пользователя.",
      approvalStatus: "required",
      workDate: "2026-04-24",
      linkedTaskId: "ai-task-005",
      updatedAt: "2026-04-24T13:52:00.000Z",
    },
  ],
  plannerItems: [
    {
      id: "plan-ai-001",
      title: "Проверить причину невыполнения плана по Аксу",
      description: "Сформировать черновик причины и вывести действие на согласование.",
      plannedDate: "2026-04-24",
      plannedTime: "15:00",
      status: "needs-decision",
      priority: "high",
      owner: "Начальник диспетчерской службы",
      target: "Руководитель участка Аксу",
      channel: "app",
      actionType: "update-report-reason",
      preparedText: "Проверить причины невыполнения и подготовить текст для отчета.",
      requireApproval: true,
      recurrence: { type: "none" },
      linkedTaskId: "ai-task-001",
      linkedNotificationId: "ai-note-001",
      updatedAt: "2026-04-24T15:20:00.000Z",
    },
    {
      id: "plan-ai-002",
      title: "Подготовить уведомление по GPS подрядчика",
      description: "Собрать технику без сигнала GPS и подготовить сообщение подрядчику.",
      plannedDate: "2026-04-24",
      plannedTime: "13:30",
      status: "needs-decision",
      priority: "normal",
      owner: "Диспетчер",
      target: "Qaz Trucks",
      channel: "whatsapp",
      actionType: "send-whatsapp",
      preparedText: "Просим проверить GPS и подтвердить готовность техники к смене.",
      requireApproval: true,
      recurrence: { type: "none" },
      linkedTaskId: "ai-task-002",
      linkedNotificationId: "ai-note-002",
      updatedAt: "2026-04-24T13:50:00.000Z",
    },
    {
      id: "plan-ai-003",
      title: "Проверить недостающий оперучет после маркзамера",
      description: "На следующую рабочую дату сверить маркзамер и оперучет перед отчетом.",
      plannedDate: "2026-04-25",
      plannedTime: "10:00",
      status: "planned",
      priority: "normal",
      owner: "ПТО",
      target: "ПТО",
      channel: "app",
      actionType: "ask-assistant",
      preparedText: "Сверить маркзамер и оперучет перед отчетом.",
      requireApproval: false,
      recurrence: { type: "daily", interval: 1 },
      comment: "Появится в Задачах 25.04.2026.",
      updatedAt: "2026-04-24T16:10:00.000Z",
    },
  ],
  integrations: [
    {
      key: "ai-api",
      title: "AI API",
      status: "planned",
      mode: "read-write",
      description: "Серверный обработчик запросов, черновиков и анализа причин.",
      requiredScopes: ["ai.chat.read", "ai.chat.write", "ai.context.dispatcher.read"],
      availableCapabilities: ["Чат", "Черновики", "Анализ", "Поиск по контексту"],
      stubNotes: "Пока работает как dry-run модель без обращения к внешнему AI API.",
      nextStep: "Подключить server action/API route с безопасным хранением ключа.",
      usedByAgentIds: ["agent-main", "agent-development"],
    },
    {
      key: "whatsapp",
      title: "WhatsApp",
      status: "planned",
      mode: "write",
      description: "Черновики и отправка сообщений после согласования.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
      availableCapabilities: ["Чтение кандидатов", "Черновик", "Отправка после одобрения"],
      stubNotes: "WhatsApp не является основным интерфейсом, только источник событий и канал уведомлений.",
      nextStep: "Подключить backend-коннектор и журнал входящих сообщений.",
      usedByAgentIds: ["agent-whatsapp"],
    },
    {
      key: "documentolog",
      title: "Documentolog",
      status: "planned",
      mode: "read-write",
      description: "Поиск документов, создание черновиков и маршрутов согласования.",
      requiredScopes: ["ai.documentolog.read", "ai.documentolog.write"],
      availableCapabilities: ["Черновик документа", "Старт согласования", "Статусы"],
      stubNotes: "Запуск согласования заблокирован до решения пользователя на сайте.",
      nextStep: "Описать обязательные поля шаблонов Documentolog.",
      usedByAgentIds: ["agent-document", "agent-documentolog"],
    },
    {
      key: "mail",
      title: "Почта",
      status: "planned",
      mode: "read-write",
      description: "Черновики писем, чтение согласованных входящих и контроль отправки.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
      availableCapabilities: ["Входящие", "Черновик", "Отправка после одобрения"],
      stubNotes: "SMTP/API ключи не должны попадать в frontend.",
      nextStep: "Добавить backend-очередь отправки писем.",
      usedByAgentIds: ["agent-mail"],
    },
    {
      key: "calendar",
      title: "Календарь",
      status: "planned",
      mode: "read-write",
      description: "События, напоминания, сроки согласований и сменные задачи.",
      requiredScopes: ["ai.calendar.read", "ai.calendar.write"],
      availableCapabilities: ["События", "Напоминания", "Повторы"],
      stubNotes: "Внешний календарь требует подтверждения перед созданием события.",
      nextStep: "Выбрать календарный provider и схему прав.",
      usedByAgentIds: ["agent-task-planner", "agent-calendar"],
    },
    {
      key: "push",
      title: "Push-уведомления",
      status: "disabled",
      mode: "write",
      description: "Внутренние уведомления пользователям после включения ролей.",
      requiredScopes: ["ai.external.draft", "ai.external.send"],
      availableCapabilities: ["Внутренние уведомления", "Быстрые ссылки"],
      stubNotes: "Пока уведомления живут внутри сайта.",
      nextStep: "Подключить серверную доставку после настройки пользователей.",
      usedByAgentIds: ["agent-task-planner"],
    },
    {
      key: "knowledge-base",
      title: "База знаний",
      status: "planned",
      mode: "read",
      description: "Регламенты, инструкции, шаблоны причин и история решений.",
      requiredScopes: ["ai.knowledge.read"],
      availableCapabilities: ["Поиск", "Правила", "Шаблоны", "Контекст"],
      stubNotes: "Индексация и поиск должны выполняться на backend.",
      nextStep: "Определить источники знаний и права доступа.",
      usedByAgentIds: ["agent-main", "agent-mentor", "agent-qa", "agent-security"],
    },
  ],
  knowledgeSources: [
    {
      id: "kb-001",
      title: "Правила заполнения причин невыполнения плана",
      source: "manual",
      access: "internal",
      owner: "Диспетчерская служба",
      updatedAt: "2026-04-23T10:00:00.000Z",
      tags: ["отчетность", "причины", "план"],
    },
    {
      id: "kb-002",
      title: "Регламент согласования сообщений подрядчикам",
      source: "file",
      access: "restricted",
      owner: "Администрация",
      updatedAt: "2026-04-20T09:30:00.000Z",
      tags: ["подрядчики", "whatsapp", "согласование"],
    },
    {
      id: "kb-003",
      title: "Порядок учета маркзамера и оперучета",
      source: "system",
      access: "internal",
      owner: "ПТО",
      updatedAt: "2026-04-18T08:15:00.000Z",
      tags: ["ПТО", "замер", "оперучет"],
    },
  ],
  evidence: [
    {
      id: "ev-001",
      source: {
        type: "dispatch-summary",
        id: "summary-2026-04-24",
        label: "Сводка за сутки",
      },
      summary: "Зафиксирован ремонт транспортировочной техники и простой ДСК.",
      confidence: 0.78,
    },
    {
      id: "ev-002",
      source: {
        type: "report",
        id: "report-aksu-2026-04-24",
        label: "План-факт Аксу",
      },
      summary: "Отклонение по факту ниже плана на рабочую дату.",
      confidence: 0.84,
    },
    {
      id: "ev-003",
      source: {
        type: "vehicle",
        id: "fleet-qaz-trucks-gps",
        label: "GPS подрядчика",
      },
      summary: "Часть техники подрядчика не передает последние координаты.",
      confidence: 0.72,
    },
    {
      id: "ev-004",
      source: {
        type: "pto",
        id: "survey-oper-april",
        label: "Замер и оперучет",
      },
      summary: "Последний маркзамер нужно дополнить оперучетом до текущей рабочей даты.",
      confidence: 0.81,
    },
    {
      id: "ev-005",
      source: {
        type: "document",
        id: "wa-candidate-balkhash-trip",
        label: "WhatsApp-кандидат",
      },
      summary: "Сообщение распознано как возможная командировка на Балхаш.",
      confidence: 0.82,
    },
  ],
  auditEvents: [
    {
      id: "audit-001",
      timestamp: "2026-04-24T15:20:00.000Z",
      actor: "Начальник диспетчерской службы",
      role: "supervisor",
      action: "Создан черновик анализа",
      connector: "ai-api",
      target: "Отчетность Аксу",
      status: "success",
      summary: "Сформирован черновик причины с двумя источниками.",
    },
    {
      id: "audit-002",
      timestamp: "2026-04-24T13:50:00.000Z",
      actor: "Диспетчер",
      role: "operator",
      action: "Подготовлен черновик сообщения",
      connector: "whatsapp",
      target: "Qaz Trucks",
      status: "success",
      summary: "Отправка заблокирована до согласования.",
    },
    {
      id: "audit-003",
      timestamp: "2026-04-24T11:30:00.000Z",
      actor: "ПТО",
      role: "operator",
      action: "Запрошена сводка по замеру",
      connector: "documentolog",
      target: "Маркзамер за апрель",
      status: "blocked",
      summary: "Интеграция еще не подключена, задача оставлена в очереди.",
    },
    {
      id: "audit-004",
      timestamp: "2026-04-24T09:05:00.000Z",
      actor: "WhatsApp-монитор",
      role: "operator",
      action: "Обнаружено WhatsApp-сообщение",
      connector: "whatsapp",
      target: "ДС / рабочая",
      status: "success",
      summary: "Сообщение распознано как возможная командировка.",
    },
    {
      id: "audit-005",
      timestamp: "2026-04-24T09:20:00.000Z",
      actor: "AI-ассистент",
      role: "operator",
      action: "Создана задача",
      connector: "ai-api",
      target: "Возможная командировка на Балхаш",
      status: "success",
      summary: "Создана задача и связанный черновик документа.",
    },
    {
      id: "audit-006",
      timestamp: "2026-04-24T09:30:00.000Z",
      actor: "AI-ассистент",
      role: "operator",
      action: "Действие отправлено на одобрение",
      connector: "documentolog",
      target: "Служебная записка на командировку",
      status: "blocked",
      summary: "Запуск Documentolog заблокирован до решения пользователя на сайте.",
    },
    {
      id: "audit-007",
      timestamp: "2026-04-24T10:25:00.000Z",
      actor: "Агент развития / ТЗ / Codex",
      role: "operator",
      action: "Создан mock-промт для Codex",
      connector: "ai-api",
      target: "Командировка из WhatsApp-сообщения",
      status: "success",
      summary: "Промт подготовлен как черновик без вызова внешнего API.",
    },
  ],
};
