import type { PtoDateTableRendererOptions } from "@/features/pto/usePtoDateTableRenderer";
import type { UseAppPtoScreenPropsArgs } from "@/features/app/appPtoScreenPropsTypes";

export function createAppPtoDateRendererOptions({
  appState,
  models,
  runtime,
  ptoDateViewport,
  ptoDateEditing,
  ptoSupplementalTables,
}: Omit<UseAppPtoScreenPropsArgs, "navigation">): PtoDateTableRendererOptions {
  return {
    ptoTab: appState.ptoTab,
    ptoAreaFilter: appState.ptoAreaFilter,
    ptoPlanYear: appState.ptoPlanYear,
    reportDate: appState.reportDate,
    ptoYearMonths: models.ptoYearMonths,
    ptoMonthGroups: models.ptoMonthGroups,
    ptoAreaTabs: models.ptoAreaTabs,
    ptoYearTabs: models.ptoYearTabs,
    ptoYearDialogOpen: appState.ptoYearDialogOpen,
    ptoYearInput: appState.ptoYearInput,
    ptoDateEditing: appState.ptoDateEditing,
    ptoColumnWidths: appState.ptoColumnWidths,
    ptoRowHeights: appState.ptoRowHeights,
    ptoDateViewport: ptoDateViewport.viewport,
    ptoDateOptionMaps: models.ptoDateOptionMaps,
    ptoDateTableScrollRef: ptoDateViewport.scrollRef,
    ptoPlanImportInputRef: appState.ptoPlanImportInputRef,
    draggedPtoRowId: appState.draggedPtoRowId,
    ptoDropTarget: appState.ptoDropTarget,
    hoveredPtoAddRowId: appState.hoveredPtoAddRowId,
    ptoFormulaCell: appState.ptoFormulaCell,
    ptoFormulaDraft: appState.ptoFormulaDraft,
    ptoInlineEditCell: appState.ptoInlineEditCell,
    ptoInlineEditInitialDraft: appState.ptoInlineEditInitialDraft,
    ptoSelectionAnchorCell: appState.ptoSelectionAnchorCell,
    ptoSelectedCellKeys: appState.ptoSelectedCellKeys,
    ptoSelectionDraggingRef: appState.ptoSelectionDraggingRef,
    ptoDraftRowFields: appState.ptoDraftRowFields,
    editingPtoHeaderKey: appState.editingPtoHeaderKey,
    ptoHeaderDraft: appState.ptoHeaderDraft,
    setPtoDateEditing: appState.setPtoDateEditing,
    setDraggedPtoRowId: appState.setDraggedPtoRowId,
    setPtoDropTarget: appState.setPtoDropTarget,
    setPtoFormulaCell: appState.setPtoFormulaCell,
    setPtoFormulaDraft: appState.setPtoFormulaDraft,
    setPtoInlineEditCell: appState.setPtoInlineEditCell,
    setPtoInlineEditInitialDraft: appState.setPtoInlineEditInitialDraft,
    setPtoSelectionAnchorCell: appState.setPtoSelectionAnchorCell,
    setPtoSelectedCellKeys: appState.setPtoSelectedCellKeys,
    setPtoYearInput: appState.setPtoYearInput,
    setPtoYearDialogOpen: appState.setPtoYearDialogOpen,
    setExpandedPtoMonths: appState.setExpandedPtoMonths,
    setHoveredPtoAddRowId: appState.setHoveredPtoAddRowId,
    setPtoDraftRowFields: appState.setPtoDraftRowFields,
    setPtoPendingFieldFocus: appState.setPtoPendingFieldFocus,
    setPtoHeaderDraft: appState.setPtoHeaderDraft,
    savePtoLocalState: runtime.savePtoLocalState,
    requestPtoDatabaseSave: runtime.requestPtoDatabaseSave,
    savePtoDatabaseChanges: runtime.savePtoDatabaseChanges,
    selectPtoArea: appState.selectPtoArea,
    currentPtoDateExcelMeta: ptoSupplementalTables.currentPtoDateExcelMeta,
    exportPtoDateTableToExcel: ptoSupplementalTables.exportPtoDateTableToExcel,
    openPtoDateImportFilePicker: ptoSupplementalTables.openPtoDateImportFilePicker,
    importPtoDateTableFromExcel: ptoSupplementalTables.importPtoDateTableFromExcel,
    selectPtoPlanYear: (year) => {
      void runtime.flushPtoDatabasePendingSave().then((canNavigate) => {
        if (canNavigate) appState.selectPtoPlanYear(year);
      });
    },
    deletePtoYear: ptoDateEditing.deletePtoYear,
    addPtoYear: ptoDateEditing.addPtoYear,
    updatePtoDateViewportFromElement: ptoDateViewport.updateViewportFromElement,
    handlePtoDateTableScroll: ptoDateViewport.handleScroll,
    startPtoColumnResize: runtime.startPtoColumnResize,
    startPtoRowResize: runtime.startPtoRowResize,
    addLinkedPtoDateRow: ptoDateEditing.addLinkedPtoDateRow,
    removeLinkedPtoDateRow: ptoDateEditing.removeLinkedPtoDateRow,
    getPtoDropPosition: ptoDateEditing.getPtoDropPosition,
    moveLinkedPtoDateRow: ptoDateEditing.moveLinkedPtoDateRow,
    updatePtoDateRow: ptoDateEditing.updatePtoDateRow,
    clearPtoCarryoverOverride: ptoDateEditing.clearPtoCarryoverOverride,
    updatePtoDateDay: ptoDateEditing.updatePtoDateDay,
    updatePtoMonthTotal: ptoDateEditing.updatePtoMonthTotal,
    beginPtoRowTextDraft: ptoDateEditing.beginPtoRowTextDraft,
    getPtoRowTextDraft: ptoDateEditing.getPtoRowTextDraft,
    updatePtoRowTextDraft: ptoDateEditing.updatePtoRowTextDraft,
    commitPtoRowTextDraft: ptoDateEditing.commitPtoRowTextDraft,
    cancelPtoRowTextDraft: ptoDateEditing.cancelPtoRowTextDraft,
    ptoHeaderLabel: runtime.ptoHeaderLabel,
    startPtoHeaderEdit: runtime.startPtoHeaderEdit,
    commitPtoHeaderEdit: runtime.commitPtoHeaderEdit,
    cancelPtoHeaderEdit: runtime.cancelPtoHeaderEdit,
  };
}
