"use client";

import { AppHeader } from "@/components/layout/AppHeader";
import { AppAdminContent } from "@/features/app/AppAdminContent";
import { AppPrimaryContent } from "@/features/app/AppPrimaryContent";
import { useAppActiveNavigation } from "@/features/app/useAppActiveNavigation";
import { useAppAdminContentProps } from "@/features/app/useAppAdminContentProps";
import { useAppAdminDatabaseProps } from "@/features/app/useAppAdminDatabaseProps";
import { useAppAdminReportEditors } from "@/features/app/useAppAdminReportEditors";
import { useAppAdminReportsProps } from "@/features/app/useAppAdminReportsProps";
import { useAppAdminVehiclesProps } from "@/features/app/useAppAdminVehiclesProps";
import { useAppDeferredData } from "@/features/app/useAppDeferredData";
import { useAppDispatchSectionProps } from "@/features/app/useAppDispatchSectionProps";
import { useAppDispatchSummaryModel } from "@/features/app/useAppDispatchSummaryModel";
import { useAppHeaderEditors } from "@/features/app/useAppHeaderEditors";
import { useAppHeaderProps } from "@/features/app/useAppHeaderProps";
import { useAppInitialDataLoadController } from "@/features/app/useAppInitialDataLoadController";
import { AppPageShell } from "@/features/app/AppPageShell";
import { useAppPtoDateEditing } from "@/features/app/useAppPtoDateEditing";
import { useAppPtoDateModel } from "@/features/app/useAppPtoDateModel";
import { useAppPtoDateViewport } from "@/features/app/useAppPtoDateViewport";
import { useAppPtoPersistenceController } from "@/features/app/useAppPtoPersistenceController";
import { useAppPtoSectionProps } from "@/features/app/useAppPtoSectionProps";
import { useAppPtoSupplementalTables } from "@/features/app/useAppPtoSupplementalTables";
import { useAppReportReasonEditing } from "@/features/app/useAppReportReasonEditing";
import { useAppReportsSectionProps } from "@/features/app/useAppReportsSectionProps";
import { useAppReportsModel } from "@/features/app/useAppReportsModel";
import { useAppSharedPersistenceController } from "@/features/app/useAppSharedPersistenceController";
import { useAppStateBundle } from "@/features/app/useAppStateBundle";
import { useAppTableInteractionEffects } from "@/features/app/useAppTableInteractionEffects";
import { useAppUndoController } from "@/features/app/useAppUndoController";
import { useAppVehicleEditing } from "@/features/app/useAppVehicleEditing";
import { useAppVehicleFocusController } from "@/features/app/useAppVehicleFocusController";
import { useAppVehicleViewModel } from "@/features/app/useAppVehicleViewModel";
import { useFleetRows } from "@/features/fleet/useFleetRows";
import { vehicleFilterColumns } from "@/features/admin/vehicles/vehicleFilterColumns";
import { defaultUserCard } from "@/lib/domain/reference/defaults";
import { databaseConfigured } from "@/lib/data/config";

export default function App() {
  const appState = useAppStateBundle();
  const {
    topTab,
    topTabs,
    subTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    deleteTopTab,
    showTopTab,
    updateCustomTabTitle,
    showCustomTab,
    deleteCustomTab,
    dispatchTab,
    setDispatchTab,
    fleetTab,
    setFleetTab,
    contractorTab,
    setContractorTab,
    fuelTab,
    setFuelTab,
    ptoTab,
    tbTab,
    setTbTab,
    structureSection,
    setStructureSection,
    adminSection,
    setAdminSection,
    dispatchSummaryRows,
    setDispatchSummaryRows,
    dispatchVehicleToAddId,
    setDispatchVehicleToAddId,
    adminVehiclesEditing,
    setAdminVehiclesEditing,
    showAllVehicleRows,
    setShowAllVehicleRows,
    vehiclePreviewRowLimit,
    setVehiclePreviewRowLimit,
    vehicleRows,
    setVehicleRows,
    vehicleFilters,
    setVehicleFilters,
    vehicleFilterDrafts,
    setVehicleFilterDrafts,
    openVehicleFilter,
    setOpenVehicleFilter,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    setPendingVehicleFocus,
    activeVehicleCell,
    setActiveVehicleCell,
    vehicleSelectionAnchorCell,
    setVehicleSelectionAnchorCell,
    selectedVehicleCellKeys,
    setSelectedVehicleCellKeys,
    editingVehicleCell,
    setEditingVehicleCell,
    vehicleCellDraft,
    setVehicleCellDraft,
    vehicleCellInitialDraft,
    setVehicleCellInitialDraft,
    vehicleCellSkipBlurCommitRef,
    vehicleSelectionDraggingRef,
    vehicleSelectionAnchorRef,
    vehicleImportInputRef,
    adminVehicleTableScrollRef,
    vehicleRowsRef,
    vehiclesDatabaseLoadedRef,
    vehiclesDatabaseSaveSnapshotRef,
    draggedPtoRowId,
    setDraggedPtoRowId,
    ptoDropTarget,
    setPtoDropTarget,
    ptoFormulaCell,
    setPtoFormulaCell,
    ptoFormulaDraft,
    setPtoFormulaDraft,
    ptoInlineEditCell,
    setPtoInlineEditCell,
    ptoInlineEditInitialDraft,
    setPtoInlineEditInitialDraft,
    ptoSelectionAnchorCell,
    setPtoSelectionAnchorCell,
    ptoSelectedCellKeys,
    setPtoSelectedCellKeys,
    ptoDateEditing,
    setPtoDateEditing,
    hoveredPtoAddRowId,
    setHoveredPtoAddRowId,
    ptoPendingFieldFocus,
    setPtoPendingFieldFocus,
    ptoRowFieldDrafts,
    setPtoRowFieldDrafts,
    ptoDraftRowFields,
    setPtoDraftRowFields,
    ptoSelectionDraggingRef,
    ptoPlanImportInputRef,
    ptoDatabaseLoadedRef,
    reportArea,
    setReportArea,
    reportCustomerId,
    setReportCustomerId,
    adminReportCustomerId,
    setAdminReportCustomerId,
    adminReportCustomerSettingsTab,
    setAdminReportCustomerSettingsTab,
    editingReportRowLabelKeys,
    setEditingReportRowLabelKeys,
    expandedReportSummaryIds,
    setExpandedReportSummaryIds,
    editingReportFactSourceRowKey,
    setEditingReportFactSourceRowKey,
    reportCustomers,
    setReportCustomers,
    reportAreaOrder,
    reportWorkOrder,
    reportHeaderLabels,
    setReportHeaderLabels,
    reportColumnWidths,
    setReportColumnWidths,
    reportReasons,
    setReportReasons,
    editingReportHeaderKey,
    setEditingReportHeaderKey,
    reportHeaderDraft,
    setReportHeaderDraft,
    areaShiftCutoffs,
    ptoPlanYear,
    setPtoPlanYear,
    ptoYearInput,
    setPtoYearInput,
    ptoYearDialogOpen,
    setPtoYearDialogOpen,
    ptoManualYears,
    setPtoManualYears,
    ptoAreaFilter,
    expandedPtoMonths,
    setExpandedPtoMonths,
    ptoPlanRows,
    setPtoPlanRows,
    ptoSurveyRows,
    setPtoSurveyRows,
    ptoOperRows,
    setPtoOperRows,
    ptoColumnWidths,
    setPtoColumnWidths,
    ptoRowHeights,
    setPtoRowHeights,
    ptoHeaderLabels,
    setPtoHeaderLabels,
    editingPtoHeaderKey,
    setEditingPtoHeaderKey,
    ptoHeaderDraft,
    setPtoHeaderDraft,
    ptoBucketValues,
    setPtoBucketValues,
    ptoBucketManualRows,
    setPtoBucketManualRows,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    setEditingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    reportDate,
    selectReportDate,
    updateAreaShiftCutoff,
    adminLogs,
    addAdminLog,
    clearAdminLogs,
    lastChangeLog,
    lastUploadLog,
    ptoDatabaseMessage,
    ptoDatabaseReady,
    saveStatus,
    showSaveStatus,
    hideSaveStatus,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    refreshClientSnapshots,
    createClientSnapshotNow,
    restoreClientSnapshot,
    areaFilter,
    setAreaFilter,
    search,
    setSearch,
    selectTopTab,
    selectPtoTab,
    selectPtoPlanYear,
    selectPtoArea,
  } = appState;
  const {
    pushVehicleUndoSnapshot,
    resetUndoHistoryForExternalRestore,
  } = useAppUndoController({
    appState,
    databaseConfigured,
  });

  useAppVehicleFocusController({ appState });

  useAppInitialDataLoadController({ appState });

  const {
    savePtoDatabaseChanges,
    requestPtoDatabaseSave,
    savePtoLocalState,
  } = useAppPtoPersistenceController({
    appState,
    resetUndoHistoryForExternalRestore,
  });

  useAppSharedPersistenceController({ appState, databaseConfigured });

  const {
    commitReportDayReason,
    cancelReportDayReasonDraft,
    updateReportDayReasonDraft,
    commitReportYearReason,
    cancelReportYearReasonDraft,
    updateReportYearReasonDraft,
  } = useAppReportReasonEditing({
    reportDate,
    setReportReasons,
    requestPtoDatabaseSave,
  });

  const {
    cancelPtoHeaderEdit,
    commitPtoHeaderEdit,
    printReport,
    ptoHeaderLabel,
    reportHeaderLabel,
    renderReportHeaderText,
    startPtoHeaderEdit,
  } = useAppHeaderEditors({
    ptoHeaderLabels,
    ptoHeaderDraft,
    setPtoHeaderLabels,
    setEditingPtoHeaderKey,
    setPtoHeaderDraft,
    reportHeaderLabels,
    reportHeaderDraft,
    editingReportHeaderKey,
    setReportHeaderLabels,
    setEditingReportHeaderKey,
    setReportHeaderDraft,
    requestPtoDatabaseSave,
    addAdminLog,
  });

  const {
    startPtoColumnResize,
    startReportColumnResize,
    startPtoRowResize,
  } = useAppTableInteractionEffects({
    ptoRowHeights,
    setPtoColumnWidths,
    setPtoRowHeights,
    setReportColumnWidths,
    requestSave: requestPtoDatabaseSave,
    addAdminLog,
    ptoSelectionDraggingRef,
    vehicleSelectionDraggingRef,
    vehicleSelectionAnchorRef,
    setActiveVehicleCell,
    setVehicleSelectionAnchorCell,
    setSelectedVehicleCellKeys,
    setEditingVehicleCell,
    setPtoFormulaCell,
    setPtoFormulaDraft,
    setPtoInlineEditCell,
    setPtoInlineEditInitialDraft,
    setPtoSelectionAnchorCell,
    setPtoSelectedCellKeys,
    pendingFieldFocus: ptoPendingFieldFocus,
    setPendingFieldFocus: setPtoPendingFieldFocus,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
  });

  const {
    deferredPtoPlanRows,
    deferredPtoSurveyRows,
    deferredPtoOperRows,
    deferredVehicleRows,
    renderedTopTab,
    needsReportRows,
    needsDerivedReportRows,
    needsAdminReportRows,
    needsReportIndexes,
    needsAutoReportRows,
  } = useAppDeferredData({
    ptoPlanRows,
    ptoSurveyRows,
    ptoOperRows,
    vehicleRows,
    topTab,
    adminSection,
  });

  const {
    reportBaseRows,
    activeAdminReportCustomer,
    adminReportBaseRows,
    derivedReportRowsByKey,
    reportAutoRowKeysForCustomer,
    activeAdminReportBaseRows,
    activeAdminReportVisibleRowKeys,
    activeAdminReportOrderRows,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    activeAdminReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    adminReportWorkOrderGroups,
    activeAdminReportSelectedCount,
    activeAdminReportRowLabelEntries,
    activeAdminReportUsesSummaryRows,
    visibleAdminReportCustomerSettingsTab,
    activeReportCustomer,
    reportAreaTabs,
    filteredReports,
    filteredReportAreaGroups,
    areaShiftScheduleAreas,
    visibleReportColumnKeys,
    reportTableColumnWidths,
    reportColumnWidthByKey,
    reportCompletionCards,
  } = useAppReportsModel({
    needsReportRows,
    needsReportIndexes,
    needsAutoReportRows,
    needsAdminReportRows,
    needsDerivedReportRows,
    deferredPtoPlanRows,
    deferredPtoSurveyRows,
    deferredPtoOperRows,
    deferredVehicleRows,
    reportDate,
    reportReasons,
    reportCustomers,
    reportCustomerId,
    setReportCustomerId,
    adminReportCustomerId,
    adminReportCustomerSettingsTab,
    reportArea,
    setReportArea,
    reportAreaOrder,
    reportWorkOrder,
    editingReportFactSourceRowKey,
    areaShiftCutoffs,
    reportHeaderLabels,
    reportColumnWidths,
  });

  const {
    isPtoDateTab,
    isPtoBucketsSection,
    allPtoDateRows,
    ptoYearTabs,
    ptoYearMonths,
    ptoMonthGroups,
    ptoAreaTabs,
    ptoDateOptionMaps,
  } = useAppPtoDateModel({
    renderedTopTab,
    ptoTab,
    ptoPlanYear,
    ptoManualYears,
    expandedPtoMonths,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    deferredPtoPlanRows,
    deferredPtoOperRows,
    deferredPtoSurveyRows,
    ptoBucketManualRows,
  });

  const {
    vehicleAutocompleteOptions,
    activeVehicleFilterOptions,
    filteredVehicleRows,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    activeVehicleFilterCount,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    clearAllVehicleFilters,
    closeVehicleFilterMenu,
  } = useAppVehicleViewModel({
    active: renderedTopTab === "admin" && adminSection === "vehicles",
    adminVehiclesEditing,
    showAllVehicleRows,
    vehiclePreviewRowLimit,
    vehicleRows,
    deferredVehicleRows,
    vehicleFilters,
    openVehicleFilter,
    tableScrollRef: adminVehicleTableScrollRef,
    setAdminVehiclesEditing,
    setShowAllVehicleRows,
    setVehiclePreviewRowLimit,
    vehicleFilterDrafts,
    setOpenVehicleFilter,
    setVehicleFilters,
    setVehicleFilterDrafts,
  });

  const {
    currentDispatchShift,
    isDailyDispatchShift,
    dispatchAreaOptions,
    dispatchVehicleOptions,
    dispatchLocationOptions,
    dispatchWorkTypeOptions,
    dispatchExcavatorOptions,
    filteredDispatchSummaryRows,
    dispatchSummaryTotals,
    dispatchAiSuggestion,
    addSelectedDispatchVehicle,
    addFilteredVehiclesToDispatchSummary,
    updateDispatchSummaryText,
    updateDispatchSummaryNumber,
    updateDispatchSummaryVehicle,
    deleteDispatchSummaryRow,
  } = useAppDispatchSummaryModel({
    active: renderedTopTab === "dispatch",
    areaFilter,
    search,
    dispatchTab,
    reportDate,
    vehicleRows,
    dispatchSummaryRows,
    reportBaseRows,
    dispatchVehicleToAddId,
    setDispatchSummaryRows,
    setDispatchVehicleToAddId,
    addAdminLog,
  });

  const filteredFleet = useFleetRows({
    active: renderedTopTab === "fleet",
    fleetTab,
    vehicleRows,
  });

  const {
    headerNavRef,
    activeHeaderTabRef,
    headerSubtabsRef,
    headerHasSubtabs,
    headerSubtabsOffset,
    activeCustomTab,
    activeDispatchSubtab,
    activePtoSubtab,
  } = useAppActiveNavigation({
    topTab,
    renderedTopTab,
    customTabs,
    subTabs,
    adminSection,
    dispatchTab,
    ptoTab,
    reportCustomerId,
    reportCustomers,
  });
  const {
    viewport: ptoDateViewport,
    scrollRef: ptoDateTableScrollRef,
    updateViewportFromElement: updatePtoDateViewportFromElement,
    handleScroll: handlePtoDateTableScroll,
  } = useAppPtoDateViewport({
    renderedTopTab,
    isPtoDateTab,
    ptoDateEditing,
    expandedPtoMonths,
    ptoTab,
    ptoPlanYear,
    ptoAreaFilter,
    setPtoDateEditing,
    setDraggedPtoRowId,
    setPtoDropTarget,
    setPtoFormulaCell,
    setPtoInlineEditCell,
    setPtoSelectedCellKeys,
  });

  const {
    updateReportCustomer,
    addReportCustomer,
    deleteReportCustomer,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    updateReportCustomerRowLabel,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    removeReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    reportRowsForSummaryArea,
    addReportSummaryRow,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    removeReportSummaryRow,
  } = useAppAdminReportEditors({
    activeAdminReportAreaOptions,
    activeAdminReportBaseRows,
    activeAdminReportCustomer,
    activeAdminReportOrderRows,
    activeAdminReportRowsByKey,
    activeAdminReportSummaryAreaOptions,
    addAdminLog,
    adminReportBaseRows,
    reportAutoRowKeysForCustomer,
    reportCustomers,
    setAdminReportCustomerId,
    setEditingReportRowLabelKeys,
    setExpandedReportSummaryIds,
    setReportCustomerId,
    setReportCustomers,
  });

  const {
    addLinkedPtoDateRow,
    addPtoYear,
    beginPtoRowTextDraft,
    cancelPtoRowTextDraft,
    clearPtoCarryoverOverride,
    commitPtoRowTextDraft,
    deletePtoYear,
    getPtoDropPosition,
    getPtoRowTextDraft,
    moveLinkedPtoDateRow,
    removeLinkedPtoDateRow,
    updatePtoDateDay,
    updatePtoDateRow,
    updatePtoMonthTotal,
    updatePtoRowTextDraft,
  } = useAppPtoDateEditing({
    addAdminLog,
    databaseConfigured,
    ptoAreaFilter,
    ptoDatabaseLoadedRef,
    ptoOperRows,
    ptoPlanRows,
    ptoPlanYear,
    ptoRowFieldDrafts,
    ptoSubTabs: subTabs.pto,
    ptoSurveyRows,
    ptoTab,
    ptoYearInput,
    ptoYearTabs,
    requestPtoDatabaseSave,
    setExpandedPtoMonths,
    setPtoManualYears,
    setPtoOperRows,
    setPtoPlanRows,
    setPtoPlanYear,
    setPtoRowFieldDrafts,
    setPtoSurveyRows,
    setPtoYearDialogOpen,
    setPtoYearInput,
  });

  const {
    addVehicleRow,
    updateVehicleRow,
    toggleVehicleVisibility,
    deleteVehicle,
    vehicleCellInputProps,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    openVehicleImportFilePicker,
    importVehiclesFromExcel,
    exportVehiclesToExcel,
  } = useAppVehicleEditing({
    vehicleRows,
    visibleVehicleRows,
    vehicleRowsRef,
    vehicleImportInputRef,
    vehiclesDatabaseLoadedRef,
    vehiclesDatabaseSaveSnapshotRef,
    databaseConfigured,
    activeVehicleCell,
    selectedVehicleCellKeys,
    editingVehicleCell,
    vehicleCellDraft,
    vehicleCellInitialDraft,
    vehicleSelectionAnchorCell,
    vehicleCellSkipBlurCommitRef,
    vehicleSelectionDraggingRef,
    vehicleSelectionAnchorRef,
    setVehicleRows,
    setVehicleFilters,
    setVehicleFilterDrafts,
    setOpenVehicleFilter,
    setPendingVehicleFocus,
    setActiveVehicleCell,
    setVehicleSelectionAnchorCell,
    setSelectedVehicleCellKeys,
    setEditingVehicleCell,
    setVehicleCellDraft,
    setVehicleCellInitialDraft,
    setAdminVehiclesEditing,
    setShowAllVehicleRows,
    pushVehicleUndoSnapshot,
    clearAllVehicleFilters,
    showSaveStatus,
    addAdminLog,
  });

  const {
    ptoBucketRows,
    ptoBucketColumns,
    openPtoDateImportFilePicker,
    currentPtoDateExcelMeta,
    exportPtoDateTableToExcel,
    importPtoDateTableFromExcel,
    commitPtoBucketValue,
    clearPtoBucketCells,
    addPtoBucketManualRow,
    deletePtoBucketManualRow,
  } = useAppPtoSupplementalTables({
    isPtoBucketsSection,
    allPtoDateRows,
    deferredVehicleRows,
    ptoTab,
    ptoPlanYear,
    ptoAreaFilter,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    ptoBucketManualRows,
    ptoPlanImportInputRef,
    setPtoPlanRows,
    setPtoOperRows,
    setPtoSurveyRows,
    setPtoManualYears,
    setExpandedPtoMonths,
    setPtoBucketValues,
    setPtoBucketManualRows,
    databaseConfigured,
    ptoDatabaseLoadedRef,
    requestPtoDatabaseSave,
    addAdminLog,
  });
  const ptoSectionProps = useAppPtoSectionProps({
    ptoTab,
    activePtoSubtabLabel: activePtoSubtab?.label ?? ptoTab,
    activePtoSubtabContent: activePtoSubtab?.content || "",
    isPtoDateTab,
    ptoAreaTabs,
    ptoAreaFilter,
    ptoBucketRows,
    ptoBucketColumns,
    ptoBucketValues,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    setPtoPlanRows,
    setPtoOperRows,
    setPtoSurveyRows,
    selectPtoArea,
    commitPtoBucketValue,
    clearPtoBucketCells,
    addPtoBucketManualRow,
    deletePtoBucketManualRow,
    ptoPlanYear,
    reportDate,
    ptoYearMonths,
    ptoMonthGroups,
    ptoYearTabs,
    ptoYearDialogOpen,
    ptoYearInput,
    ptoDateEditing,
    ptoColumnWidths,
    ptoRowHeights,
    ptoDateViewport,
    ptoDateOptionMaps,
    ptoDateTableScrollRef,
    ptoPlanImportInputRef,
    draggedPtoRowId,
    ptoDropTarget,
    hoveredPtoAddRowId,
    ptoFormulaCell,
    ptoFormulaDraft,
    ptoInlineEditCell,
    ptoInlineEditInitialDraft,
    ptoSelectionAnchorCell,
    ptoSelectedCellKeys,
    ptoSelectionDraggingRef,
    ptoDraftRowFields,
    editingPtoHeaderKey,
    ptoHeaderDraft,
    setPtoDateEditing,
    setDraggedPtoRowId,
    setPtoDropTarget,
    setPtoFormulaCell,
    setPtoFormulaDraft,
    setPtoInlineEditCell,
    setPtoInlineEditInitialDraft,
    setPtoSelectionAnchorCell,
    setPtoSelectedCellKeys,
    setPtoYearInput,
    setPtoYearDialogOpen,
    setExpandedPtoMonths,
    setHoveredPtoAddRowId,
    setPtoDraftRowFields,
    setPtoPendingFieldFocus,
    setPtoHeaderDraft,
    savePtoLocalState,
    requestPtoDatabaseSave,
    savePtoDatabaseChanges,
    currentPtoDateExcelMeta,
    exportPtoDateTableToExcel,
    openPtoDateImportFilePicker,
    importPtoDateTableFromExcel,
    selectPtoPlanYear,
    deletePtoYear,
    addPtoYear,
    updatePtoDateViewportFromElement,
    handlePtoDateTableScroll,
    startPtoColumnResize,
    startPtoRowResize,
    addLinkedPtoDateRow,
    removeLinkedPtoDateRow,
    getPtoDropPosition,
    moveLinkedPtoDateRow,
    updatePtoDateRow,
    clearPtoCarryoverOverride,
    updatePtoDateDay,
    updatePtoMonthTotal,
    beginPtoRowTextDraft,
    getPtoRowTextDraft,
    updatePtoRowTextDraft,
    commitPtoRowTextDraft,
    cancelPtoRowTextDraft,
    ptoHeaderLabel,
    startPtoHeaderEdit,
    commitPtoHeaderEdit,
    cancelPtoHeaderEdit,
  });
  const adminDatabaseProps = useAppAdminDatabaseProps({
    databaseConfigured,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    ptoBucketManualRows,
    ptoBucketValues,
    vehicleRows,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    createClientSnapshotNow,
    refreshClientSnapshots,
    restoreClientSnapshot,
  });
  const reportsSectionProps = useAppReportsSectionProps({
    reportAreaTabs,
    reportArea,
    setReportArea,
    printReport,
    activeReportCustomer,
    reportDate,
    reportCompletionCards,
    reportTableColumnWidths,
    visibleReportColumnKeys,
    reportColumnWidthByKey,
    reportHeaderLabel,
    renderReportHeaderText,
    startReportColumnResize,
    filteredReportAreaGroups,
    filteredReports,
    reportReasons,
    commitReportDayReason,
    cancelReportDayReasonDraft,
    updateReportDayReasonDraft,
    commitReportYearReason,
    cancelReportYearReasonDraft,
    updateReportYearReasonDraft,
  });
  const dispatchSectionProps = useAppDispatchSectionProps({
    activeDispatchSubtab,
    dispatchTab,
    reportDate,
    isDailyDispatchShift,
    currentDispatchShift,
    dispatchSummaryTotals,
    search,
    setSearch,
    areaFilter,
    setAreaFilter,
    dispatchAreaOptions,
    dispatchVehicleToAddId,
    setDispatchVehicleToAddId,
    dispatchVehicleOptions,
    addSelectedDispatchVehicle,
    addFilteredVehiclesToDispatchSummary,
    dispatchAiSuggestion,
    filteredDispatchSummaryRows,
    updateDispatchSummaryVehicle,
    updateDispatchSummaryText,
    updateDispatchSummaryNumber,
    deleteDispatchSummaryRow,
    dispatchLocationOptions,
    dispatchWorkTypeOptions,
    dispatchExcavatorOptions,
  });
  const adminVehiclesProps = useAppAdminVehiclesProps({
    activeVehicleFilterCount,
    filteredVehicleRows,
    vehicleRows,
    adminVehiclesEditing,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    vehicleAutocompleteOptions,
    vehicleFilterColumns,
    openVehicleFilter,
    activeVehicleFilterOptions,
    vehicleFilters,
    vehicleFilterDrafts,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    adminVehicleTableScrollRef,
    vehicleImportInputRef,
    clearAllVehicleFilters,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    addVehicleRow,
    openVehicleImportFilePicker,
    exportVehiclesToExcel,
    importVehiclesFromExcel,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    closeVehicleFilterMenu,
    toggleVehicleVisibility,
    vehicleCellInputProps,
    updateVehicleRow,
    deleteVehicle,
    setShowAllVehicleRows,
  });
  const adminReportsProps = useAppAdminReportsProps({
    reportCustomers,
    activeAdminReportCustomer,
    visibleAdminReportCustomerSettingsTab,
    activeAdminReportSelectedCount,
    activeAdminReportUsesSummaryRows,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    adminReportWorkOrderGroups,
    activeAdminReportBaseRows,
    activeAdminReportRowsByKey,
    activeAdminReportVisibleRowKeys,
    derivedReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    activeAdminReportRowLabelEntries,
    editingReportRowLabelKeys,
    expandedReportSummaryIds,
    reportRowsForSummaryArea,
    setAdminReportCustomerId,
    addReportCustomer,
    deleteReportCustomer,
    updateReportCustomer,
    setAdminReportCustomerSettingsTab,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    setEditingReportFactSourceRowKey,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    updateReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    removeReportCustomerRowLabel,
    addReportSummaryRow,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    removeReportSummaryRow,
  });
  const adminContentProps = useAppAdminContentProps({
    adminSection,
    topTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    updateCustomTabTitle,
    deleteTopTab,
    showTopTab,
    deleteCustomTab,
    showCustomTab,
    structureSection,
    setStructureSection,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyNodeId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    areaShiftScheduleAreas,
    areaShiftCutoffs,
    updateAreaShiftCutoff,
    adminVehiclesProps,
    adminDatabaseProps,
    adminReportsProps,
    adminLogs,
    lastChangeLog,
    lastUploadLog,
    clearAdminLogs,
  });
  const appHeaderProps = useAppHeaderProps({
    topTabs,
    customTabs,
    topTab,
    subTabs,
    headerHasSubtabs,
    headerSubtabsOffset,
    headerNavRef,
    activeHeaderTabRef,
    headerSubtabsRef,
    reportCustomers,
    reportCustomerId,
    dispatchTab,
    ptoTab,
    adminSection,
    reportDate,
    selectTopTab,
    deleteCustomTab,
    setReportCustomerId,
    setDispatchTab,
    selectPtoTab,
    setAdminSection,
    selectReportDate,
  });
  const shouldGatePtoDatabase = databaseConfigured && !ptoDatabaseReady;

  return (
    <AppPageShell saveStatus={saveStatus} onCloseSaveStatus={hideSaveStatus}>
        <AppHeader {...appHeaderProps} />
        <AppPrimaryContent
          renderedTopTab={renderedTopTab}
          shouldGatePtoDatabase={shouldGatePtoDatabase}
          ptoDatabaseMessage={ptoDatabaseMessage}
          reportsProps={reportsSectionProps}
          dispatchProps={dispatchSectionProps}
          fleetProps={{
            fleetTab,
            subTabs: subTabs.fleet,
            rows: filteredFleet,
            onSelectTab: setFleetTab,
          }}
          contractorsProps={{
            contractorTab,
            subTabs: subTabs.contractors,
            onSelectTab: setContractorTab,
          }}
          fuelProps={{
            fuelTab,
            subTabs: subTabs.fuel,
            onSelectTab: setFuelTab,
          }}
          ptoProps={ptoSectionProps}
          safetyProps={{
            tbTab,
            subTabs: subTabs.tb,
            onSelectTab: setTbTab,
          }}
          userProfileProps={{ userCard: defaultUserCard }}
          adminContent={<AppAdminContent {...adminContentProps} />}
          customTabProps={activeCustomTab ? { tab: activeCustomTab } : null}
        />
    </AppPageShell>
  );
}
