import type { Dispatch, RefObject, SetStateAction } from "react";
import type { AdminLogInput as DomainAdminLogInput } from "@/lib/domain/admin/logs";
import type { UndoSnapshot } from "@/lib/domain/app/undo";
import type { VehicleFilterKey } from "@/lib/domain/vehicles/grid";
import type { PtoFormulaCell } from "@/features/pto/ptoDateFormulaTypes";

export type AdminLogInput = DomainAdminLogInput;
export type SnapshotSetter<Key extends keyof UndoSnapshot> = Dispatch<SetStateAction<UndoSnapshot[Key]>>;

export type AppUndoHistoryOptions = {
  adminDataLoaded: boolean;
  topTab: string;
  adminSection: string;
  databaseConfigured: boolean;
  ptoDatabaseLoadedRef: RefObject<boolean>;
  vehicleRows: UndoSnapshot["vehicleRows"];
  vehicleRowsRef: RefObject<UndoSnapshot["vehicleRows"]>;
  setPtoSaveRevision: Dispatch<SetStateAction<number>>;
  addAdminLog: (entry: AdminLogInput) => void;
  reportCustomers: UndoSnapshot["reportCustomers"];
  reportAreaOrder: UndoSnapshot["reportAreaOrder"];
  reportWorkOrder: UndoSnapshot["reportWorkOrder"];
  reportHeaderLabels: UndoSnapshot["reportHeaderLabels"];
  reportColumnWidths: UndoSnapshot["reportColumnWidths"];
  reportReasons: UndoSnapshot["reportReasons"];
  areaShiftCutoffs: UndoSnapshot["areaShiftCutoffs"];
  customTabs: UndoSnapshot["customTabs"];
  topTabs: UndoSnapshot["topTabs"];
  subTabs: UndoSnapshot["subTabs"];
  ptoManualYears: UndoSnapshot["ptoManualYears"];
  expandedPtoMonths: UndoSnapshot["expandedPtoMonths"];
  ptoPlanRows: UndoSnapshot["ptoPlanRows"];
  ptoSurveyRows: UndoSnapshot["ptoSurveyRows"];
  ptoOperRows: UndoSnapshot["ptoOperRows"];
  ptoColumnWidths: UndoSnapshot["ptoColumnWidths"];
  ptoRowHeights: UndoSnapshot["ptoRowHeights"];
  ptoHeaderLabels: UndoSnapshot["ptoHeaderLabels"];
  ptoBucketValues: UndoSnapshot["ptoBucketValues"];
  ptoBucketManualRows: UndoSnapshot["ptoBucketManualRows"];
  orgMembers: UndoSnapshot["orgMembers"];
  dependencyNodes: UndoSnapshot["dependencyNodes"];
  dependencyLinks: UndoSnapshot["dependencyLinks"];
  setReportCustomers: SnapshotSetter<"reportCustomers">;
  setReportAreaOrder: SnapshotSetter<"reportAreaOrder">;
  setReportWorkOrder: SnapshotSetter<"reportWorkOrder">;
  setReportHeaderLabels: SnapshotSetter<"reportHeaderLabels">;
  setReportColumnWidths: SnapshotSetter<"reportColumnWidths">;
  setReportReasons: SnapshotSetter<"reportReasons">;
  setAreaShiftCutoffs: SnapshotSetter<"areaShiftCutoffs">;
  setCustomTabs: SnapshotSetter<"customTabs">;
  setTopTabs: SnapshotSetter<"topTabs">;
  setSubTabs: SnapshotSetter<"subTabs">;
  setVehicleRows: SnapshotSetter<"vehicleRows">;
  setPtoManualYears: SnapshotSetter<"ptoManualYears">;
  setExpandedPtoMonths: SnapshotSetter<"expandedPtoMonths">;
  setPtoPlanRows: SnapshotSetter<"ptoPlanRows">;
  setPtoSurveyRows: SnapshotSetter<"ptoSurveyRows">;
  setPtoOperRows: SnapshotSetter<"ptoOperRows">;
  setPtoColumnWidths: SnapshotSetter<"ptoColumnWidths">;
  setPtoRowHeights: SnapshotSetter<"ptoRowHeights">;
  setPtoHeaderLabels: SnapshotSetter<"ptoHeaderLabels">;
  setPtoBucketValues: SnapshotSetter<"ptoBucketValues">;
  setPtoBucketManualRows: SnapshotSetter<"ptoBucketManualRows">;
  setOrgMembers: SnapshotSetter<"orgMembers">;
  setDependencyNodes: SnapshotSetter<"dependencyNodes">;
  setDependencyLinks: SnapshotSetter<"dependencyLinks">;
  setEditingVehicleCell: Dispatch<SetStateAction<string | null>>;
  setVehicleCellDraft: Dispatch<SetStateAction<string>>;
  setVehicleCellInitialDraft: Dispatch<SetStateAction<string>>;
  setPtoInlineEditCell: Dispatch<SetStateAction<PtoFormulaCell | null>>;
  setPtoInlineEditInitialDraft: Dispatch<SetStateAction<string>>;
  setPtoFormulaDraft: Dispatch<SetStateAction<string>>;
  setEditingPtoHeaderKey: Dispatch<SetStateAction<string | null>>;
  setPtoHeaderDraft: Dispatch<SetStateAction<string>>;
  setEditingReportHeaderKey: Dispatch<SetStateAction<string | null>>;
  setReportHeaderDraft: Dispatch<SetStateAction<string>>;
  setOpenVehicleFilter: Dispatch<SetStateAction<VehicleFilterKey | null>>;
};
