"use client";

import type { ReactNode } from "react";

import { AppAdminContent } from "@/features/app/AppAdminContent";
import { useAppAdminContentProps } from "@/features/app/useAppAdminContentProps";
import { useAppAdminDatabaseProps } from "@/features/app/useAppAdminDatabaseProps";
import type { useAppAdminReportEditors } from "@/features/app/useAppAdminReportEditors";
import { useAppAdminReportsProps } from "@/features/app/useAppAdminReportsProps";
import { useAppAdminVehiclesProps } from "@/features/app/useAppAdminVehiclesProps";
import type { useAppDerivedModels } from "@/features/app/useAppDerivedModels";
import type { useAppStateBundle } from "@/features/app/useAppStateBundle";
import type { useAppVehicleEditing } from "@/features/app/useAppVehicleEditing";
import { databaseConfigured } from "@/lib/data/config";

type AppStateBundle = ReturnType<typeof useAppStateBundle>;
type AppDerivedModels = ReturnType<typeof useAppDerivedModels>;
type AppAdminReportEditors = ReturnType<typeof useAppAdminReportEditors>;
type AppVehicleEditing = ReturnType<typeof useAppVehicleEditing>;

type UseAppAdminScreenPropsArgs = {
  appState: AppStateBundle;
  models: AppDerivedModels;
  adminReportEditors: AppAdminReportEditors;
  vehicleEditing: AppVehicleEditing;
};

export function useAppAdminScreenProps({
  appState,
  models,
  adminReportEditors,
  vehicleEditing,
}: UseAppAdminScreenPropsArgs): ReactNode {
  const {
    topTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    deleteTopTab,
    showTopTab,
    updateCustomTabTitle,
    showCustomTab,
    deleteCustomTab,
    structureSection,
    setStructureSection,
    adminSection,
    adminVehiclesEditing,
    setShowAllVehicleRows,
    vehicleRows,
    vehicleFilters,
    vehicleFilterDrafts,
    openVehicleFilter,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    vehicleImportInputRef,
    adminVehicleTableScrollRef,
    setAdminReportCustomerId,
    setAdminReportCustomerSettingsTab,
    editingReportRowLabelKeys,
    expandedReportSummaryIds,
    setEditingReportFactSourceRowKey,
    reportCustomers,
    ptoPlanRows,
    ptoSurveyRows,
    ptoOperRows,
    ptoBucketValues,
    ptoBucketManualRows,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    setEditingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    updateAreaShiftCutoff,
    adminLogs,
    clearAdminLogs,
    lastChangeLog,
    lastUploadLog,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    refreshClientSnapshots,
    createClientSnapshotNow,
    restoreClientSnapshot,
  } = appState;

  const {
    activeAdminReportCustomer,
    derivedReportRowsByKey,
    activeAdminReportBaseRows,
    activeAdminReportVisibleRowKeys,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    activeAdminReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    adminReportWorkOrderGroups,
    activeAdminReportSelectedCount,
    activeAdminReportRowLabelEntries,
    activeAdminReportUsesSummaryRows,
    visibleAdminReportCustomerSettingsTab,
    areaShiftScheduleAreas,
    vehicleAutocompleteOptions,
    activeVehicleFilterOptions,
    filteredVehicleRows,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    activeVehicleFilterCount,
    vehicleFilterColumns,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    clearAllVehicleFilters,
    closeVehicleFilterMenu,
  } = models;

  const {
    updateReportCustomer,
    addReportCustomer,
    deleteReportCustomer,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    updateReportCustomerRowLabel,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    removeReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    reportRowsForSummaryArea,
    addReportSummaryRow,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    removeReportSummaryRow,
  } = adminReportEditors;

  const {
    addVehicleRow,
    updateVehicleRow,
    toggleVehicleVisibility,
    deleteVehicle,
    vehicleCellInputProps,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    openVehicleImportFilePicker,
    importVehiclesFromExcel,
    exportVehiclesToExcel,
  } = vehicleEditing;

  const adminDatabaseProps = useAppAdminDatabaseProps({
    databaseConfigured,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    ptoBucketManualRows,
    ptoBucketValues,
    vehicleRows,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    createClientSnapshotNow,
    refreshClientSnapshots,
    restoreClientSnapshot,
  });

  const adminVehiclesProps = useAppAdminVehiclesProps({
    activeVehicleFilterCount,
    filteredVehicleRows,
    vehicleRows,
    adminVehiclesEditing,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    vehicleAutocompleteOptions,
    vehicleFilterColumns,
    openVehicleFilter,
    activeVehicleFilterOptions,
    vehicleFilters,
    vehicleFilterDrafts,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    adminVehicleTableScrollRef,
    vehicleImportInputRef,
    clearAllVehicleFilters,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    addVehicleRow,
    openVehicleImportFilePicker,
    exportVehiclesToExcel,
    importVehiclesFromExcel,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    closeVehicleFilterMenu,
    toggleVehicleVisibility,
    vehicleCellInputProps,
    updateVehicleRow,
    deleteVehicle,
    setShowAllVehicleRows,
  });

  const adminReportsProps = useAppAdminReportsProps({
    reportCustomers,
    activeAdminReportCustomer,
    visibleAdminReportCustomerSettingsTab,
    activeAdminReportSelectedCount,
    activeAdminReportUsesSummaryRows,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    adminReportWorkOrderGroups,
    activeAdminReportBaseRows,
    activeAdminReportRowsByKey,
    activeAdminReportVisibleRowKeys,
    derivedReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    activeAdminReportRowLabelEntries,
    editingReportRowLabelKeys,
    expandedReportSummaryIds,
    reportRowsForSummaryArea,
    setAdminReportCustomerId,
    addReportCustomer,
    deleteReportCustomer,
    updateReportCustomer,
    setAdminReportCustomerSettingsTab,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    setEditingReportFactSourceRowKey,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    updateReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    removeReportCustomerRowLabel,
    addReportSummaryRow,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    removeReportSummaryRow,
  });

  const adminContentProps = useAppAdminContentProps({
    adminSection,
    topTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    updateCustomTabTitle,
    deleteTopTab,
    showTopTab,
    deleteCustomTab,
    showCustomTab,
    structureSection,
    setStructureSection,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyNodeId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    areaShiftScheduleAreas,
    areaShiftCutoffs: appState.areaShiftCutoffs,
    updateAreaShiftCutoff,
    adminVehiclesProps,
    adminDatabaseProps,
    adminReportsProps,
    adminLogs,
    lastChangeLog,
    lastUploadLog,
    clearAdminLogs,
  });

  return <AppAdminContent {...adminContentProps} />;
}
