"use client";

import type { ComponentProps } from "react";

import { AppAdminContent } from "@/features/app/AppAdminContent";
import { AppPrimaryContent } from "@/features/app/AppPrimaryContent";
import { useAppAdminContentProps } from "@/features/app/useAppAdminContentProps";
import { useAppAdminDatabaseProps } from "@/features/app/useAppAdminDatabaseProps";
import type { useAppAdminReportEditors } from "@/features/app/useAppAdminReportEditors";
import { useAppAdminReportsProps } from "@/features/app/useAppAdminReportsProps";
import { useAppAdminVehiclesProps } from "@/features/app/useAppAdminVehiclesProps";
import type { useAppActiveNavigation } from "@/features/app/useAppActiveNavigation";
import type { useAppDerivedModels } from "@/features/app/useAppDerivedModels";
import { useAppDispatchSectionProps } from "@/features/app/useAppDispatchSectionProps";
import { useAppHeaderProps } from "@/features/app/useAppHeaderProps";
import type { useAppPtoDateEditing } from "@/features/app/useAppPtoDateEditing";
import type { useAppPtoDateViewport } from "@/features/app/useAppPtoDateViewport";
import { useAppPtoSectionProps } from "@/features/app/useAppPtoSectionProps";
import type { useAppPtoSupplementalTables } from "@/features/app/useAppPtoSupplementalTables";
import { useAppReportsSectionProps } from "@/features/app/useAppReportsSectionProps";
import type { useAppRuntimeControllers } from "@/features/app/useAppRuntimeControllers";
import type { useAppStateBundle } from "@/features/app/useAppStateBundle";
import type { useAppVehicleEditing } from "@/features/app/useAppVehicleEditing";
import { databaseConfigured } from "@/lib/data/config";
import { defaultUserCard } from "@/lib/domain/reference/defaults";
import { AppHeader } from "@/components/layout/AppHeader";

type AppStateBundle = ReturnType<typeof useAppStateBundle>;
type AppDerivedModels = ReturnType<typeof useAppDerivedModels>;
type AppRuntimeControllers = ReturnType<typeof useAppRuntimeControllers>;
type AppNavigation = ReturnType<typeof useAppActiveNavigation>;
type AppPtoDateViewport = ReturnType<typeof useAppPtoDateViewport>;
type AppAdminReportEditors = ReturnType<typeof useAppAdminReportEditors>;
type AppPtoDateEditing = ReturnType<typeof useAppPtoDateEditing>;
type AppVehicleEditing = ReturnType<typeof useAppVehicleEditing>;
type AppPtoSupplementalTables = ReturnType<typeof useAppPtoSupplementalTables>;

type UseAppScreenPropsArgs = {
  appState: AppStateBundle;
  models: AppDerivedModels;
  runtime: AppRuntimeControllers;
  navigation: AppNavigation;
  ptoDateViewport: AppPtoDateViewport;
  adminReportEditors: AppAdminReportEditors;
  ptoDateEditing: AppPtoDateEditing;
  vehicleEditing: AppVehicleEditing;
  ptoSupplementalTables: AppPtoSupplementalTables;
};

type UseAppScreenPropsResult = {
  appHeaderProps: ComponentProps<typeof AppHeader>;
  primaryContentProps: ComponentProps<typeof AppPrimaryContent>;
};

export function useAppScreenProps({
  appState,
  models,
  runtime,
  navigation,
  ptoDateViewport,
  adminReportEditors,
  ptoDateEditing,
  vehicleEditing,
  ptoSupplementalTables,
}: UseAppScreenPropsArgs): UseAppScreenPropsResult {
  const {
    topTab,
    topTabs,
    subTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    deleteTopTab,
    showTopTab,
    updateCustomTabTitle,
    showCustomTab,
    deleteCustomTab,
    dispatchTab,
    setDispatchTab,
    fleetTab,
    setFleetTab,
    contractorTab,
    setContractorTab,
    fuelTab,
    setFuelTab,
    ptoTab,
    tbTab,
    setTbTab,
    structureSection,
    setStructureSection,
    adminSection,
    setAdminSection,
    dispatchVehicleToAddId,
    setDispatchVehicleToAddId,
    adminVehiclesEditing,
    setShowAllVehicleRows,
    vehicleRows,
    vehicleFilters,
    vehicleFilterDrafts,
    openVehicleFilter,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    vehicleImportInputRef,
    adminVehicleTableScrollRef,
    draggedPtoRowId,
    setDraggedPtoRowId,
    ptoDropTarget,
    setPtoDropTarget,
    ptoFormulaCell,
    setPtoFormulaCell,
    ptoFormulaDraft,
    setPtoFormulaDraft,
    ptoInlineEditCell,
    setPtoInlineEditCell,
    ptoInlineEditInitialDraft,
    setPtoInlineEditInitialDraft,
    ptoSelectionAnchorCell,
    setPtoSelectionAnchorCell,
    ptoSelectedCellKeys,
    setPtoSelectedCellKeys,
    ptoDateEditing: ptoDateEditingEnabled,
    setPtoDateEditing,
    hoveredPtoAddRowId,
    setHoveredPtoAddRowId,
    setPtoPendingFieldFocus,
    ptoDraftRowFields,
    setPtoDraftRowFields,
    ptoSelectionDraggingRef,
    ptoPlanImportInputRef,
    reportArea,
    setReportArea,
    reportCustomerId,
    setReportCustomerId,
    setAdminReportCustomerId,
    setAdminReportCustomerSettingsTab,
    editingReportRowLabelKeys,
    expandedReportSummaryIds,
    setEditingReportFactSourceRowKey,
    reportCustomers,
    reportReasons,
    areaShiftCutoffs,
    ptoPlanYear,
    setPtoYearInput,
    ptoYearInput,
    setPtoYearDialogOpen,
    ptoYearDialogOpen,
    ptoAreaFilter,
    setExpandedPtoMonths,
    ptoPlanRows,
    setPtoPlanRows,
    ptoSurveyRows,
    setPtoSurveyRows,
    ptoOperRows,
    setPtoOperRows,
    ptoColumnWidths,
    ptoRowHeights,
    editingPtoHeaderKey,
    ptoHeaderDraft,
    setPtoHeaderDraft,
    ptoBucketValues,
    ptoBucketManualRows,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    setEditingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    reportDate,
    selectReportDate,
    updateAreaShiftCutoff,
    adminLogs,
    clearAdminLogs,
    lastChangeLog,
    lastUploadLog,
    ptoDatabaseMessage,
    ptoDatabaseReady,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    refreshClientSnapshots,
    createClientSnapshotNow,
    restoreClientSnapshot,
    areaFilter,
    setAreaFilter,
    search,
    setSearch,
    selectTopTab,
    selectPtoTab,
    selectPtoPlanYear,
    selectPtoArea,
  } = appState;

  const {
    renderedTopTab,
    activeAdminReportCustomer,
    derivedReportRowsByKey,
    activeAdminReportBaseRows,
    activeAdminReportVisibleRowKeys,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    activeAdminReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    adminReportWorkOrderGroups,
    activeAdminReportSelectedCount,
    activeAdminReportRowLabelEntries,
    activeAdminReportUsesSummaryRows,
    visibleAdminReportCustomerSettingsTab,
    activeReportCustomer,
    reportAreaTabs,
    filteredReports,
    filteredReportAreaGroups,
    areaShiftScheduleAreas,
    visibleReportColumnKeys,
    reportTableColumnWidths,
    reportColumnWidthByKey,
    reportCompletionCards,
    isPtoDateTab,
    ptoYearTabs,
    ptoYearMonths,
    ptoMonthGroups,
    ptoAreaTabs,
    ptoDateOptionMaps,
    vehicleAutocompleteOptions,
    activeVehicleFilterOptions,
    filteredVehicleRows,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    activeVehicleFilterCount,
    vehicleFilterColumns,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    clearAllVehicleFilters,
    closeVehicleFilterMenu,
    currentDispatchShift,
    isDailyDispatchShift,
    dispatchAreaOptions,
    dispatchVehicleOptions,
    dispatchLocationOptions,
    dispatchWorkTypeOptions,
    dispatchExcavatorOptions,
    filteredDispatchSummaryRows,
    dispatchSummaryTotals,
    dispatchAiSuggestion,
    addSelectedDispatchVehicle,
    addFilteredVehiclesToDispatchSummary,
    updateDispatchSummaryText,
    updateDispatchSummaryNumber,
    updateDispatchSummaryVehicle,
    deleteDispatchSummaryRow,
    filteredFleet,
  } = models;

  const {
    savePtoDatabaseChanges,
    requestPtoDatabaseSave,
    savePtoLocalState,
    commitReportDayReason,
    cancelReportDayReasonDraft,
    updateReportDayReasonDraft,
    commitReportYearReason,
    cancelReportYearReasonDraft,
    updateReportYearReasonDraft,
    cancelPtoHeaderEdit,
    commitPtoHeaderEdit,
    printReport,
    ptoHeaderLabel,
    reportHeaderLabel,
    renderReportHeaderText,
    startPtoHeaderEdit,
    startPtoColumnResize,
    startReportColumnResize,
    startPtoRowResize,
  } = runtime;

  const {
    headerNavRef,
    activeHeaderTabRef,
    headerSubtabsRef,
    headerHasSubtabs,
    headerSubtabsOffset,
    activeCustomTab,
    activeDispatchSubtab,
    activePtoSubtab,
  } = navigation;

  const {
    viewport: ptoDateViewportState,
    scrollRef: ptoDateTableScrollRef,
    updateViewportFromElement: updatePtoDateViewportFromElement,
    handleScroll: handlePtoDateTableScroll,
  } = ptoDateViewport;

  const {
    updateReportCustomer,
    addReportCustomer,
    deleteReportCustomer,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    updateReportCustomerRowLabel,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    removeReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    reportRowsForSummaryArea,
    addReportSummaryRow,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    removeReportSummaryRow,
  } = adminReportEditors;

  const {
    addLinkedPtoDateRow,
    addPtoYear,
    beginPtoRowTextDraft,
    cancelPtoRowTextDraft,
    clearPtoCarryoverOverride,
    commitPtoRowTextDraft,
    deletePtoYear,
    getPtoDropPosition,
    getPtoRowTextDraft,
    moveLinkedPtoDateRow,
    removeLinkedPtoDateRow,
    updatePtoDateDay,
    updatePtoDateRow,
    updatePtoMonthTotal,
    updatePtoRowTextDraft,
  } = ptoDateEditing;

  const {
    addVehicleRow,
    updateVehicleRow,
    toggleVehicleVisibility,
    deleteVehicle,
    vehicleCellInputProps,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    openVehicleImportFilePicker,
    importVehiclesFromExcel,
    exportVehiclesToExcel,
  } = vehicleEditing;

  const {
    ptoBucketRows,
    ptoBucketColumns,
    openPtoDateImportFilePicker,
    currentPtoDateExcelMeta,
    exportPtoDateTableToExcel,
    importPtoDateTableFromExcel,
    commitPtoBucketValue,
    clearPtoBucketCells,
    addPtoBucketManualRow,
    deletePtoBucketManualRow,
  } = ptoSupplementalTables;

  const ptoSectionProps = useAppPtoSectionProps({
    ptoTab,
    activePtoSubtabLabel: activePtoSubtab?.label ?? ptoTab,
    activePtoSubtabContent: activePtoSubtab?.content || "",
    isPtoDateTab,
    ptoAreaTabs,
    ptoAreaFilter,
    ptoBucketRows,
    ptoBucketColumns,
    ptoBucketValues,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    setPtoPlanRows,
    setPtoOperRows,
    setPtoSurveyRows,
    selectPtoArea,
    commitPtoBucketValue,
    clearPtoBucketCells,
    addPtoBucketManualRow,
    deletePtoBucketManualRow,
    ptoPlanYear,
    reportDate,
    ptoYearMonths,
    ptoMonthGroups,
    ptoYearTabs,
    ptoYearDialogOpen,
    ptoYearInput,
    ptoDateEditing: ptoDateEditingEnabled,
    ptoColumnWidths,
    ptoRowHeights,
    ptoDateViewport: ptoDateViewportState,
    ptoDateOptionMaps,
    ptoDateTableScrollRef,
    ptoPlanImportInputRef,
    draggedPtoRowId,
    ptoDropTarget,
    hoveredPtoAddRowId,
    ptoFormulaCell,
    ptoFormulaDraft,
    ptoInlineEditCell,
    ptoInlineEditInitialDraft,
    ptoSelectionAnchorCell,
    ptoSelectedCellKeys,
    ptoSelectionDraggingRef,
    ptoDraftRowFields,
    editingPtoHeaderKey,
    ptoHeaderDraft,
    setPtoDateEditing,
    setDraggedPtoRowId,
    setPtoDropTarget,
    setPtoFormulaCell,
    setPtoFormulaDraft,
    setPtoInlineEditCell,
    setPtoInlineEditInitialDraft,
    setPtoSelectionAnchorCell,
    setPtoSelectedCellKeys,
    setPtoYearInput,
    setPtoYearDialogOpen,
    setExpandedPtoMonths,
    setHoveredPtoAddRowId,
    setPtoDraftRowFields,
    setPtoPendingFieldFocus,
    setPtoHeaderDraft,
    savePtoLocalState,
    requestPtoDatabaseSave,
    savePtoDatabaseChanges,
    currentPtoDateExcelMeta,
    exportPtoDateTableToExcel,
    openPtoDateImportFilePicker,
    importPtoDateTableFromExcel,
    selectPtoPlanYear,
    deletePtoYear,
    addPtoYear,
    updatePtoDateViewportFromElement,
    handlePtoDateTableScroll,
    startPtoColumnResize,
    startPtoRowResize,
    addLinkedPtoDateRow,
    removeLinkedPtoDateRow,
    getPtoDropPosition,
    moveLinkedPtoDateRow,
    updatePtoDateRow,
    clearPtoCarryoverOverride,
    updatePtoDateDay,
    updatePtoMonthTotal,
    beginPtoRowTextDraft,
    getPtoRowTextDraft,
    updatePtoRowTextDraft,
    commitPtoRowTextDraft,
    cancelPtoRowTextDraft,
    ptoHeaderLabel,
    startPtoHeaderEdit,
    commitPtoHeaderEdit,
    cancelPtoHeaderEdit,
  });

  const adminDatabaseProps = useAppAdminDatabaseProps({
    databaseConfigured,
    ptoPlanRows,
    ptoOperRows,
    ptoSurveyRows,
    ptoBucketManualRows,
    ptoBucketValues,
    vehicleRows,
    clientSnapshots,
    databasePanelMessage,
    databasePanelLoading,
    createClientSnapshotNow,
    refreshClientSnapshots,
    restoreClientSnapshot,
  });

  const reportsSectionProps = useAppReportsSectionProps({
    reportAreaTabs,
    reportArea,
    setReportArea,
    printReport,
    activeReportCustomer,
    reportDate,
    reportCompletionCards,
    reportTableColumnWidths,
    visibleReportColumnKeys,
    reportColumnWidthByKey,
    reportHeaderLabel,
    renderReportHeaderText,
    startReportColumnResize,
    filteredReportAreaGroups,
    filteredReports,
    reportReasons,
    commitReportDayReason,
    cancelReportDayReasonDraft,
    updateReportDayReasonDraft,
    commitReportYearReason,
    cancelReportYearReasonDraft,
    updateReportYearReasonDraft,
  });

  const dispatchSectionProps = useAppDispatchSectionProps({
    activeDispatchSubtab,
    dispatchTab,
    reportDate,
    isDailyDispatchShift,
    currentDispatchShift,
    dispatchSummaryTotals,
    search,
    setSearch,
    areaFilter,
    setAreaFilter,
    dispatchAreaOptions,
    dispatchVehicleToAddId,
    setDispatchVehicleToAddId,
    dispatchVehicleOptions,
    addSelectedDispatchVehicle,
    addFilteredVehiclesToDispatchSummary,
    dispatchAiSuggestion,
    filteredDispatchSummaryRows,
    updateDispatchSummaryVehicle,
    updateDispatchSummaryText,
    updateDispatchSummaryNumber,
    deleteDispatchSummaryRow,
    dispatchLocationOptions,
    dispatchWorkTypeOptions,
    dispatchExcavatorOptions,
  });

  const adminVehiclesProps = useAppAdminVehiclesProps({
    activeVehicleFilterCount,
    filteredVehicleRows,
    vehicleRows,
    adminVehiclesEditing,
    visibleVehicleRows,
    hiddenVehicleRowsCount,
    vehicleAutocompleteOptions,
    vehicleFilterColumns,
    openVehicleFilter,
    activeVehicleFilterOptions,
    vehicleFilters,
    vehicleFilterDrafts,
    vehicleFilterSearch,
    setVehicleFilterSearch,
    adminVehicleTableScrollRef,
    vehicleImportInputRef,
    clearAllVehicleFilters,
    startAdminVehiclesEditing,
    finishAdminVehiclesEditing,
    addVehicleRow,
    openVehicleImportFilePicker,
    exportVehiclesToExcel,
    importVehiclesFromExcel,
    openVehicleFilterMenu,
    toggleVehicleFilterDraftValue,
    selectAllVehicleFilterDraftValues,
    deselectAllVehicleFilterDraftValues,
    applyVehicleFilter,
    closeVehicleFilterMenu,
    toggleVehicleVisibility,
    vehicleCellInputProps,
    updateVehicleRow,
    deleteVehicle,
    setShowAllVehicleRows,
  });

  const adminReportsProps = useAppAdminReportsProps({
    reportCustomers,
    activeAdminReportCustomer,
    visibleAdminReportCustomerSettingsTab,
    activeAdminReportSelectedCount,
    activeAdminReportUsesSummaryRows,
    activeAdminReportAreaOptions,
    activeAdminReportSummaryAreaOptions,
    adminReportWorkOrderGroups,
    activeAdminReportBaseRows,
    activeAdminReportRowsByKey,
    activeAdminReportVisibleRowKeys,
    derivedReportRowsByKey,
    editingReportFactSourceRow,
    editingReportFactSourceOptions,
    activeAdminReportRowLabelEntries,
    editingReportRowLabelKeys,
    expandedReportSummaryIds,
    reportRowsForSummaryArea,
    setAdminReportCustomerId,
    addReportCustomer,
    deleteReportCustomer,
    updateReportCustomer,
    setAdminReportCustomerSettingsTab,
    moveReportAreaOrder,
    moveReportWorkOrder,
    toggleReportCustomerRow,
    setEditingReportFactSourceRowKey,
    setReportCustomerFactSourceMode,
    toggleReportCustomerFactSourceRowKey,
    addReportCustomerRowLabel,
    changeReportCustomerRowLabelSource,
    updateReportCustomerRowLabel,
    startReportRowLabelEdit,
    finishReportRowLabelEdit,
    removeReportCustomerRowLabel,
    addReportSummaryRow,
    updateReportSummaryRow,
    toggleReportSummaryRowKey,
    startReportSummaryEdit,
    finishReportSummaryEdit,
    removeReportSummaryRow,
  });

  const adminContentProps = useAppAdminContentProps({
    adminSection,
    topTabs,
    customTabs,
    addCustomTab,
    updateTopTabLabel,
    updateCustomTabTitle,
    deleteTopTab,
    showTopTab,
    deleteCustomTab,
    showCustomTab,
    structureSection,
    setStructureSection,
    dependencyNodes,
    dependencyLinks,
    dependencyNodeForm,
    dependencyLinkForm,
    editingDependencyNodeId,
    editingDependencyLinkId,
    setEditingDependencyNodeId,
    setEditingDependencyLinkId,
    updateDependencyNode,
    updateDependencyNodeForm,
    addDependencyNode,
    deleteDependencyNode,
    updateDependencyLink,
    updateDependencyLinkForm,
    addDependencyLink,
    deleteDependencyLink,
    orgMembers,
    orgMemberForm,
    editingOrgMemberId,
    setEditingOrgMemberId,
    updateOrgMember,
    updateOrgMemberForm,
    addOrgMember,
    deleteOrgMember,
    areaShiftScheduleAreas,
    areaShiftCutoffs,
    updateAreaShiftCutoff,
    adminVehiclesProps,
    adminDatabaseProps,
    adminReportsProps,
    adminLogs,
    lastChangeLog,
    lastUploadLog,
    clearAdminLogs,
  });

  const appHeaderProps = useAppHeaderProps({
    topTabs,
    customTabs,
    topTab,
    subTabs,
    headerHasSubtabs,
    headerSubtabsOffset,
    headerNavRef,
    activeHeaderTabRef,
    headerSubtabsRef,
    reportCustomers,
    reportCustomerId,
    dispatchTab,
    ptoTab,
    adminSection,
    reportDate,
    selectTopTab,
    deleteCustomTab,
    setReportCustomerId,
    setDispatchTab,
    selectPtoTab,
    setAdminSection,
    selectReportDate,
  });

  return {
    appHeaderProps,
    primaryContentProps: {
      renderedTopTab,
      shouldGatePtoDatabase: databaseConfigured && !ptoDatabaseReady,
      ptoDatabaseMessage,
      reportsProps: reportsSectionProps,
      dispatchProps: dispatchSectionProps,
      fleetProps: {
        fleetTab,
        subTabs: subTabs.fleet,
        rows: filteredFleet,
        onSelectTab: setFleetTab,
      },
      contractorsProps: {
        contractorTab,
        subTabs: subTabs.contractors,
        onSelectTab: setContractorTab,
      },
      fuelProps: {
        fuelTab,
        subTabs: subTabs.fuel,
        onSelectTab: setFuelTab,
      },
      ptoProps: ptoSectionProps,
      safetyProps: {
        tbTab,
        subTabs: subTabs.tb,
        onSelectTab: setTbTab,
      },
      userProfileProps: { userCard: defaultUserCard },
      adminContent: <AppAdminContent {...adminContentProps} />,
      customTabProps: activeCustomTab ? { tab: activeCustomTab } : null,
    },
  };
}
