"use client";

import { useEffect, useRef } from "react";
import { runInitialAppDataLoad, type InitialAppDataLoadOptions } from "@/features/app/initialAppDataLoadSteps";

export function useInitialAppDataLoad({
  defaultSubTabs,
  restoreAdminLogs,
  appDatabaseSaveSnapshotRef,
  appSettingsDatabaseLoadedRef,
  appSettingsDatabaseSaveSnapshotRef,
  vehiclesDatabaseLoadedRef,
  vehiclesDatabaseSaveSnapshotRef,
  hasStoredPtoStateRef,
  setPtoDatabaseLoadStarted,
  setPtoBootstrapLoaded,
  setAdminDataLoaded,
  setReportCustomers,
  setReportAreaOrder,
  setReportWorkOrder,
  setReportHeaderLabels,
  setReportColumnWidths,
  setReportReasons,
  setAreaShiftCutoffs,
  setCustomTabs,
  setTopTabs,
  setSubTabs,
  setVehicleRows,
  setDispatchSummaryRows,
  setPtoManualYears,
  setPtoPlanRows,
  setPtoSurveyRows,
  setPtoOperRows,
  setPtoColumnWidths,
  setPtoRowHeights,
  setPtoHeaderLabels,
  setPtoBucketValues,
  setPtoBucketManualRows,
  setOrgMembers,
  setDependencyNodes,
  setDependencyLinks,
  setDependencyLinkForm,
}: InitialAppDataLoadOptions) {
  const loadStartedRef = useRef(false);

  useEffect(() => {
    let cancelled = false;

    queueMicrotask(() => {
      if (cancelled || loadStartedRef.current) return;
      loadStartedRef.current = true;

      void runInitialAppDataLoad({
        defaultSubTabs,
        restoreAdminLogs,
        appDatabaseSaveSnapshotRef,
        appSettingsDatabaseLoadedRef,
        appSettingsDatabaseSaveSnapshotRef,
        vehiclesDatabaseLoadedRef,
        vehiclesDatabaseSaveSnapshotRef,
        hasStoredPtoStateRef,
        setPtoDatabaseLoadStarted,
        setPtoBootstrapLoaded,
        setAdminDataLoaded,
        setReportCustomers,
        setReportAreaOrder,
        setReportWorkOrder,
        setReportHeaderLabels,
        setReportColumnWidths,
        setReportReasons,
        setAreaShiftCutoffs,
        setCustomTabs,
        setTopTabs,
        setSubTabs,
        setVehicleRows,
        setDispatchSummaryRows,
        setPtoManualYears,
        setPtoPlanRows,
        setPtoSurveyRows,
        setPtoOperRows,
        setPtoColumnWidths,
        setPtoRowHeights,
        setPtoHeaderLabels,
        setPtoBucketValues,
        setPtoBucketManualRows,
        setOrgMembers,
        setDependencyNodes,
        setDependencyLinks,
        setDependencyLinkForm,
        isCancelled: () => cancelled,
      });
    });

    return () => {
      cancelled = true;
    };
  }, [
    appDatabaseSaveSnapshotRef,
    appSettingsDatabaseLoadedRef,
    appSettingsDatabaseSaveSnapshotRef,
    defaultSubTabs,
    hasStoredPtoStateRef,
    setPtoDatabaseLoadStarted,
    restoreAdminLogs,
    setAdminDataLoaded,
    setAreaShiftCutoffs,
    setCustomTabs,
    setDependencyLinkForm,
    setDependencyLinks,
    setDependencyNodes,
    setDispatchSummaryRows,
    setOrgMembers,
    setPtoBucketManualRows,
    setPtoBucketValues,
    setPtoBootstrapLoaded,
    setPtoColumnWidths,
    setPtoHeaderLabels,
    setPtoManualYears,
    setPtoOperRows,
    setPtoPlanRows,
    setPtoRowHeights,
    setPtoSurveyRows,
    setReportAreaOrder,
    setReportColumnWidths,
    setReportCustomers,
    setReportHeaderLabels,
    setReportReasons,
    setReportWorkOrder,
    setSubTabs,
    setTopTabs,
    setVehicleRows,
    vehiclesDatabaseLoadedRef,
    vehiclesDatabaseSaveSnapshotRef,
  ]);
}
