import fs from 'node:fs';
import path from 'node:path';
import {JSDOM,VirtualConsole} from 'jsdom';

const root=path.resolve('app/src/main/assets');
const htmlSource=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scriptSources=[...htmlSource.matchAll(/<script[^>]+src="([^"]+)"[^>]*><\/script>/g)].map(match=>match[1]);
const html=htmlSource.replace(/<script[^>]+src="[^"]+"[^>]*><\/script>/g,'');
const javaSource=fs.readFileSync(path.resolve('app/src/main/java/kz/shtabai/app/MainActivity.java'),'utf8');
const errors=[],virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',error=>errors.push(String(error.message||error)));virtualConsole.on('error',error=>errors.push(String(error)));
const dom=new JSDOM(html,{url:'https://shtab-ai.local/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole}),{window}=dom;
window.console.error=(...args)=>errors.push(args.map(String).join(' '));window.confirm=()=>{throw new Error('Native confirm forbidden')};window.prompt=()=>{throw new Error('Native prompt forbidden')};window.alert=()=>{};window.requestAnimationFrame=callback=>setTimeout(callback,0);window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLElement.prototype.showModal=function(){this.open=true;this.setAttribute('open','')};window.HTMLElement.prototype.close=function(){this.open=false;this.removeAttribute('open')};Object.defineProperty(window.navigator,'clipboard',{value:{writeText:async()=>{}},configurable:true});
let permissionRequests=0;window.Android={requestInitialPermissions(){permissionRequests++},requestNotifications(){},requestExactAlarmPermission(){},scheduleNotification(){},cancelNotification(){},startVoiceInput(){},speak(){},showToast(){}};
const scriptParts=[];
for(const source of scriptSources){
  if(source==='chunk22.js')scriptParts.push(`
    const __today=dayKey(today),__tomorrow=dayKey(addDays(today,1));
    if(!state.tasks.length){state.tasks.push({id:uid('task'),kind:'assignment',title:'Длинный заголовок поручения для проверки визуального разделения и переноса текста',description:'Подробное описание должно быть отдельным уровнем, а не сливаться с заголовком.',date:__today,endDate:__tomorrow,time:'09:00',duration:60,project:'',priority:'high',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[60],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()});}
    Object.assign(state.tasks[0],{kind:'assignment',title:'Длинный заголовок поручения для проверки визуального разделения и переноса текста',description:'Подробное описание должно быть отдельным уровнем, а не сливаться с заголовком.',date:__today,endDate:__tomorrow,time:'09:00',duration:60,priority:'high',reminders:[60]});
    window.__preserveTaskId=state.tasks[0].id;
    state.tasks[0].tags=['скрытая метка'];
    state.tasks[0].subtasks=[{id:'preserve-sub',title:'Скрытая подзадача',done:false}];
    state.tasks.push({id:uid('task'),kind:'event',title:'Обычное событие',description:'',date:__today,endDate:__today,time:'12:00',duration:45,project:'',priority:'normal',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()});
    state.tasks.push({id:uid('task'),kind:'task',title:'Задача низкой важности',description:'',date:__today,endDate:__today,time:'16:00',duration:30,project:'',priority:'low',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()});
  `);
  scriptParts.push(fs.readFileSync(path.join(root,source),'utf8'));
}
try{window.eval(scriptParts.join('\n;\n'))}catch(error){errors.push(`initialization: ${error.stack||error}`)}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),assert=(value,message)=>{if(!value)throw new Error(message)},run=async(name,test)=>{try{await test();console.log(`✓ ${name}`)}catch(error){errors.push(`${name}: ${error.stack||error}`);console.log(`✕ ${name}`)}};
const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,now=new Date(),todayKey=iso(now),tomorrowKey=iso(new Date(now.getFullYear(),now.getMonth(),now.getDate()+1)),tripEndKey=iso(new Date(now.getFullYear(),now.getMonth(),now.getDate()+3));
function auditButtons(rootNode=window.document){rootNode.querySelectorAll('button').forEach(button=>assert(button.getAttribute('type'),`Button type missing: ${button.textContent.trim()}`))}
function auditHandlers(rootNode=window.document){const ignored=new Set(['if','for','while','switch','catch','function','setTimeout']);rootNode.querySelectorAll('[onclick]').forEach(element=>{const code=element.getAttribute('onclick')||'';for(const match of code.matchAll(/(?<![\w$.])([A-Za-z_$][\w$]*)\s*\(/g)){const name=match[1];if(ignored.has(name))continue;let value;try{value=window.eval(name)}catch{value=undefined}assert(typeof value==='function',`Unresolved onclick function ${name}: ${code}`)}})}

await run('script order and v2.9 patch',async()=>{const guard=scriptSources.indexOf('chunk22.js'),interfacePatch=scriptSources.indexOf('chunk21.js'),hierarchy=scriptSources.indexOf('chunk23.js'),final=scriptSources.indexOf('chunk24.js');assert(guard>0&&interfacePatch>guard&&hierarchy>interfacePatch&&final>hierarchy,'Task data/UI patches are in the wrong order');assert(window.__shtabDiagnostics.uiVersion()==='2.9.0','UI version is not 2.9.0')});
await run('fixed top header and navigation',async()=>{const style=[...window.document.querySelectorAll('style')].map(node=>node.textContent).join('\n');assert(style.includes('.topbar{position:fixed!important'),'Top header is not fixed');assert(style.includes('.app-shell{padding-top:'),'Content offset for fixed header missing');const pages=[...window.document.querySelectorAll('.nav-item')].map(item=>item.dataset.page);assert(pages.join(',')==='today,plan,analytics,finance,more','Bottom navigation is incorrect');window.document.querySelector('#assistant-btn').click();assert(window.document.querySelector('#assistant.active'),'Top assistant button failed');auditButtons();auditHandlers()});
await run('first-launch permissions remain safe',async()=>{await wait(650);assert(permissionRequests===1,'Initial permissions not requested once');assert(javaSource.includes('POST_NOTIFICATIONS')&&javaSource.includes('RECORD_AUDIO')&&javaSource.includes('ACTION_REQUEST_SCHEDULE_EXACT_ALARM'),'Required permissions incomplete');assert(!javaSource.includes('ACCESS_FINE_LOCATION')&&!javaSource.includes('READ_CONTACTS'),'Unnecessary permissions requested')});
await run('hidden task details survive simplified form and edit',async()=>{let details=window.__shtabDiagnostics.taskHiddenDetails(window.__preserveTaskId);assert(details?.tags?.[0]==='скрытая метка','Existing hidden tag was erased during migration');assert(details?.subtasks?.[0]?.title==='Скрытая подзадача','Existing hidden subtask was erased during migration');window.openEditor('task',window.__preserveTaskId);await wait(20);const form=window.document.querySelector('#editor-form');assert(!form.elements.tags&&!form.elements.subtasks,'Hidden fields remain visible');form.elements.title.value=`${form.elements.title.value} обновлено`;form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));details=window.__shtabDiagnostics.taskHiddenDetails(window.__preserveTaskId);assert(details?.tags?.[0]==='скрытая метка','Existing hidden tag was erased after edit');assert(details?.subtasks?.[0]?.title==='Скрытая подзадача','Existing hidden subtask was erased after edit')});
await run('Today has balanced task hierarchy',async()=>{window.setPage('today');const page=window.document.querySelector('#today'),records=[...page.querySelectorAll('[data-task-record]')],style=[...window.document.querySelectorAll('style')].map(node=>node.textContent).join('\n');assert(page.querySelector('.today-section-v29'),'Structured Today section missing');assert(records.length>=3,'Task records missing on Today');assert(records[0].querySelector('.record-title-v29')?.textContent.includes('Длинный заголовок'),'Task title missing');assert(records[0].querySelector('.record-type-v29.assignment'),'Assignment type icon missing');assert(records[0].querySelector('.record-priority-v29.high'),'High-priority icon missing');assert(page.querySelector('.record-priority-v29.normal'),'Normal-priority icon missing');assert(page.querySelector('.record-priority-v29.low'),'Low-priority icon missing');assert(records[0].querySelector('.record-meta-v29 .period')?.textContent.includes('—'),'Multi-day period missing');assert(records[0].querySelector('.record-meta-v29')?.textContent.includes('09:00')&&records[0].querySelector('.record-meta-v29')?.textContent.includes('10:00'),'Start/end time missing');assert(records[0].querySelector('.record-description-v29'),'Description is not separated');assert(style.includes('.record-title-v29{font-size:13px')&&style.includes('white-space:normal')&&style.includes('-webkit-line-clamp:2'),'Title wrapping hierarchy missing');assert(!page.querySelector('.today-row'),'Over-simplified v2.8 task rows remain');auditButtons(page);auditHandlers(page)});
await run('task form keeps period and timer wheel',async()=>{window.openEditor('task');await wait(20);const form=window.document.querySelector('#editor-form'),dialog=window.document.querySelector('#editor-dialog');assert(form.elements.date&&form.elements.startTime&&form.elements.endDate&&form.elements.endTime,'Period and time fields incomplete');assert(!form.elements.time&&!form.elements.duration&&!form.elements.tags&&!form.elements.subtasks,'Removed task fields remain');assert(form.elements.reminderEnabled&&form.elements.reminderHours&&form.elements.reminderMinutes,'Reminder wheel missing');form.elements.reminderEnabled.checked=true;window.refreshTaskReminderV28();form.elements.reminderHours.value='2';form.elements.reminderMinutes.value='35';window.refreshTaskReminderV28();assert(window.document.querySelector('#task-reminder-preview').textContent.includes('2 ч')&&window.document.querySelector('#task-reminder-preview').textContent.includes('35 мин'),'Reminder preview incorrect');form.elements.kind.value='trip';form.elements.title.value='Командировка 2.9';form.elements.date.value=tomorrowKey;form.elements.startTime.value='08:30';form.elements.endDate.value=tripEndKey;form.elements.endTime.value='18:15';form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));const task=window.__shtabDiagnostics.taskByTitle('Командировка 2.9');assert(task?.startTime==='08:30'&&task.endTime==='18:15','Task start/end time not saved');assert(task.reminders?.[0]===155,'Reminder wheel offset not saved');assert(!dialog.open,'Task dialog did not close')});
await run('Plan uses same hierarchy and periods',async()=>{window.setPage('today');window.setPage('plan');let plan=window.document.querySelector('#plan');assert(window.__shtabDiagnostics.planView()==='week','Plan did not open in week mode');assert(plan.querySelectorAll('.plan-week-day-v29').length===7,'Weekly plan does not show seven days');const record=plan.querySelector(`[data-task-record="${window.__preserveTaskId}"]`);assert(record,'Existing task missing from weekly plan');assert(record.querySelector('.record-title-v29')&&record.querySelector('.record-type-v29')&&record.querySelector('.record-priority-v29')&&record.querySelector('.record-meta-v29 .period'),'Plan does not share task hierarchy');assert(plan.querySelectorAll('.plan-view-tabs button').length===3,'Week/month/period switch missing');window.setPlanViewV28('month');plan=window.document.querySelector('#plan');assert(plan.querySelector('.month-grid'),'Month view missing');window.setPlanViewV28('period');plan=window.document.querySelector('#plan');assert(plan.querySelectorAll('.period-picker input[type=date]').length===2,'Period picker missing');auditButtons(plan);auditHandlers(plan)});
await run('general task cards keep hierarchy',async()=>{const task=window.__shtabDiagnostics.taskByTitle('Длинный заголовок поручения для проверки визуального разделения и переноса текста обновлено');const holder=window.document.createElement('div');holder.innerHTML=window.taskCard(task,todayKey);const card=holder.firstElementChild;assert(card.classList.contains('record-card-v29'),'General task card did not use v2.9 style');assert(card.querySelector('.record-type-v29')&&card.querySelector('.record-priority-v29')&&card.querySelector('.record-meta-v29 .period'),'General task card hierarchy incomplete')});
await run('Analytics tabs share one visual system',async()=>{window.setPage('analytics');for(const section of ['tasks','trips','projects']){window.setAnalyticsSectionV27(section);const page=window.document.querySelector('#analytics');assert(page.querySelector('.analytics-unified-grid'),'Unified metric grid missing');assert(page.querySelectorAll('.analytics-metric-v28').length===4,`Metric card count differs for ${section}`);assert(page.querySelector('.analytics-list-v28'),`Unified list card missing for ${section}`);auditButtons(page);auditHandlers(page)}});
await run('Finance and More regressions',async()=>{window.setPage('finance');const finance=window.document.querySelector('#finance');assert(window.__shtabDiagnostics.financeSummaryCount()===1&&finance.querySelector('.finance-summary-v28'),'Unified finance summary missing');assert(finance.querySelector('[aria-label="Изменить бюджет"]')?.textContent.includes('✎'),'Budget edit pencil missing');window.setPage('more');const more=window.document.querySelector('#more');assert(![...more.querySelectorAll('.module-card h3')].some(node=>['Диагностика','Аналитика задач'].includes(node.textContent.trim())),'Removed More modules returned');assert(more.textContent.includes('2.9.0'),'Visible app version was not updated');auditButtons(more);auditHandlers(more)});
await run('all pages render without JavaScript errors',async()=>{for(const pageName of ['today','plan','analytics','finance','more','assistant']){window.setPage(pageName);assert(window.document.querySelector(`#${pageName}.active`),`${pageName} inactive`);auditButtons();auditHandlers()}});

if(errors.length){console.log('\nAudit failures:');errors.forEach(error=>console.log(`- ${error}`));process.exit(1)}
console.log('\nAll v2.9 hierarchy, priority, period, planning and regression tests passed.');