import fs from 'node:fs';
import path from 'node:path';
import {JSDOM,VirtualConsole} from 'jsdom';

const root=path.resolve('app/src/main/assets');
const htmlSource=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scriptSources=[...htmlSource.matchAll(/<script[^>]+src="([^"]+)"[^>]*><\/script>/g)].map(match=>match[1]);
const html=htmlSource.replace(/<script[^>]+src="[^"]+"[^>]*><\/script>/g,'');
const javaSource=fs.readFileSync(path.resolve('app/src/main/java/kz/shtabai/app/MainActivity.java'),'utf8');
const errors=[],virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',error=>errors.push(String(error.message||error)));virtualConsole.on('error',error=>errors.push(String(error)));
const dom=new JSDOM(html,{url:'https://shtab-ai.local/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole}),{window}=dom;
window.console.error=(...args)=>errors.push(args.map(String).join(' '));window.confirm=()=>{throw new Error('Native confirm forbidden')};window.prompt=()=>{throw new Error('Native prompt forbidden')};window.alert=()=>{};window.requestAnimationFrame=callback=>setTimeout(callback,0);window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLElement.prototype.showModal=function(){this.open=true;this.setAttribute('open','')};window.HTMLElement.prototype.close=function(){this.open=false;this.removeAttribute('open')};Object.defineProperty(window.navigator,'clipboard',{value:{writeText:async()=>{}},configurable:true});
let permissionRequests=0;window.Android={requestInitialPermissions(){permissionRequests++},requestNotifications(){},requestExactAlarmPermission(){},scheduleNotification(){},cancelNotification(){},startVoiceInput(){},speak(){},showToast(){}};
const scriptParts=[];
for(const source of scriptSources){
  if(source==='chunk22.js')scriptParts.push(`
    const __today=dayKey(today),__tomorrow=dayKey(addDays(today,1)),__tripEnd=dayKey(addDays(today,3));
    if(!state.areas.length)state.areas.push({id:uid('area'),name:'Тестовая сфера',icon:'●',color:'#7d65ff'});
    Object.assign(state.areas[0],{name:'Тестовая сфера',icon:'◆'});
    if(!state.projects.length)state.projects.push({id:uid('project'),name:'Проект контроля',description:'Скрытое описание',area:state.areas[0].id,color:'#7d65ff',status:'active',createdAt:Date.now()});
    Object.assign(state.projects[0],{name:'Проект контроля',area:state.areas[0].id,status:'active'});window.__projectId=state.projects[0].id;
    if(!state.tasks.length)state.tasks.push({id:uid('task'),kind:'assignment',title:'Важное поручение',description:'Описание важного поручения',date:__today,endDate:__tomorrow,time:'09:00',duration:60,project:window.__projectId,priority:'high',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[60],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()});
    Object.assign(state.tasks[0],{kind:'assignment',title:'Важное поручение',description:'Описание важного поручения',date:__today,endDate:__tomorrow,time:'09:00',duration:60,project:window.__projectId,priority:'high',reminders:[60],status:'active'});
    window.__preserveTaskId=state.tasks[0].id;state.tasks[0].tags=['скрытая метка'];state.tasks[0].subtasks=[{id:'preserve-sub',title:'Скрытая подзадача',done:false}];
    const __event={id:uid('task'),kind:'event',title:'Обычное событие сегодня',description:'Описание события',date:__today,endDate:__today,time:'23:59',duration:45,project:window.__projectId,priority:'normal',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()};state.tasks.push(__event);window.__eventId=__event.id;
    const __tomorrowTask={id:uid('task'),kind:'task',title:'Задача только завтра',description:'',date:__tomorrow,endDate:__tomorrow,time:'14:00',duration:30,project:'',priority:'low',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()};state.tasks.push(__tomorrowTask);window.__tomorrowTaskId=__tomorrowTask.id;
    const __trip={id:uid('task'),kind:'trip',title:'Важная командировка',description:'',date:__today,endDate:__tripEnd,time:'08:30',duration:600,project:window.__projectId,priority:'high',tags:[],subtasks:[],recurrence:{type:'none',interval:1},recurrenceEnd:'',reminders:[120],repeatUntilDone:false,status:'active',completedDates:[],createdAt:Date.now()};state.tasks.push(__trip);window.__tripId=__trip.id;
  `);
  scriptParts.push(fs.readFileSync(path.join(root,source),'utf8'));
}
try{window.eval(scriptParts.join('\n;\n'))}catch(error){errors.push(`initialization: ${error.stack||error}`)}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),assert=(value,message)=>{if(!value)throw new Error(message)},run=async(name,test)=>{try{await test();console.log(`✓ ${name}`)}catch(error){errors.push(`${name}: ${error.stack||error}`);console.log(`✕ ${name}`)}};
const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,now=new Date(),todayKey=iso(now),tomorrowKey=iso(new Date(now.getFullYear(),now.getMonth(),now.getDate()+1));
function auditButtons(rootNode=window.document){rootNode.querySelectorAll('button').forEach(button=>assert(button.getAttribute('type'),`Button type missing: ${button.textContent.trim()}`))}
function auditHandlers(rootNode=window.document){const ignored=new Set(['if','for','while','switch','catch','function','setTimeout']);rootNode.querySelectorAll('[onclick]').forEach(element=>{const code=element.getAttribute('onclick')||'';for(const match of code.matchAll(/(?<![\w$.])([A-Za-z_$][\w$]*)\s*\(/g)){const name=match[1];if(ignored.has(name))continue;let value;try{value=window.eval(name)}catch{value=undefined}assert(typeof value==='function',`Unresolved onclick function ${name}: ${code}`)}})}
function sectionByTitle(rootNode,title){return [...rootNode.querySelectorAll('section')].find(section=>section.querySelector('h3')?.textContent.trim()===title)}

await run('script order and v3.2 version',async()=>{const v31=scriptSources.indexOf('chunk27.js'),v32=scriptSources.indexOf('chunk28.js');assert(v31>0&&v32>v31,'v3.2 patch order is wrong');assert(window.__shtabDiagnostics.uiVersion()==='3.2.0','UI version is not 3.2.0')});
await run('fixed header, permissions and hidden data remain safe',async()=>{const style=[...window.document.querySelectorAll('style')].map(node=>node.textContent).join('\n');assert(style.includes('.topbar{position:fixed!important'),'Top header is not fixed');await wait(650);assert(permissionRequests===1,'Initial permissions not requested once');assert(javaSource.includes('POST_NOTIFICATIONS')&&javaSource.includes('RECORD_AUDIO')&&javaSource.includes('ACTION_REQUEST_SCHEDULE_EXACT_ALARM'),'Required permissions incomplete');assert(!javaSource.includes('ACCESS_FINE_LOCATION')&&!javaSource.includes('READ_CONTACTS'),'Unnecessary permissions requested');const details=window.__shtabDiagnostics.taskHiddenDetails(window.__preserveTaskId);assert(details?.tags?.[0]==='скрытая метка'&&details?.subtasks?.[0]?.title==='Скрытая подзадача','Hidden task data was erased')});
await run('Important window has check left and exclamation right',async()=>{window.setPage('today');const page=window.document.querySelector('#today'),important=sectionByTitle(page,'Важное'),regular=sectionByTitle(page,'Задачи, поручения и события'),row=important?.querySelector(`[data-important-task-id="${window.__preserveTaskId}"]`);assert(row,'Important task row missing');const children=[...row.children];assert(children[0]?.classList.contains('task-check-v31'),'Completion check is not first');assert(children[0]?.textContent.trim()==='✓','Completion check is not visible');assert(children.at(-1)?.classList.contains('important-mark-right-v32'),'Exclamation is not on the right');assert(children.at(-1)?.textContent.trim()==='!','Right exclamation missing');assert(!regular?.textContent.includes('Важное поручение'),'Important task duplicated in regular window');const regularCheck=regular?.querySelector(`[data-task-id="${window.__eventId}"] .task-check-v31`);assert(regularCheck?.textContent.trim()==='✓','Regular completion check is not visible');assert(window.__shtabDiagnostics.importantTaskDuplicates()===0,'Important task is duplicated');auditButtons(page);auditHandlers(page)});
await run('Completion checks are available in Plan and Analytics',async()=>{window.setPage('plan');window.selectPlanDateV31(todayKey);let page=window.document.querySelector('#plan'),planRow=page.querySelector(`[data-plan-task-id="${window.__eventId}"]`);assert(planRow?.querySelector('.plan-check-v32')?.textContent.trim()==='✓','Plan completion check missing');window.setPage('analytics');window.setAnalyticsSectionV27('tasks');page=window.document.querySelector('#analytics');const analyticsRow=page.querySelector(`[data-analytics-task-id="${window.__eventId}"]`);assert(analyticsRow?.querySelector('.analytics-check-v32')?.textContent.trim()==='✓','Analytics completion check missing');assert(window.__shtabDiagnostics.visibleCompletionCount()>=3,'Too few visible completion controls');auditButtons(page);auditHandlers(page)});
await run('Task preview contains completion and edit actions',async()=>{window.setPage('today');const row=window.document.querySelector(`#today [data-task-id="${window.__eventId}"] .today-record-main-v30`);assert(row,'Event row missing');row.click();await wait(20);const view=window.document.querySelector('#task-view-dialog-v31'),editor=window.document.querySelector('#editor-dialog');assert(view?.open&&!editor.open,'Task preview did not open first');assert(view.querySelector('.task-view-complete-v32')?.textContent.includes('Выполнить'),'Completion action missing from preview');assert(view.querySelector('.task-view-edit-v31')?.textContent.includes('Изменить'),'Edit action missing from preview');view.querySelector('.task-view-edit-v31').click();await wait(100);assert(!view.open&&editor.open,'Pencil did not open editor');window.closeDialog('editor-dialog')});
await run('Plan calendar remains compact and list follows selected date',async()=>{window.setPage('plan');let page=window.document.querySelector('#plan'),style=[...window.document.querySelectorAll('style')].map(node=>node.textContent).join('\n');assert(page.querySelectorAll('.month-day').length===42,'Month calendar incomplete');assert(style.includes('#plan .month-day{min-height:43px'),'Compact calendar sizing missing');let list=sectionByTitle(page,'Записи выбранного дня');window.selectPlanDateV31(tomorrowKey);page=window.document.querySelector('#plan');list=sectionByTitle(page,'Записи выбранного дня');assert(window.__shtabDiagnostics.selectedPlanDate()===tomorrowKey,'Selected date did not change');assert(list.textContent.includes('Задача только завтра'),'Selected-date list did not update');assert(!list.textContent.includes('Обычное событие сегодня'),'Previous day event remained after date change');auditButtons(page);auditHandlers(page)});
await run('Projects, finance and navigation regressions',async()=>{window.openMore('projects');let page=window.document.querySelector('#more');assert(page.querySelectorAll('.directory-window-v30').length===2&&!page.textContent.includes('Архив'),'Projects directory regressed');window.setPage('finance');page=window.document.querySelector('#finance');assert(window.__shtabDiagnostics.financeSummaryCount()===1&&page.querySelector('.finance-summary-v28'),'Finance summary missing');const pages=[...window.document.querySelectorAll('.nav-item')].map(item=>item.dataset.page);assert(pages.join(',')==='today,plan,analytics,finance,more','Bottom navigation changed');auditButtons();auditHandlers()});
await run('all pages render without JavaScript errors',async()=>{for(const pageName of ['today','plan','analytics','finance','more','assistant']){window.setPage(pageName);assert(window.document.querySelector(`#${pageName}.active`),`${pageName} inactive`);auditButtons();auditHandlers()}});

if(errors.length){console.log('\nAudit failures:');errors.forEach(error=>console.log(`- ${error}`));process.exit(1)}
console.log('\nAll v3.2 completion controls, important layout and regression tests passed.');